import { cancelOrder, createOrder, createProduct, handleNewebPayCallback, initiatePayment, listOrderPayments, listOrders, listProducts, readOrder, readProduct, setProductStatus, updateProduct } from './commerce';

const known = /^COMMERCE_[A-Z0-9_]+$/;
function failure(c:any,error:unknown,fallback:string){const raw=error instanceof Error?error.message:'';const code=raw==='FORBIDDEN_ROLE'?'FORBIDDEN':known.test(raw)?raw:fallback;const status=code==='FORBIDDEN'?403:code.endsWith('_NOT_FOUND')?404:code.includes('PAID')||code.includes('ARCHIVED')||code.includes('CANCELLED')?409:400;return c.json({success:false,error:code},status);}

export function registerCommerceRoutes(app:any,deps:any){
  app.get('/api/commerce/products',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,products:await listProducts(c.env.smart_menu_db,deps.workspaceIdOf(c))});}catch(e){return failure(c,e,'COMMERCE_PRODUCT_LIST_FAILED')}});
  app.post('/api/commerce/products',async(c:any)=>{try{deps.requireRole(c,'admin');const product=await createProduct(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),userId:deps.text(c.get('userId'))||null,body:await c.req.json().catch(()=>({}))});return c.json({success:true,product},201);}catch(e){return failure(c,e,'COMMERCE_PRODUCT_CREATE_FAILED')}});
  app.get('/api/commerce/products/:safeProductReference',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,product:await readProduct(c.env.smart_menu_db,deps.workspaceIdOf(c),deps.text(c.req.param('safeProductReference'),100))});}catch(e){return failure(c,e,'COMMERCE_PRODUCT_READ_FAILED')}});
  app.patch('/api/commerce/products/:safeProductReference',async(c:any)=>{try{deps.requireRole(c,'admin');const product=await updateProduct(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),userId:deps.text(c.get('userId'))||null,reference:deps.text(c.req.param('safeProductReference'),100),body:await c.req.json().catch(()=>({}))});return c.json({success:true,product});}catch(e){return failure(c,e,'COMMERCE_PRODUCT_UPDATE_FAILED')}});
  app.post('/api/commerce/products/:safeProductReference/archive',async(c:any)=>{try{deps.requireRole(c,'admin');const product=await setProductStatus(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),userId:deps.text(c.get('userId'))||null,reference:deps.text(c.req.param('safeProductReference'),100),status:'ARCHIVED'});return c.json({success:true,product});}catch(e){return failure(c,e,'COMMERCE_PRODUCT_ARCHIVE_FAILED')}});
  app.get('/api/commerce/orders',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,orders:await listOrders(c.env.smart_menu_db,deps.workspaceIdOf(c))});}catch(e){return failure(c,e,'COMMERCE_ORDER_LIST_FAILED')}});
  app.post('/api/commerce/orders',async(c:any)=>{try{deps.requireRole(c,'admin');const order=await createOrder(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),userId:deps.text(c.get('userId'))||null,body:await c.req.json().catch(()=>({}))});return c.json({success:true,order},201);}catch(e){return failure(c,e,'COMMERCE_ORDER_CREATE_FAILED')}});
  app.get('/api/commerce/orders/:safeOrderReference',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,order:await readOrder(c.env.smart_menu_db,deps.workspaceIdOf(c),deps.text(c.req.param('safeOrderReference'),100))});}catch(e){return failure(c,e,'COMMERCE_ORDER_READ_FAILED')}});
  app.post('/api/commerce/orders/:safeOrderReference/cancel',async(c:any)=>{try{deps.requireRole(c,'admin');return c.json({success:true,order:await cancelOrder(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),reference:deps.text(c.req.param('safeOrderReference'),100)})});}catch(e){return failure(c,e,'COMMERCE_ORDER_CANCEL_FAILED')}});
  app.post('/api/commerce/orders/:safeOrderReference/payment-intents',async(c:any)=>{try{deps.requireRole(c,'admin');const body=await c.req.json().catch(()=>({}));const notifyUrl=new URL('/api/commerce/payments/newebpay/notify',c.req.url).toString();const payment=await initiatePayment(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),reference:deps.text(c.req.param('safeOrderReference'),100),body,env:c.env,notifyUrl});return c.json({success:true,payment},201);}catch(e){return failure(c,e,'COMMERCE_PAYMENT_INITIATE_FAILED')}});
  app.get('/api/commerce/orders/:safeOrderReference/payments',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,payments:await listOrderPayments(c.env.smart_menu_db,deps.workspaceIdOf(c),deps.text(c.req.param('safeOrderReference'),100))});}catch(e){return failure(c,e,'COMMERCE_PAYMENT_LIST_FAILED')}});
  app.post('/api/commerce/payments/newebpay/notify',async(c:any)=>{try{const length=Number(c.req.header('content-length')||0);if(length>65536)throw new Error('COMMERCE_PAYMENT_CALLBACK_TOO_LARGE');const raw=await c.req.text();if(raw.length>65536)throw new Error('COMMERCE_PAYMENT_CALLBACK_TOO_LARGE');const form=new URLSearchParams(raw);const tradeInfo=form.get('TradeInfo')||'',tradeShaValue=form.get('TradeSha')||'';if(!tradeInfo||!tradeShaValue)throw new Error('COMMERCE_PAYMENT_CALLBACK_INVALID');await handleNewebPayCallback(c.env.smart_menu_db,{env:c.env,tradeInfo,tradeShaValue,projectTravelPaymentMilestone:deps.projectTravelPaymentMilestone});return c.text('1|OK');}catch(e){const code=e instanceof Error&&known.test(e.message)?e.message:'COMMERCE_PAYMENT_CALLBACK_FAILED';return c.text(`0|${code}`,400)}});
}
