import React, { useEffect, useMemo, useState } from 'react';
import { labelAcquisitionSource, labelSegmentOperator, labelStatus, labelZodiac } from '../utils/presentationLabels';

const fields = [
  ['status','CRM 狀態'],['acquisition.firstSource','首次取得來源'],['acquisition.latestSource','最新取得來源'],['hasReferrer','有推薦人'],['tag','CRM 標籤'],['stage','銷售階段'],['assignedOwner','CRM 負責人'],['region','地區'],['preferredLanguage','偏好語言'],['hasVerifiedLineIdentity','已驗證 LINE'],['followUp.overdue','逾期跟進'],['followUp.hasOpen','待處理跟進'],['trait.zodiac','星座'],['createdAt','建立時間'],['updatedAt','更新時間'],
];
const boolFields=new Set(['hasReferrer','hasVerifiedLineIdentity','followUp.overdue','followUp.hasOpen']);
const dateFields=new Set(['createdAt','updatedAt']);
const sourceTypes=['LINE_ORGANIC','KEYWORD','RICH_MENU','QR','LINE_SHARE','REFERRAL_SHARE','PERSONAL_CARD_SHARE','EVENT','CSV_IMPORT','XLSX_IMPORT','OCR_IMPORT','API_IMPORT'];
const zodiac=['ARIES','TAURUS','GEMINI','CANCER','LEO','VIRGO','LIBRA','SCORPIO','SAGITTARIUS','CAPRICORN','AQUARIUS','PISCES'];
const safeApi=async(request,path,options)=>{const res=await request(path,options);const data=await res.json();if(!res.ok||!data.success)throw new Error(data.error||'REQUEST_FAILED');return data;};
const blank=()=>({field:'status',op:'EQ',value:'ACTIVE'});
const ops=(field)=>boolFields.has(field)?['IS_TRUE','IS_FALSE']:dateFields.has(field)?['BEFORE','AFTER']:['EQ','NEQ','IN','NOT_IN'];
const normalized=(conditions)=>({operator:'AND',conditions:conditions.map(c=>boolFields.has(c.field)?{field:c.field,op:c.op}:{field:c.field,op:c.op,value:['IN','NOT_IN'].includes(c.op)?String(c.value||'').split(',').map(x=>x.trim()).filter(Boolean):String(c.value||'')})});
const errorText=(error)=>({CRM_SEGMENT_RULE_INVALID:'Rule must use AND with at most 20 conditions.',CRM_SEGMENT_RULE_CONDITION_INVALID:'Unsupported condition.',CRM_SEGMENT_RULE_VALUE_INVALID:'Provide a valid condition value.',CRM_SEGMENT_REFERENCE_INVALID:'The selected CRM reference is unavailable.',CRM_SEGMENT_ASSIGNED_OWNER_INVALID:'The selected CRM owner is unavailable.'}[error]||'Unable to complete this segment request.');
const Bar=({label,count})=><div className="space-y-1"><div className="flex justify-between gap-3 text-sm"><span className="truncate">{label||'Unassigned'}</span><b>{Number(count||0)}</b></div><div className="h-2 rounded bg-slate-100"><div className="h-2 rounded bg-slate-700" style={{width:`${Math.min(100,Math.max(4,Number(count||0)*8))}%`}} /></div></div>;

export default function CrmAnalyticsPanel({request,userRole='viewer'}){
 const role=String(userRole).toLowerCase(), canManage=['owner','admin'].includes(role);
 const [period,setPeriod]=useState('30d'),[summary,setSummary]=useState(null),[loading,setLoading]=useState(true),[analyticsError,setAnalyticsError]=useState('');
 const [conditions,setConditions]=useState([blank()]),[references,setReferences]=useState({tags:[],stages:[],owners:[]}),[preview,set預覽]=useState(null),[previewError,set預覽Error]=useState(''),[previewing,set預覽ing]=useState(false);
 const [segments,setSegments]=useState([]),[selected,setSelected]=useState(null),[people,setPeople]=useState([]),[nextCursor,setNextCursor]=useState(null),[segmentBusy,setSegmentBusy]=useState(false),[name,setName]=useState(''),[description,setDescription]=useState('');
 const rule=useMemo(()=>normalized(conditions),[conditions]);
 const loadSummary=async()=>{setLoading(true);try{setSummary(await safeApi(request,`/api/crm/analytics-summary?period=${period}`));setAnalyticsError('');}catch(e){setAnalyticsError(e.message)}finally{setLoading(false)}};
 const loadSegments=async()=>{try{const data=await safeApi(request,'/api/crm/segments');setSegments(data.segments||[])}catch(e){setAnalyticsError(e.message)}};
 // oxlint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{void loadSummary()},[period]); // oxlint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{void loadSegments();safeApi(request,'/api/crm/tags').then(x=>setReferences(v=>({...v,tags:x.tags||[]}))).catch(()=>{});safeApi(request,'/api/crm/pipeline-stages').then(x=>setReferences(v=>({...v,stages:x.stages||[]}))).catch(()=>{});safeApi(request,'/api/crm/assignees').then(x=>setReferences(v=>({...v,owners:x.assignees||[]}))).catch(()=>{});},[]);
 const update=(index,patch)=>setConditions(all=>all.map((c,i)=>i===index?{...c,...patch}:c));
 const values=(field)=>field==='tag'?references.tags.map(x=>[x.safeTagReference||x.tagReference,x.name||x.label]):field==='stage'?references.stages.map(x=>[x.stageReference,x.name||x.stageLabel]):field==='assignedOwner'?references.owners.map(x=>[x.assignedUserReference,x.displayLabel]):field.startsWith('acquisition.')?sourceTypes.map(x=>[x,labelAcquisitionSource(x)]):field==='trait.zodiac'?zodiac.map(x=>[x,labelZodiac(x)]):[];
 const run預覽=async()=>{set預覽ing(true);set預覽Error('');try{set預覽(await safeApi(request,'/api/crm/segments/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rule})}))}catch(e){set預覽(null);set預覽Error(errorText(e.message))}finally{set預覽ing(false)}};
 const save=async(edit=false)=>{if(!canManage)return;setSegmentBusy(true);try{const path=edit?`/api/crm/segments/${encodeURIComponent(selected.safeSegmentReference)}`:'/api/crm/segments';const data=await safeApi(request,path,{method:edit?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name||selected?.name,description,rule})});setSelected(data.segment);await loadSegments()}catch(e){set預覽Error(errorText(e.message))}finally{setSegmentBusy(false)}};
 const openSegment=async(segment)=>{try{const data=await safeApi(request,`/api/crm/segments/${encodeURIComponent(segment.safeSegmentReference)}`);setSelected(data.segment);setName(data.segment.name||'');setDescription(data.segment.description||'');setConditions(data.segment.rule?.conditions||[blank()]);setPeople([]);setNextCursor(null)}catch(e){set預覽Error(errorText(e.message))}};
 const loadPeople=async(cursor='')=>{if(!selected)return;try{const path=`/api/crm/segments/${encodeURIComponent(selected.safeSegmentReference)}/people?limit=25${cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`;const data=await safeApi(request,path);setPeople(existing=>cursor?[...existing,...(data.people||[])]:data.people||[]);setNextCursor(data.nextCursor||null)}catch(e){set預覽Error(errorText(e.message))}};
 const archive=async()=>{if(!selected||!canManage)return;setSegmentBusy(true);try{await safeApi(request,`/api/crm/segments/${encodeURIComponent(selected.safeSegmentReference)}/status`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'ARCHIVED'})});await loadSegments();setSelected(x=>x?{...x,status:'ARCHIVED'}:x)}catch(e){set預覽Error(errorText(e.message))}finally{setSegmentBusy(false)}};
 const metrics=summary?[['CRM 客戶總數',summary.totalPeople],['新增 CRM 客戶',summary.newPeopleInPeriod],['已驗證 LINE',summary.peopleWithLineIdentity],['未驗證 LINE',summary.peopleWithoutLineIdentity],['有推薦人',summary.peopleWithReferrer],['無推薦人',summary.peopleWithoutReferrer],['待處理跟進',summary.openFollowUpCount],['逾期跟進',summary.overdueFollowUpCount]]:[];
 return <section data-testid="crm-analytics-panel" className="space-y-6">
  <header className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-bold">CRM 分析</h2><p className="text-sm text-gray-500">唯讀 CRM 分布與即時計算的客戶區隔。</p></div><div className="flex gap-2"><button onClick={()=>setPeriod('7d')} className={`rounded px-3 py-2 text-sm ${period==='7d'?'bg-slate-800 text-white':'border'}`}>7d</button><button onClick={()=>setPeriod('30d')} className={`rounded px-3 py-2 text-sm ${period==='30d'?'bg-slate-800 text-white':'border'}`}>30d</button></div></header>
  {analyticsError&&<p role="alert" className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">目前無法讀取 CRM 分析資料。</p>}
  {loading?<p>正在讀取 CRM 分析資料…</p>:summary&&<><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{metrics.map(([label,value])=><div key={label} className="rounded border bg-white p-4"><div className="text-xs text-gray-500">{label}</div><b className="text-2xl">{Number(value||0)}</b></div>)}</div><div className="grid gap-4 lg:grid-cols-2">{[['階段分布',summary.peopleByStage,'stageLabel'],['最新取得來源',summary.peopleByAcquisitionSource,'sourceType'],['CRM 標籤分布',summary.peopleByTag,'tagLabel'],['CRM 負責人分布',summary.peopleByAssignedOwner,'ownerLabel']].map(([title,rows,key])=><article key={title} className="rounded border bg-white p-4"><h3 className="font-semibold">{title}</h3><div className="mt-3 space-y-3">{rows.length?rows.map(row=><Bar key={row[key]} label={row[key]} count={row.count}/>):<p className="text-sm text-gray-500">目前沒有資料。</p>}</div></article>)}</div></>}
  <article className="rounded-xl border bg-white p-5"><h2 className="font-bold">客戶區隔建立器</h2><p className="mt-1 text-sm text-gray-500">僅支援 AND 條件。即時結果使用目前 CRM 資料，不會保存客群快照。</p><div className="mt-4 space-y-3">{conditions.map((condition,index)=><div key={index} className="grid gap-2 md:grid-cols-4"><select value={condition.field} onChange={e=>update(index,{field:e.target.value,op:ops(e.target.value)[0],value:''})} className="rounded border p-2">{fields.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select value={condition.op} onChange={e=>update(index,{op:e.target.value})} className="rounded border p-2">{ops(condition.field).map(op=><option key={op}>{labelSegmentOperator(op)}</option>)}</select>{boolFields.has(condition.field)?<span className="rounded border bg-gray-50 p-2 text-sm">布林條件</span>:values(condition.field).length?<select value={condition.value||''} onChange={e=>update(index,{value:e.target.value})} className="rounded border p-2"><option value="">請選擇…</option>{values(condition.field).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:<input value={condition.value||''} onChange={e=>update(index,{value:e.target.value})} placeholder={dateFields.has(condition.field)?'ISO 日期':'值'} className="rounded border p-2"/>}<button type="button" disabled={conditions.length===1} onClick={()=>setConditions(all=>all.filter((_,i)=>i!==index))} className="rounded border px-3 text-sm disabled:opacity-50">移除</button></div>)}</div><div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={conditions.length>=20} onClick={()=>setConditions(all=>[...all,blank()])} className="rounded border px-3 py-2 text-sm disabled:opacity-50">新增條件</button><button type="button" onClick={run預覽} disabled={previewing} className="rounded bg-slate-800 px-3 py-2 text-sm text-white">{previewing?'驗證中…':'預覽'}</button>{canManage&&<button type="button" onClick={()=>save(false)} disabled={segmentBusy||!name.trim()} className="rounded bg-blue-700 px-3 py-2 text-sm text-white">儲存客戶區隔</button>}<input aria-label="客戶區隔名稱" value={name} onChange={e=>setName(e.target.value)} placeholder="客戶區隔名稱" className="rounded border p-2 text-sm"/></div>{previewError&&<p role="alert" className="mt-3 text-sm text-red-700">{previewError}</p>}{preview&&<div className="mt-4 rounded bg-slate-50 p-3 text-sm"><b>{preview.totalCount} 位客戶</b>{preview.truncated&&<p>僅顯示前 25 位符合條件的客戶。</p>}<div className="mt-2 space-y-1">{(preview.previewPeople||[]).map((person,i)=><p key={person.personRef||i}>{person.profile?.contactName||person.profile?.displayName||'CRM 客戶'} {person.profile?.companyName||''}</p>)}</div></div>}</article>
  <div className="grid gap-4 lg:grid-cols-2"><article className="rounded border bg-white p-4"><h2 className="font-bold">已儲存的客戶區隔</h2><div className="mt-3 space-y-2">{segments.length?segments.map(segment=><button key={segment.safeSegmentReference} onClick={()=>openSegment(segment)} className="block w-full rounded border p-3 text-left hover:bg-gray-50"><b>{segment.name}</b><div className="text-xs text-gray-500">{labelStatus(segment.status)} · v{segment.currentVersion}</div></button>):<p className="text-sm text-gray-500">目前沒有已儲存的客戶區隔。</p>}</div></article>{selected&&<article className="rounded border bg-white p-4"><h2 className="font-bold">{selected.name}</h2><p className="mt-1 text-sm text-gray-500">版本 {selected.currentVersion||selected.currentVersionNo} · {labelStatus(selected.status)}</p><p className="mt-2 text-sm">編輯會建立新的不可變版本；歷程維持唯讀。</p><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>loadPeople()} className="rounded bg-slate-800 px-3 py-2 text-sm text-white">載入即時客戶</button>{canManage&&selected.status==='ACTIVE'&&<><button onClick={()=>save(true)} disabled={segmentBusy} className="rounded border px-3 py-2 text-sm">儲存新版本</button><button onClick={archive} disabled={segmentBusy} className="rounded border border-amber-300 px-3 py-2 text-sm text-amber-800">封存客戶區隔</button></>}</div><div className="mt-3 space-y-1 text-sm">{(selected.versions||[]).map(v=><p key={v.version}>v{v.version} · {v.createdAt||''}</p>)}</div><p className="mt-3 text-xs text-gray-500">客戶區隔會依目前 CRM 資料即時計算。</p><div className="mt-3 space-y-2">{people.map((person,i)=><p key={person.personRef||i} className="rounded bg-slate-50 p-2 text-sm">{person.profile?.contactName||person.profile?.displayName||'CRM 客戶'} {person.profile?.companyName||''}</p>)}{nextCursor&&<button onClick={()=>loadPeople(nextCursor)} className="rounded border px-3 py-2 text-sm">載入更多</button>}</div></article>}</div>
 </section>;
}