import React, { useCallback, useEffect, useRef, useState } from 'react';
import { CheckCircle2, Loader2, MapPin, Minus, Plus, RefreshCw } from 'lucide-react';
import { loadLiffSdk, referralContextFromLocation, usableLiffConfig } from '../liff-referral';
import { dateOnly, dateTime, isBookingFullyPaid, isBookingPaymentFailed, money, paymentLegLabel, paymentScheduleLabel, travelEventLabel, travelerTypeLabel, travelStatusLabel } from '../travel-presentation';
import { travelFulfillmentLabel, travelMemberPaymentLabel } from '../travel-operations-presentation';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || import.meta.env.VITE_PRODUCTION_WORKER_BASE_URL || (import.meta.env.PROD ? 'https://smart-menu-backend.fangwl591021.workers.dev' : 'http://127.0.0.1:8788');
const POLL_INTERVAL_MS = 4000;
const POLL_LIMIT_MS = 60000;
const api = (path, options) => fetch(`${API_BASE_URL}${path}`, options);
async function readJson(response) { const body = await response.json().catch(() => ({})); if (!response.ok || !body?.success) throw new Error(body?.error || 'REQUEST_FAILED'); return body; }
function memberRequest(auth, path, options = {}) { const query = path.includes('?') ? '&' : '?'; const headers = new Headers(options.headers || {}); headers.set('Authorization', `Bearer ${auth.accessToken}`); return api(`${path}${query}lineAccountId=${encodeURIComponent(auth.lineAccountId)}`, { ...options, headers }); }
function submitCheckout(checkout) { if (!checkout?.gatewayUrl) throw new Error('CHECKOUT_UNAVAILABLE'); const form = document.createElement('form'); form.method = 'POST'; form.action = checkout.gatewayUrl; for (const name of ['MerchantID', 'TradeInfo', 'TradeSha', 'Version']) { const input = document.createElement('input'); input.type = 'hidden'; input.name = name; input.value = String(checkout[name] || ''); form.appendChild(input); } document.body.appendChild(form); form.submit(); form.remove(); }
async function pollTravelBooking({ auth, safeBookingReference, paymentLeg, onUpdate, signal, intervalMs = POLL_INTERVAL_MS, limitMs = POLL_LIMIT_MS }) { const startedAt = Date.now(); while (!signal?.aborted) { const body = await readJson(await memberRequest(auth, `/api/member/travel/bookings/${encodeURIComponent(safeBookingReference)}`)); onUpdate(body.booking); const target = body.booking.paymentSchedule?.find(item => item.paymentLeg === paymentLeg); if (isBookingFullyPaid(body.booking) || ['PAID', 'FAILED', 'CANCELLED'].includes(target?.status)) return body.booking; if (Date.now() - startedAt >= limitMs) return null; await new Promise(resolve => { const timeout = setTimeout(resolve, intervalMs); signal?.addEventListener('abort', () => { clearTimeout(timeout); resolve(); }, { once: true }); }); } return null; }

function paymentConfirmationMessage(booking, paymentLeg) { const target = booking.paymentSchedule?.find(item => item.paymentLeg === paymentLeg); if (isBookingFullyPaid(booking)) return '款項已付清'; if (target?.status === 'PAID' && paymentLeg === 'DEPOSIT') return '訂金已完成'; if (target?.status === 'PAID') return `${paymentLegLabel(paymentLeg)}付款已確認。`; if (isBookingPaymentFailed(booking)) return '付款未完成，您可以重新發起該筆款項。'; return '正在確認付款結果…'; }

function paymentActionLabel(paymentLeg) { return paymentLeg === 'FULL' ? '前往付款' : paymentLeg === 'DEPOSIT' ? '支付訂金' : '支付尾款'; }

function MemberCover({ auth, src, alt }) { const [url, setUrl] = useState(''); useEffect(() => { let active = true; let objectUrl = ''; if (!src) return undefined; memberRequest(auth, src).then(response => { if (!response.ok) throw new Error(); return response.blob(); }).then(blob => { objectUrl = URL.createObjectURL(blob); if (active) setUrl(objectUrl); }).catch(() => {}); return () => { active = false; if (objectUrl) URL.revokeObjectURL(objectUrl); }; }, [auth, src]); return url ? <img src={url} alt={alt} className="h-44 w-full rounded-xl object-cover" /> : <div className="flex h-44 items-center justify-center rounded-xl bg-blue-50 text-blue-300"><MapPin size={36} /></div>; }

const newTraveler = () => ({ displayName: '', travelerType: 'ADULT', phone: '', note: '' });
function TravelerForm({ travelers, setTravelers }) { const resize = count => setTravelers(current => Array.from({ length: Math.max(1, Math.min(100, count)) }, (_, index) => current[index] || newTraveler())); const update = (index, name, value) => setTravelers(current => current.map((traveler, i) => i === index ? { ...traveler, [name]: value } : traveler)); return <section className="rounded-xl bg-white p-5 shadow-sm" aria-label="旅客資料"><div className="flex items-center justify-between"><div><h2 className="font-bold">旅客資料</h2><p className="text-xs text-slate-500">送出後將保存當次訂位快照。</p></div><div className="flex items-center gap-2"><button type="button" onClick={() => resize(travelers.length - 1)} className="rounded border p-1" aria-label="減少旅客"><Minus size={15} /></button><b>{travelers.length} 位</b><button type="button" onClick={() => resize(travelers.length + 1)} className="rounded border p-1" aria-label="增加旅客"><Plus size={15} /></button></div></div><div className="mt-4 space-y-4">{travelers.map((traveler, index) => <fieldset key={index} className="rounded-lg border p-4"><legend className="px-2 text-sm font-bold">旅客 {index + 1}</legend><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">姓名<input required value={traveler.displayName} maxLength={120} onChange={event => update(index, 'displayName', event.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2" /></label><label className="text-sm">旅客類型<select value={traveler.travelerType} onChange={event => update(index, 'travelerType', event.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2"><option value="ADULT">成人</option><option value="CHILD">兒童</option><option value="INFANT">嬰兒</option></select></label><label className="text-sm">聯絡電話（選填）<input value={traveler.phone} maxLength={40} onChange={event => update(index, 'phone', event.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2" /></label><label className="text-sm">備註（選填）<input value={traveler.note} maxLength={500} onChange={event => update(index, 'note', event.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2" /></label></div></fieldset>)}</div></section>; }

function TravelMemberExperience({ auth }) {
  const [state, setState] = useState({ loading: true, itineraries: [], departures: [], bookings: [], itinerary: null, departure: null, booking: null, events: [], travelers: [newTraveler()], busy: '', error: '', paymentMessage: '', confirming: false });
  const pollAbortRef = useRef(null);
  const load = useCallback(async () => { setState(value => ({ ...value, loading: true, error: '' })); try { const [itineraries, bookings] = await Promise.all([readJson(await memberRequest(auth, '/api/member/travel/itineraries')), readJson(await memberRequest(auth, '/api/member/travel/bookings'))]); setState(value => ({ ...value, loading: false, itineraries: itineraries.itineraries || [], bookings: bookings.bookings || [] })); } catch { setState(value => ({ ...value, loading: false, error: '目前無法讀取旅遊資料，請稍後再試。' })); } }, [auth]);
  const openItinerary = async item => { setState(value => ({ ...value, busy: 'itinerary', error: '' })); try { const ref = encodeURIComponent(item.safeItineraryReference); const [detail, departures] = await Promise.all([readJson(await memberRequest(auth, `/api/member/travel/itineraries/${ref}`)), readJson(await memberRequest(auth, `/api/member/travel/itineraries/${ref}/departures`))]); setState(value => ({ ...value, busy: '', itinerary: detail.itinerary, departures: departures.departures || [], departure: null })); } catch { setState(value => ({ ...value, busy: '', error: '目前無法讀取行程詳情。' })); } };
  const openDeparture = async item => { try { const body = await readJson(await memberRequest(auth, `/api/member/travel/departures/${encodeURIComponent(item.safeDepartureReference)}`)); setState(value => ({ ...value, departure: body.departure, error: '' })); } catch { setState(value => ({ ...value, error: '此出發日目前無法購買。' })); } };
  const openBooking = useCallback(async reference => { const ref = encodeURIComponent(reference); try { const [detail, timeline] = await Promise.all([readJson(await memberRequest(auth, `/api/member/travel/bookings/${ref}`)), readJson(await memberRequest(auth, `/api/member/travel/bookings/${ref}/events`))]); setState(value => ({ ...value, booking: detail.booking, events: timeline.events || [], error: '' })); return detail.booking; } catch { setState(value => ({ ...value, error: '目前無法讀取您的訂位。' })); return null; } }, [auth]);
  const createBooking = async event => { event.preventDefault(); if (!state.departure || state.travelers.some(item => !item.displayName.trim())) return; setState(value => ({ ...value, busy: 'booking', error: '' })); try { const body = await readJson(await memberRequest(auth, '/api/member/travel/bookings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ safeDepartureReference: state.departure.safeDepartureReference, travelers: state.travelers.map(item => ({ ...item, displayName: item.displayName.trim(), phone: item.phone.trim(), note: item.note.trim() })) }) })); setState(value => ({ ...value, busy: '', booking: body.booking, travelers: [newTraveler()] })); await load(); await openBooking(body.booking.safeBookingReference); } catch (error) { const full = error?.message === 'TRAVEL_DEPARTURE_CAPACITY_EXCEEDED'; setState(value => ({ ...value, busy: '', error: full ? '剩餘名額不足，請重新選擇旅客人數。' : '訂位未建立，價格、報名期間或名額可能已更新。' })); } };
  const confirmPayment = useCallback(async (reference, paymentLeg) => { pollAbortRef.current?.abort(); const controller = new AbortController(); pollAbortRef.current = controller; setState(value => ({ ...value, confirming: true, paymentMessage: '正在確認付款結果…', error: '' })); try { const result = await pollTravelBooking({ auth, safeBookingReference: reference, paymentLeg, signal: controller.signal, onUpdate: booking => setState(value => ({ ...value, booking, paymentMessage: paymentConfirmationMessage(booking, paymentLeg) })) }); if (!controller.signal.aborted) { if (!result) setState(value => ({ ...value, confirming: false, paymentMessage: '付款結果仍在確認中，您可以稍後重新整理查看。' })); else { setState(value => ({ ...value, confirming: false })); await load(); await openBooking(reference); } } } catch { if (!controller.signal.aborted) setState(value => ({ ...value, confirming: false, paymentMessage: '付款結果仍在確認中，您可以稍後重新整理查看。' })); } }, [auth, load, openBooking]);
  useEffect(() => { load(); return () => pollAbortRef.current?.abort(); }, [load]);
  const pay = async (booking, leg) => { setState(value => ({ ...value, busy: `payment-${leg}`, error: '' })); try { const body = await readJson(await memberRequest(auth, `/api/member/travel/bookings/${encodeURIComponent(booking.safeBookingReference)}/payment-intents`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ paymentLeg: leg }) })); submitCheckout(body.payment?.checkout); } catch { setState(value => ({ ...value, busy: '', error: '目前無法前往付款，請稍後再試。' })); } };
  if (state.loading) return <div className="flex justify-center gap-2 py-16 text-sm"><Loader2 className="animate-spin" size={18} />正在讀取旅遊資料…</div>;
  return <div className="space-y-6">{(state.paymentMessage || state.confirming) && <div className={`rounded-xl p-4 text-sm ${state.paymentMessage === '款項已付清' ? 'bg-emerald-50 text-emerald-900' : 'bg-blue-50 text-blue-900'}`} aria-live="polite"><div className="flex items-center gap-2">{state.confirming ? <Loader2 className="animate-spin" size={18} /> : state.paymentMessage === '款項已付清' ? <CheckCircle2 size={18} /> : <RefreshCw size={18} />}{state.paymentMessage}</div></div>}{state.error && <p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900">{state.error}</p>}
    <section aria-label="旅遊行程"><div className="flex justify-between"><div><h2 className="text-xl font-bold">行程</h2><p className="text-sm text-slate-500">選擇已發布的行程與可購買出發日。</p></div><button onClick={load} className="rounded-lg border p-2"><RefreshCw size={17} /></button></div><div className="mt-4 grid gap-4 sm:grid-cols-2">{state.itineraries.map(item => <button key={item.safeItineraryReference} type="button" onClick={() => openItinerary(item)} className="rounded-xl bg-white p-4 text-left shadow-sm"><MemberCover auth={auth} src={item.coverUrl} alt={item.title} /><h3 className="mt-3 font-bold">{item.title}</h3><p className="mt-1 text-sm text-slate-500">{item.region || '行程地區'} · {item.durationDays} 天</p><p className="mt-2 line-clamp-3 text-sm">{item.summary}</p></button>)}</div>{state.itineraries.length === 0 && <p className="mt-4 rounded-xl bg-white p-5 text-sm text-slate-500">目前沒有已發布行程。</p>}</section>
    {state.itinerary && <section aria-label="出發日"><h2 className="text-xl font-bold">{state.itinerary.title} — 出發日</h2><p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{state.itinerary.notes}</p><div className="mt-4 space-y-3">{state.departures.map(item => <button type="button" key={item.safeDepartureReference} onClick={() => openDeparture(item)} className="w-full rounded-xl bg-white p-4 text-left shadow-sm"><div className="flex justify-between"><b>{dateOnly(item.departureDate)} ～ {dateOnly(item.returnDate)}</b><span>{money(item.priceAmountMinor)} / 人</span></div><p className="mt-2 text-sm text-slate-500">剩餘 {item.remainingSeats} 位 · {paymentScheduleLabel(item.paymentScheduleType)} · 報名至 {dateTime(item.bookingClosesAt)}</p></button>)}</div></section>}
    {state.departure && <form onSubmit={createBooking} className="space-y-4"><section className="rounded-xl border border-blue-100 bg-blue-50 p-5"><h2 className="font-bold">選定出發日</h2><p className="mt-2 text-sm">{dateOnly(state.departure.departureDate)} ～ {dateOnly(state.departure.returnDate)} · 剩餘 {state.departure.remainingSeats} 位</p><p className="mt-1 text-sm">{money(state.departure.priceAmountMinor)} / 人 · {paymentScheduleLabel(state.departure.paymentScheduleType)}</p></section><TravelerForm travelers={state.travelers} setTravelers={travelers => setState(value => ({ ...value, travelers: typeof travelers === 'function' ? travelers(value.travelers) : travelers }))} /><button disabled={state.busy === 'booking' || state.travelers.length > state.departure.remainingSeats} className="w-full rounded-xl bg-slate-900 px-4 py-3 font-bold text-white disabled:opacity-50">{state.busy === 'booking' ? '立即報名中…' : '立即報名'}</button></form>}
    <section aria-label="我的旅遊訂單"><h2 className="text-xl font-bold">我的旅遊訂單</h2><div className="mt-4 space-y-3">{state.bookings.map(item => <button type="button" key={item.safeBookingReference} onClick={() => openBooking(item.safeBookingReference)} className="w-full rounded-xl bg-white p-4 text-left shadow-sm"><div className="flex justify-between gap-3"><b>{item.itineraryTitle}</b><span>{money(item.totalAmountMinor)}</span></div><p className="mt-2 text-sm text-slate-500">{dateOnly(item.departureDate)} · {item.travelerCount} 位 · {travelStatusLabel(item.bookingStatus)}</p></button>)}</div></section>
    {state.booking && <section className="rounded-xl border bg-white p-5" aria-label="訂位詳情"><h2 className="text-xl font-bold">訂位詳情</h2><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><p><span className="text-slate-500">行程</span><br /><b>{state.booking.itineraryTitle}</b></p><p><span className="text-slate-500">出發日</span><br /><b>{state.booking.departureDate}</b></p><p><span className="text-slate-500">報名狀態</span><br /><b>{travelStatusLabel(state.booking.bookingStatus)}</b></p><p><span className="text-slate-500">付款狀態</span><br /><b>{travelMemberPaymentLabel(state.booking.bookingStatus)}</b></p><p><span className="text-slate-500">履約進度</span><br /><b>{travelFulfillmentLabel(state.booking.fulfillment?.state)}</b>{state.booking.fulfillment?.confirmedAt && <small className="block text-slate-500">確認：{dateTime(state.booking.fulfillment.confirmedAt)}</small>}{state.booking.fulfillment?.completedAt && <small className="block text-slate-500">完成：{dateTime(state.booking.fulfillment.completedAt)}</small>}</p><p><span className="text-slate-500">總額</span><br /><b>{money(state.booking.totalAmountMinor)}</b></p></div><h3 className="mt-5 font-bold">旅客</h3><div className="mt-2 space-y-2">{state.booking.travelers.map(item => <div key={item.sequence} className="rounded bg-slate-50 p-3 text-sm"><b>{item.displayName}</b> · {travelerTypeLabel(item.travelerType)}{item.phone && <p>聯絡電話：{item.phone}</p>}{item.note && <p>備註：{item.note}</p>}</div>)}</div><h3 className="mt-5 font-bold">付款排程</h3><div className="mt-2 space-y-2">{state.booking.paymentSchedule.map(item => <div key={item.paymentLeg} className="rounded border p-3"><div className="flex justify-between text-sm"><span><b>{paymentLegLabel(item.paymentLeg)}</b> · {travelStatusLabel(item.status)}</span><b>{money(item.amountMinor)}</b></div>{item.dueAt && <p className="mt-1 text-xs text-slate-500">期限：{dateTime(item.dueAt)}</p>}{item.status !== 'PAID' && <button disabled={state.busy === `payment-${item.paymentLeg}`} onClick={() => pay(state.booking, item.paymentLeg)} className="mt-3 rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white">{state.busy === `payment-${item.paymentLeg}` ? '準備付款中…' : paymentActionLabel(item.paymentLeg)}</button>}</div>)}</div>{isBookingFullyPaid(state.booking) ? <p className="mt-4 inline-flex items-center gap-2 rounded-lg bg-emerald-50 px-4 py-2 text-sm font-bold text-emerald-800"><CheckCircle2 size={17} />款項已付清</p> : <button onClick={() => confirmPayment(state.booking.safeBookingReference, state.booking.paymentSchedule.find(item => item.status !== 'PAID')?.paymentLeg || 'FULL')} className="mt-4 rounded-lg border px-4 py-2 text-sm">重新確認付款狀態</button>}<h3 className="mt-6 font-bold">行程進度</h3><ol className="mt-3 space-y-3">{state.events.map((event, index) => <li key={`${event.occurredAt}-${index}`} className="border-l-2 border-blue-200 pl-4"><b className="text-sm">{travelEventLabel(event)}</b><p className="text-xs text-slate-500">{dateTime(event.occurredAt)}</p></li>)}</ol></section>}
  </div>;
}

export default function LiffTravelPage() { const [state, setState] = useState({ loading: true, auth: null, error: '' }); useEffect(() => { let active = true; (async () => { const initial = referralContextFromLocation(); if (!initial.lineAccountId) { if (active) setState({ loading: false, auth: null, error: '找不到 LINE 官方帳號設定。' }); return; } try { const response = await api(`/api/member/referral/bootstrap?lineAccountId=${encodeURIComponent(initial.lineAccountId)}`); const bootstrap = await response.json(); if (!response.ok || !bootstrap?.success || !usableLiffConfig(bootstrap.config)) throw new Error('旅遊服務尚未完成 LIFF 設定。'); const liff = await loadLiffSdk(); await liff.init({ liffId: bootstrap.config.liffId }); if (!liff.isLoggedIn()) { liff.login(); return; } const accessToken = liff.getAccessToken(); if (!accessToken) throw new Error('無法取得 LINE 登入權杖。'); const context = referralContextFromLocation(); const establishResponse = await api('/api/member/establish', { method: 'POST', headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ lineAccountId: context.lineAccountId, liffAccessToken: accessToken }) }); const establish = await establishResponse.json(); if (!establishResponse.ok || !establish?.success) throw new Error('會員身分確認失敗。'); if (active) setState({ loading: false, auth: { lineAccountId: context.lineAccountId, accessToken }, error: '' }); } catch (error) { if (active) setState({ loading: false, auth: null, error: error?.message || '旅遊服務暫時無法使用。' }); } })(); return () => { active = false; }; }, []); if (state.loading) return <main className="flex min-h-screen items-center justify-center gap-2 bg-slate-50"><Loader2 className="animate-spin" size={20} />正在驗證會員身分…</main>; if (!state.auth) return <main className="flex min-h-screen items-center justify-center bg-slate-50 p-6"><section className="rounded-2xl bg-white p-6 text-center shadow"><h1 className="text-xl font-bold">旅遊服務暫時無法使用</h1><p className="mt-3 text-sm text-slate-600">{state.error}</p></section></main>; return <main className="min-h-screen bg-slate-50 p-4 text-slate-900"><div className="mx-auto max-w-3xl"><header className="mb-6 flex items-center gap-3"><span className="rounded-xl bg-blue-700 p-3 text-white"><MapPin size={24} /></span><div><h1 className="text-2xl font-bold">旅遊行程</h1><p className="text-sm text-slate-500">查看行程、立即報名並處理付款。</p></div></header><TravelMemberExperience auth={state.auth} /></div></main>; }
