import React, { useCallback, useEffect, useState } from 'react';

const score = value => Number(value || 0).toLocaleString('zh-TW');
const eventLabel = value => ({ QUALIFIED_REFERRAL: '完成推薦資格', VERIFIED_REFERRAL_CONVERSION: '已驗證推薦轉換', COMPLETED_REWARD_REDEMPTION: '完成獎勵兌換' }[value] || value);

export default function MemberContributionTierPanel({ request, auth }) {
  const [period, setPeriod] = useState('30d'); const [state, setState] = useState({ loading: true, data: null, error: '' });
  const load = useCallback(async selected => { if (!auth?.lineAccountId || !auth?.accessToken) return; setState(value => ({ ...value, loading: true, error: '' })); try { const response = await request(`/api/member/contribution?lineAccountId=${encodeURIComponent(auth.lineAccountId)}&period=${selected}`, { headers: { Authorization: `Bearer ${auth.accessToken}` } }); const body = await response.json(); if (!response.ok || !body?.success) throw new Error(); setState({ loading: false, data: body, error: '' }); } catch { setState({ loading: false, data: null, error: '目前無法讀取我的貢獻分數。' }); } }, [auth, request]);
  useEffect(() => { load(period); }, [load, period]);
  const changePeriod = value => { setPeriod(value); };
  const data = state.data;
  return <section className="mt-5 rounded-xl border border-slate-200 p-4" aria-label="My Contribution Tier"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold">我的貢獻分數與等級</h2><p className="mt-1 text-xs text-slate-500">等級為資格紀錄，目前不包含折扣、額外點數、佣金或金流權益。</p></div><div className="flex gap-1">{['7d', '30d'].map(value => <button key={value} type="button" onClick={() => changePeriod(value)} className={period === value ? 'rounded bg-slate-900 px-2 py-1 text-xs text-white' : 'rounded border px-2 py-1 text-xs'}>{value}</button>)}</div></div>{state.loading && <p className="mt-3 text-sm text-slate-500">載入中…</p>}{state.error && <p className="mt-3 rounded bg-amber-50 p-3 text-sm text-amber-900">{state.error}</p>}{!state.loading && data && <><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded bg-slate-50 p-3"><div className="text-xs text-slate-500">我的貢獻分數</div><b className="text-xl">{score(data.contributionScore)}</b></div><div className="rounded bg-slate-50 p-3"><div className="text-xs text-slate-500">目前等級</div><b className="text-xl">{data.currentTier?.tierName || data.currentTier?.tierCode || 'NO_TIER'}</b></div></div>{data.nextTier ? <div className="mt-3 rounded bg-blue-50 p-3 text-sm text-blue-900">下一個等級：<b>{data.nextTier.tierName || data.nextTier.tierCode}</b>，還需要 <b>{score(data.nextTier.scoreToNextTier)} 貢獻分數</b>。</div> : <p className="mt-3 rounded bg-slate-50 p-3 text-sm text-slate-600">目前沒有下一個等級門檻。</p>}<div className="mt-5"><h3 className="font-bold">近期貢獻紀錄</h3>{(data.recentHistory || []).length ? <div className="mt-2 space-y-2">{data.recentHistory.map((row, index) => <div key={`${row.eventType}-${row.effectiveAt}-${index}`} className="flex justify-between rounded border border-slate-100 p-3 text-sm"><span>{eventLabel(row.eventType)}<small className="block text-slate-500">{row.effectiveAt}</small></span><b>+{score(row.scoreDelta)} 貢獻分數</b></div>)}</div> : <p className="mt-2 rounded bg-slate-50 p-3 text-sm text-slate-600">目前還沒有貢獻紀錄。</p>}</div><div className="mt-5"><h3 className="font-bold">貢獻來源</h3><div className="mt-2 space-y-2">{(data.eventTypeBreakdown || []).map(row => <div key={row.eventType} className="flex justify-between rounded border border-slate-100 p-2 text-sm"><span>{eventLabel(row.eventType)}</span><b>{score(row.scoreDelta)} 貢獻分數</b></div>)}</div></div></>}</section>;
}
