import React, { useCallback, useEffect, useState } from 'react';

const points = value => Number(value || 0).toLocaleString('zh-TW');

export default function MemberRewardRedemptionPanel({ request, auth }) {
  const [state, setState] = useState({ loading: true, points: null, rewards: [], history: [], error: '', busy: '' });
  const load = useCallback(async () => { if (!auth?.lineAccountId || !auth?.accessToken) return; setState(value => ({ ...value, loading: true, error: '' })); try { const headers = { Authorization: `Bearer ${auth.accessToken}` }; const query = `lineAccountId=${encodeURIComponent(auth.lineAccountId)}`; const [pointResponse, rewardResponse, historyResponse] = await Promise.all([request(`/api/member/points?${query}`, { headers }), request(`/api/member/rewards?${query}`, { headers }), request(`/api/member/redemptions?${query}`, { headers })]); const [pointBody, rewardBody, historyBody] = await Promise.all([pointResponse.json(), rewardResponse.json(), historyResponse.json()]); if (!pointResponse.ok || !rewardResponse.ok || !historyResponse.ok || !pointBody?.success || !rewardBody?.success || !historyBody?.success) throw new Error(); setState({ loading: false, points: pointBody, rewards: rewardBody.rewards || [], history: historyBody.redemptions || [], error: '', busy: '' }); } catch { setState(value => ({ ...value, loading: false, error: '目前無法讀取 Points / Rewards。', busy: '' })); } }, [auth, request]);
  useEffect(() => { load(); }, [load]);
  const redeem = async reward => { setState(value => ({ ...value, busy: reward.rewardHandle, error: '' })); try { const response = await request('/api/member/redemptions', { method: 'POST', headers: { Authorization: `Bearer ${auth.accessToken}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ lineAccountId: auth.lineAccountId, liffAccessToken: auth.accessToken, rewardHandle: reward.rewardHandle }) }); const body = await response.json(); if (!response.ok || !body?.success) throw new Error(body?.error || 'REDEEM_FAILED'); await load(); } catch (error) { setState(value => ({ ...value, busy: '', error: error?.message === 'INSUFFICIENT_POINTS' ? 'Points 不足，尚未建立兌換紀錄。' : '兌換未完成，請稍後再試。' })); } };
  return <section className="mt-5 rounded-xl border border-slate-200 p-4" aria-label="我的 Points 與獎勵"><h2 className="text-lg font-bold">我的 Points 與獎勵</h2>{state.loading && <p className="mt-3 text-sm text-slate-500">讀取中…</p>}{state.error && <p className="mt-3 rounded bg-amber-50 p-3 text-sm text-amber-900">{state.error}</p>}{!state.loading && state.points && <><div className="mt-3 grid grid-cols-3 gap-2 text-center"><div className="rounded bg-slate-50 p-3"><div className="text-xs text-slate-500">目前 Points</div><b>{points(state.points.balance)}</b></div><div className="rounded bg-slate-50 p-3"><div className="text-xs text-slate-500">已獲得</div><b>{points(state.points.creditedPoints)}</b></div><div className="rounded bg-slate-50 p-3"><div className="text-xs text-slate-500">已兌換</div><b>{points(state.points.debitedPoints)}</b></div></div><div className="mt-5"><h3 className="font-bold">可兌換獎勵</h3>{state.rewards.length === 0 ? <p className="mt-2 rounded bg-slate-50 p-3 text-sm text-slate-600">目前沒有可兌換獎勵。</p> : <div className="mt-2 space-y-2">{state.rewards.map(reward => <article key={reward.rewardHandle} className="rounded border border-slate-100 p-3"><b>{reward.name}</b><p className="mt-1 text-xs text-slate-500">{reward.description || '—'}</p><div className="mt-2 flex items-center justify-between gap-3"><span className="text-sm font-bold">{points(reward.pointsCost)} Points</span><button type="button" disabled={!reward.available || Boolean(state.busy)} onClick={() => redeem(reward)} className="rounded bg-slate-900 px-3 py-1 text-sm font-bold text-white">{state.busy === reward.rewardHandle ? '處理中…' : '兌換'}</button></div></article>)}</div>}</div><div className="mt-5"><h3 className="font-bold">我的兌換紀錄</h3>{state.history.length === 0 ? <p className="mt-2 text-sm text-slate-500">目前尚無兌換紀錄。</p> : <div className="mt-2 space-y-2">{state.history.map((row, index) => <div key={`${row.rewardName}-${row.redeemedAt}-${index}`} className="flex justify-between rounded border border-slate-100 p-3 text-sm"><span>{row.rewardName}<small className="block text-slate-500">{row.redeemedAt || '—'}</small></span><b>{points(row.pointsCost)} Points</b></div>)}</div>}</div></>}</section>;
}
