import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { formatCommissionMoney } from './CommissionLedgerPanel';

const T = {
  title: '\u7d50\u7b97\u8207\u4f63\u91d1\u7533\u8acb', refresh: '\u91cd\u65b0\u6574\u7406', loading: '\u8b80\u53d6\u8cc7\u6599\u4e2d\u2026', readOnly: '\u552f\u8b80', noValue: '\u2014',
  settlement: '\u7d50\u7b97\u6e05\u55ae', payout: '\u4f63\u91d1\u7533\u8acb\u5be9\u6838', detail: '\u7d50\u7b97\u660e\u7d30', lock: '\u9396\u5b9a', cancel: '\u53d6\u6d88', finalize: '\u5b8c\u6210\u7d50\u7b97', approve: '\u6838\u51c6', reject: '\u62d2\u7d55', execute: '\u57f7\u884c\u6a21\u64ec\u4ed8\u6b3e',
  noSettlement: '\u76ee\u524d\u6c92\u6709\u7d50\u7b97\u8cc7\u6599\u3002', noPayout: '\u76ee\u524d\u6c92\u6709\u4f63\u91d1\u7533\u8acb\u3002', snapshot: '\u5feb\u7167', rows: '\u7b46', requestedAt: '\u7533\u8acb\u65bc', rejectReason: '\u62d2\u7d55\u539f\u56e0',
  noRealMoney: '\u4e0d\u6703\u57f7\u884c\u771f\u5be6\u4ed8\u6b3e\u3001\u8f49\u5e33\u6216\u532f\u6b3e\u3002', managerOnly: '\u7d50\u7b97\u3001\u5be9\u6838\u8207\u6a21\u64ec\u4ed8\u6b3e\u7531 owner/admin \u57f7\u884c\u3002',
  readError: '\u76ee\u524d\u7121\u6cd5\u8b80\u53d6\u7d50\u7b97\u8207\u4f63\u91d1\u7533\u8acb\u8cc7\u6599\uff0c\u8acb\u7a0d\u5f8c\u518d\u8a66\u3002', noEligible: '\u76ee\u524d\u6c92\u6709\u53ef\u7d0d\u5165\u6b64\u671f\u9593\u7684\u4f63\u91d1\u9805\u76ee\uff0c\u7121\u6cd5\u9396\u5b9a\u7d50\u7b97\u3002', updateError: '\u7121\u6cd5\u66f4\u65b0\u72c0\u614b\u3002', executionError: '\u6a21\u64ec\u4ed8\u6b3e\u7121\u6cd5\u5b8c\u6210\u3002',
};
const SETTLEMENT_LABELS = { DRAFT: '\u8349\u7a3f', LOCKED: '\u5df2\u9396\u5b9a', FINALIZED: '\u5df2\u5b8c\u6210\u7d50\u7b97', CANCELLED: '\u5df2\u53d6\u6d88' };
const PAYOUT_LABELS = { REQUESTED: '\u5f85\u5be9\u6838', APPROVED: '\u5df2\u6838\u51c6', REJECTED: '\u5df2\u62d2\u7d55', CANCELLED: '\u5df2\u53d6\u6d88' };
const ATTEMPT_LABELS = { PENDING: '\u7b49\u5f85\u8655\u7406', PROCESSING: '\u8655\u7406\u4e2d', SUCCEEDED: '\u6a21\u64ec\u4ed8\u6b3e\u5df2\u6210\u529f', FAILED: '\u6a21\u64ec\u4ed8\u6b3e\u5931\u6557', CANCELLED: '\u5df2\u53d6\u6d88' };
const FAILURE_LABELS = { PROVIDER_UNAVAILABLE: '\u6a21\u64ec\u670d\u52d9\u66ab\u6642\u7121\u6cd5\u4f7f\u7528', PROVIDER_REJECTED: '\u6a21\u64ec\u670d\u52d9\u62d2\u7d55\u57f7\u884c', INVALID_PAYMENT_STATE: '\u4ed8\u6b3e\u72c0\u614b\u4e0d\u5141\u8a31\u57f7\u884c', IDEMPOTENCY_CONFLICT: '\u91cd\u8907\u57f7\u884c\u8acb\u6c42', TECHNICAL_FAILURE: '\u6a21\u64ec\u8655\u7406\u767c\u751f\u6280\u8853\u554f\u984c' };
const REJECTION_REASONS = [['INVALID_REQUEST', '\u7533\u8acb\u8cc7\u6599\u4e0d\u7b26'], ['SETTLEMENT_MISMATCH', '\u7d50\u7b97\u8cc7\u6599\u4e0d\u7b26'], ['DEALER_NOT_ELIGIBLE', '\u8cc7\u683c\u4e0d\u7b26'], ['DUPLICATE_REQUEST', '\u91cd\u8907\u7533\u8acb'], ['OTHER_POLICY', '\u5176\u4ed6\u653f\u7b56\u539f\u56e0']];
const formatDate = value => value ? new Intl.DateTimeFormat('zh-TW', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : T.noValue;
const isManager = role => role === 'owner' || role === 'admin';

export default function TenantSettlementPayoutPanel({ request, userRole }) {
  const [state, setState] = useState({ loading: true, error: '', accountId: '', settlements: [], payouts: [], attempts: [] });
  const [selected, setSelected] = useState(null); const [detail, setDetail] = useState(null); const [busy, setBusy] = useState(''); const [reason, setReason] = useState('INVALID_REQUEST');
  const manage = isManager(userRole);
  const load = useCallback(async () => {
    setState(old => ({ ...old, loading: true, error: '' }));
    try {
      const accountResponse = await request('/api/line/account'); const account = await accountResponse.json();
      if (!accountResponse.ok || !account?.success || !account.account?.id) throw new Error('LINE_ACCOUNT_REQUIRED');
      const accountId = account.account.id, query = `lineAccountId=${encodeURIComponent(accountId)}`;
      const responses = await Promise.all([request(`/api/commission-settlements?${query}`), request(`/api/commission-payout-requests?${query}`), request(`/api/commission-payment-attempts?${query}`)]);
      const [settlements, payouts, attempts] = await Promise.all(responses.map(response => response.json()));
      if (responses.some(response => !response.ok) || !settlements?.success || !payouts?.success || !attempts?.success) throw new Error('READ_FAILED');
      setState({ loading: false, error: '', accountId, settlements: settlements.settlements || [], payouts: payouts.requests || [], attempts: attempts.attempts || [] });
    } catch { setState(old => ({ ...old, loading: false, error: T.readError })); }
  }, [request]);
  useEffect(() => { load(); }, [load]);
  const detailFor = async settlement => { setSelected(settlement); setDetail(null); try { const response = await request(`/api/commission-settlements/${encodeURIComponent(settlement.settlementId)}?lineAccountId=${encodeURIComponent(state.accountId)}`); const body = await response.json(); if (response.ok && body?.success) setDetail(body); } catch { setDetail(null); } };
  const updateSettlement = async (settlement, status) => { if (!manage) return; setBusy(settlement.settlementId); try { const response = await request(`/api/commission-settlements/${encodeURIComponent(settlement.settlementId)}/status?lineAccountId=${encodeURIComponent(state.accountId)}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); const body = await response.json(); if (!response.ok || !body?.success) throw new Error(body?.error); await load(); } catch (error) { setState(old => ({ ...old, error: error?.message === 'NO_ELIGIBLE_LEDGER_ENTRIES' ? T.noEligible : T.updateError })); } finally { setBusy(''); } };
  const updatePayout = async (payout, status) => { if (!manage) return; setBusy(payout.requestId); try { const payload = status === 'REJECTED' ? { status, reasonCode: reason } : { status }; const response = await request(`/api/commission-payout-requests/${encodeURIComponent(payout.requestId)}/status?lineAccountId=${encodeURIComponent(state.accountId)}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok || !body?.success) throw new Error('UPDATE_FAILED'); await load(); } catch { setState(old => ({ ...old, error: T.updateError })); } finally { setBusy(''); } };
  const execute = async payout => { if (!manage) return; setBusy(payout.requestId); try { const idempotencyKey = globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`; const response = await request(`/api/commission-payout-requests/${encodeURIComponent(payout.requestId)}/execute?lineAccountId=${encodeURIComponent(state.accountId)}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ idempotencyKey }) }); const body = await response.json(); if (!response.ok || !body?.success) throw new Error('EXECUTION_FAILED'); await load(); } catch { setState(old => ({ ...old, error: T.executionError })); } finally { setBusy(''); } };
  const attemptsByPayout = useMemo(() => state.attempts.reduce((map, row) => ({ ...map, [row.payoutRequestId]: [...(map[row.payoutRequestId] || []), row] }), {}), [state.attempts]);
  const actions = row => !manage ? null : row.status === 'DRAFT' ? <span className="flex gap-2"><button type="button" disabled={Boolean(busy)} onClick={() => updateSettlement(row, 'LOCKED')} className="rounded bg-slate-900 px-3 py-1 text-xs text-white">{T.lock}</button><button type="button" disabled={Boolean(busy)} onClick={() => updateSettlement(row, 'CANCELLED')} className="rounded border px-3 py-1 text-xs">{T.cancel}</button></span> : row.status === 'LOCKED' ? <span className="flex gap-2"><button type="button" disabled={Boolean(busy)} onClick={() => updateSettlement(row, 'FINALIZED')} className="rounded bg-slate-900 px-3 py-1 text-xs text-white">{T.finalize}</button><button type="button" disabled={Boolean(busy)} onClick={() => updateSettlement(row, 'CANCELLED')} className="rounded border px-3 py-1 text-xs">{T.cancel}</button></span> : <span className="text-xs text-gray-500">{T.readOnly}</span>;
  return <section className="mt-5 rounded-xl border border-gray-200 bg-white p-5 shadow-sm" aria-label={T.title}>
    <div className="flex justify-between gap-3"><div><h2 className="text-lg font-bold">{T.title}</h2><p className="mt-1 text-xs text-gray-500">minor-unit / currencyCode</p></div><button type="button" onClick={load} className="rounded border px-3 py-1 text-sm">{T.refresh}</button></div>
    {!manage && <p className="mt-3 rounded bg-slate-50 p-3 text-xs">{T.managerOnly}</p>}{state.loading && <p className="py-5 text-sm text-gray-500">{T.loading}</p>}{state.error && <p className="mt-3 rounded bg-red-50 p-3 text-sm text-red-700">{state.error}</p>}
    {!state.loading && <><section className="mt-5"><h3 className="font-bold">{T.settlement}</h3>{state.settlements.length === 0 ? <p className="mt-2 rounded bg-gray-50 p-3 text-sm">{T.noSettlement}</p> : state.settlements.map(row => <article key={row.settlementId} className="mt-2 rounded border p-3"><div className="flex justify-between gap-3"><button type="button" onClick={() => detailFor(row)} className="text-left"><b>{row.periodStart} - {row.periodEnd}</b><div className="text-xs text-gray-500">{SETTLEMENT_LABELS[row.status] || row.status} - {row.entryCount} {T.rows} - {T.snapshot} {formatDate(row.snapshotAt)}</div></button><div className="text-right"><b>{formatCommissionMoney(row.totalAmountMinor, row.currencyCode)}</b><div className="mt-2">{actions(row)}</div></div></div></article>)}</section>
    {selected && <section className="mt-3 rounded bg-slate-50 p-3 text-sm"><b>{T.detail}: {selected.periodStart} - {selected.periodEnd}</b>{detail && <><p>{formatCommissionMoney(detail.settlement?.totalAmountMinor, detail.settlement?.currencyCode)} - {detail.settlement?.entryCount} {T.rows}</p>{(detail.items || []).map((item, index) => <div key={`${item.publicSafeLabel}-${index}`} className="flex justify-between text-xs"><span>{item.publicSafeLabel} - {item.programName}</span><b>{formatCommissionMoney(item.amountMinor, item.currencyCode)}</b></div>)}</>}</section>}
    <section className="mt-6"><div className="flex justify-between gap-3"><h3 className="font-bold">{T.payout}</h3>{manage && <label className="text-xs">{T.rejectReason} <select value={reason} onChange={event => setReason(event.target.value)}>{REJECTION_REASONS.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>}</div>{state.payouts.length === 0 ? <p className="mt-2 rounded bg-gray-50 p-3 text-sm">{T.noPayout}</p> : state.payouts.map(row => <article key={row.requestId} className="mt-2 rounded border p-3"><div className="flex justify-between gap-3"><div><b>{row.publicSafeLabel}</b><div className="text-xs text-gray-500">{PAYOUT_LABELS[row.status] || row.status} - {T.requestedAt} {formatDate(row.requestedAt)}</div></div><div className="text-right"><b>{formatCommissionMoney(row.amountMinor, row.currencyCode)}</b><div className="mt-2 flex gap-2">{manage && row.status === 'REQUESTED' && <><button type="button" disabled={Boolean(busy)} onClick={() => updatePayout(row, 'APPROVED')} className="rounded bg-slate-900 px-3 py-1 text-xs text-white">{T.approve}</button><button type="button" disabled={Boolean(busy)} onClick={() => updatePayout(row, 'REJECTED')} className="rounded border px-3 py-1 text-xs">{T.reject}</button></>}{manage && row.status === 'APPROVED' && <button type="button" disabled={Boolean(busy)} onClick={() => execute(row)} className="rounded bg-indigo-700 px-3 py-1 text-xs text-white">{T.execute}</button>}</div></div></div><div className="mt-3 rounded bg-slate-50 p-2 text-xs"><b>SIMULATED - INTERNAL_TEST</b> {T.noRealMoney}</div>{(attemptsByPayout[row.requestId] || []).map(attempt => <div key={attempt.attemptId} className="mt-2 flex justify-between border-t pt-2 text-xs"><span>{attempt.attemptNo} - {ATTEMPT_LABELS[attempt.status] || attempt.status}</span><span>{formatCommissionMoney(attempt.amountMinor, attempt.currencyCode)} - {formatDate(attempt.completedAt || attempt.startedAt)}{attempt.failureReasonCode ? ` - ${FAILURE_LABELS[attempt.failureReasonCode] || T.failed}` : ''}</span></div>)}</article>)}</section></>}
  </section>;
}
