const n=(v:any)=>Number(v?.count||0); const rows=async(db:D1Database,sql:string,args:any[])=>((await db.prepare(sql).bind(...args).all<any>()).results||[]);
const buckets=(list:any[],key:string,label:string)=>list.map(x=>({[key]:String(x[label]||''),count:Number(x.count||0)}));
export function analyticsPeriod(raw:any){return raw==='7d'?7:30;}
/** Acquisition distribution uses one latest event per Person; occurred_at then id decides ties. */
export async function crmAnalyticsSummary(db:D1Database,workspaceId:string,days:number,now=new Date().toISOString()){
 const since=new Date(Date.parse(now)-days*86400000).toISOString();const one=async(sql:string,args:any[]=[])=>await db.prepare(sql).bind(workspaceId,...args).first<any>();
 const [total,newPeople,line,referrer,open,overdue,stage,acquisition,tags,owners,activity]=await Promise.all([
  one('SELECT COUNT(*) count FROM crm_people WHERE workspace_id=?'),one('SELECT COUNT(*) count FROM crm_people WHERE workspace_id=? AND created_at>=?',[since]),one("SELECT COUNT(DISTINCT crm_person_id) count FROM crm_person_identity_links WHERE workspace_id=? AND identity_type='LINE_MEMBER' AND verification_status='VERIFIED'"),one("SELECT COUNT(DISTINCT l.crm_person_id) count FROM crm_person_identity_links l JOIN member_referral_attributions a ON a.workspace_id=l.workspace_id AND a.line_account_id=l.line_account_id AND a.invitee_member_id=l.line_member_id WHERE l.workspace_id=? AND l.identity_type='LINE_MEMBER'"),one("SELECT COUNT(*) count FROM crm_follow_up_tasks WHERE workspace_id=? AND status='OPEN'"),one("SELECT COUNT(*) count FROM crm_follow_up_tasks WHERE workspace_id=? AND status='OPEN' AND due_at<?",[now]),
  rows(db,"SELECT s.name label,COUNT(*) count FROM crm_person_stage_assignments a JOIN crm_pipeline_stages s ON s.id=a.crm_pipeline_stage_id WHERE a.workspace_id=? GROUP BY s.id,s.name ORDER BY count DESC,s.name ASC",[workspaceId]),rows(db,"SELECT source_type label,COUNT(*) count FROM (SELECT a.*,ROW_NUMBER() OVER(PARTITION BY a.crm_person_id ORDER BY a.occurred_at DESC,a.id DESC) rn FROM crm_acquisition_events a WHERE a.workspace_id=?) WHERE rn=1 GROUP BY source_type ORDER BY count DESC,source_type ASC",[workspaceId]),rows(db,"SELECT t.name label,COUNT(DISTINCT pt.crm_person_id) count FROM crm_person_tags pt JOIN crm_tags t ON t.id=pt.crm_tag_id WHERE pt.workspace_id=? AND pt.removed_at IS NULL GROUP BY t.id,t.name ORDER BY count DESC,t.name ASC",[workspaceId]),rows(db,"SELECT COALESCE(u.display_name,'Workspace user') label,COUNT(DISTINCT r.crm_person_id) count FROM crm_person_relationships r LEFT JOIN users u ON u.id=r.related_user_id WHERE r.workspace_id=? AND r.relationship_type='ASSIGNED_TO' AND r.status='ACTIVE' GROUP BY r.related_user_id,u.display_name ORDER BY count DESC,label ASC",[workspaceId]),one('SELECT COUNT(*) count FROM crm_profile_field_events WHERE workspace_id=? AND created_at>=?',[since])]);
 const totalPeople=n(total),withLine=n(line),withReferrer=n(referrer);return {period:`${days}d`,totalPeople,newPeopleInPeriod:n(newPeople),peopleWithLineIdentity:withLine,peopleWithoutLineIdentity:Math.max(0,totalPeople-withLine),peopleWithReferrer:withReferrer,peopleWithoutReferrer:Math.max(0,totalPeople-withReferrer),openFollowUpCount:n(open),overdueFollowUpCount:n(overdue),peopleByStage:buckets(stage,'stageLabel','label'),peopleByAcquisitionSource:buckets(acquisition,'sourceType','label'),peopleByTag:buckets(tags,'tagLabel','label'),peopleByAssignedOwner:buckets(owners,'ownerLabel','label'),recentActivityCount:n(activity)};
}
