import { assignPersonTag, createCrmTag, deriveZodiacTrait, listCrmTags, listPersonInsights, listPersonTags, listPersonTraits, removePersonTag, setCrmTagStatus } from './insights';

export function registerCrmInsightRoutes(app: any, deps: any) {
  const person = async (c: any) => { const workspaceId = deps.workspaceIdOf(c), row = await deps.crmPersonByReference(c.env.smart_menu_db, { workspaceId, publicRef: deps.text(c.req.param('safePersonReference'), 80) }); if (!row) throw new Error('CRM_PERSON_NOT_FOUND'); return { workspaceId, person: row }; };
  const fail = (c: any, error: any, fallback: string) => { const result = deps.crmRouteError(error, fallback); return c.json({ success: false, error: result.error }, result.status); };
  app.get('/api/crm/tags', async (c: any) => { try { deps.requireRole(c, 'viewer'); return c.json({ success: true, tags: await listCrmTags(c.env.smart_menu_db, deps.workspaceIdOf(c)) }); } catch (error) { return fail(c, error, 'CRM_TAG_LIST_FAILED'); } });
  app.post('/api/crm/tags', async (c: any) => { try { deps.requireRole(c, 'admin'); const body: any = await c.req.json().catch(() => ({})); return c.json({ success: true, tag: await createCrmTag(c.env.smart_menu_db, { workspaceId: deps.workspaceIdOf(c), name: body.name, description: body.description, createdByUserId: deps.text(c.get('userId')) || null }) }, 201); } catch (error) { return fail(c, error, 'CRM_TAG_CREATE_FAILED'); } });
  app.post('/api/crm/tags/:safeTagReference/status', async (c: any) => { try { deps.requireRole(c, 'admin'); const body: any = await c.req.json().catch(() => ({})); return c.json({ success: true, tag: await setCrmTagStatus(c.env.smart_menu_db, { workspaceId: deps.workspaceIdOf(c), tagReference: deps.text(c.req.param('safeTagReference'), 80), status: body.status }) }); } catch (error) { return fail(c, error, 'CRM_TAG_STATUS_UPDATE_FAILED'); } });
  app.get('/api/crm/people/:safePersonReference/tags', async (c: any) => { try { deps.requireRole(c, 'viewer'); const x = await person(c); return c.json({ success: true, tags: await listPersonTags(c.env.smart_menu_db, x.workspaceId, x.person.id) }); } catch (error) { return fail(c, error, 'CRM_PERSON_TAG_LIST_FAILED'); } });
  app.post('/api/crm/people/:safePersonReference/tags', async (c: any) => { try { deps.requireRole(c, 'editor'); const x = await person(c), body: any = await c.req.json().catch(() => ({})), tagReference = deps.text(body.safeTagReference, 80); if (!tagReference) return c.json({ success: false, error: 'CRM_TAG_REFERENCE_REQUIRED' }, 400); return c.json({ success: true, result: await assignPersonTag(c.env.smart_menu_db, { workspaceId: x.workspaceId, personId: x.person.id, tagReference, assignedByUserId: deps.text(c.get('userId')) || null }) }); } catch (error) { return fail(c, error, 'CRM_PERSON_TAG_ASSIGN_FAILED'); } });
  app.post('/api/crm/people/:safePersonReference/tags/:safeTagReference/remove', async (c: any) => { try { deps.requireRole(c, 'editor'); const x = await person(c); return c.json({ success: true, result: await removePersonTag(c.env.smart_menu_db, { workspaceId: x.workspaceId, personId: x.person.id, tagReference: deps.text(c.req.param('safeTagReference'), 80) }) }); } catch (error) { return fail(c, error, 'CRM_PERSON_TAG_REMOVE_FAILED'); } });
  app.get('/api/crm/people/:safePersonReference/insights', async (c: any) => { try { deps.requireRole(c, 'viewer'); const x = await person(c); return c.json({ success: true, insights: await listPersonInsights(c.env.smart_menu_db, x.workspaceId, x.person.id) }); } catch (error) { return fail(c, error, 'CRM_INSIGHT_LIST_FAILED'); } });
  app.get('/api/crm/people/:safePersonReference/traits', async (c: any) => { try { deps.requireRole(c, 'viewer'); const x = await person(c); return c.json({ success: true, traits: await listPersonTraits(c.env.smart_menu_db, x.workspaceId, x.person.id) }); } catch (error) { return fail(c, error, 'CRM_TRAIT_LIST_FAILED'); } });
  app.post('/api/crm/people/:safePersonReference/traits/derive', async (c: any) => { try { deps.requireRole(c, 'editor'); const x = await person(c); return c.json({ success: true, trait: await deriveZodiacTrait(c.env.smart_menu_db, { workspaceId: x.workspaceId, personId: x.person.id }) }); } catch (error) { return fail(c, error, 'CRM_TRAIT_DERIVE_FAILED'); } });
  app.get('/api/member/crm-traits', async (c: any) => { try { const verified = await deps.verifiedReferralMember(c, { lineAccountId: deps.text(c.req.query('lineAccountId')), liffAccessToken: deps.text(c.req.header('Authorization')).replace(/^Bearer\s+/i, '') }); const own = await deps.ensureCrmPersonForVerifiedMember(c.env.smart_menu_db, { workspaceId: verified.account.workspace_id, lineAccountId: verified.account.id, lineMemberId: verified.memberId }); const traits = await listPersonTraits(c.env.smart_menu_db, verified.account.workspace_id, own.id, true); return c.json({ success: true, traits: traits.filter((trait: any) => trait.traitType === 'ZODIAC') }); } catch { return c.json({ success: false, error: 'MEMBER_CONTEXT_REQUIRED' }, 401); } });
}
