const id=(p:string)=>`${p}_${crypto.randomUUID()}`;
const clean=(value:any,max=200)=>typeof value==='string'?value.trim().slice(0,max):'';
const stageRef=()=>`crmst_${crypto.randomUUID().replace(/-/g,'')}`;
const taskRef=()=>`crmft_${crypto.randomUUID().replace(/-/g,'')}`;
const CATEGORIES=new Set(['OPEN','WON','LOST']), STAGE_STATUSES=new Set(['ACTIVE','ARCHIVED']), PRIORITIES=new Set(['LOW','NORMAL','HIGH']), TASK_STATUSES=new Set(['COMPLETED','CANCELLED']);
function stageProjection(row:any){return {stageReference:clean(row.public_ref,100),stageKey:clean(row.stage_key,64),name:clean(row.name,120),description:clean(row.description,1000)||null,sortOrder:Number(row.sort_order||0),stageCategory:clean(row.stage_category,20),status:clean(row.status,20),createdAt:row.created_at||null,updatedAt:row.updated_at||null};}
function taskProjection(row:any,includeNote:boolean){return {safeTaskReference:clean(row.public_ref,100),title:clean(row.title,240),...(includeNote?{note:clean(row.note,4000)||null}:{}),dueAt:row.due_at||null,priority:clean(row.priority,20),status:clean(row.status,20),assignedOwnerLabel:clean(row.display_name,120)||'Workspace user',createdAt:row.created_at||null,completedAt:row.completed_at||null};}
function timestamp(value:any){const text=clean(value,64);if(!text)return null;if(Number.isNaN(Date.parse(text)))throw new Error('CRM_FOLLOW_UP_DUE_AT_INVALID');return text;}

export async function listPipelineStages(db:D1Database,workspaceId:string){const rows:any[]=(await db.prepare('SELECT * FROM crm_pipeline_stages WHERE workspace_id=? ORDER BY sort_order ASC,name ASC,id ASC').bind(workspaceId).all()).results||[];return rows.map(stageProjection);}
export async function createPipelineStage(db:D1Database,input:{workspaceId:string;stageKey:any;name:any;description?:any;sortOrder?:any;stageCategory?:any;createdByUserId?:string|null}){const key=clean(input.stageKey,64).toUpperCase(),name=clean(input.name,120),category=clean(input.stageCategory||'OPEN',20).toUpperCase();if(!/^[A-Z][A-Z0-9_]{0,63}$/.test(key))throw new Error('CRM_PIPELINE_STAGE_KEY_INVALID');if(!name)throw new Error('CRM_PIPELINE_STAGE_NAME_REQUIRED');if(!CATEGORIES.has(category))throw new Error('CRM_PIPELINE_STAGE_CATEGORY_INVALID');const existing:any=await db.prepare('SELECT id FROM crm_pipeline_stages WHERE workspace_id=? AND stage_key=? LIMIT 1').bind(input.workspaceId,key).first();if(existing)throw new Error('CRM_PIPELINE_STAGE_KEY_EXISTS');const row={id:id('crmps'),ref:stageRef(),sort:Number.isInteger(input.sortOrder)?input.sortOrder:0};await db.prepare('INSERT INTO crm_pipeline_stages(id,public_ref,workspace_id,stage_key,name,description,sort_order,stage_category,created_by_user_id) VALUES(?,?,?,?,?,?,?,?,?)').bind(row.id,row.ref,input.workspaceId,key,name,clean(input.description,1000)||null,row.sort,category,input.createdByUserId||null).run();const result:any=await db.prepare('SELECT * FROM crm_pipeline_stages WHERE id=?').bind(row.id).first();return stageProjection(result);}
async function stageByReference(db:D1Database,workspaceId:string,reference:string){const row:any=await db.prepare('SELECT * FROM crm_pipeline_stages WHERE workspace_id=? AND public_ref=? LIMIT 1').bind(workspaceId,reference).first();if(!row)throw new Error('CRM_PIPELINE_STAGE_NOT_FOUND');return row;}
export async function setPipelineStageStatus(db:D1Database,input:{workspaceId:string;stageReference:string;status:any}){const status=clean(input.status,20).toUpperCase();if(!STAGE_STATUSES.has(status))throw new Error('CRM_PIPELINE_STAGE_STATUS_INVALID');const stage=await stageByReference(db,input.workspaceId,input.stageReference);await db.prepare('UPDATE crm_pipeline_stages SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND workspace_id=?').bind(status,stage.id,input.workspaceId).run();return stageProjection({...stage,status,updated_at:new Date().toISOString()});}
export async function personStage(db:D1Database,workspaceId:string,personId:string){const row:any=await db.prepare('SELECT s.* FROM crm_person_stage_assignments a JOIN crm_pipeline_stages s ON s.id=a.crm_pipeline_stage_id WHERE a.workspace_id=? AND a.crm_person_id=? LIMIT 1').bind(workspaceId,personId).first();return row?stageProjection(row):null;}
export async function assignPersonStage(db:D1Database,input:{workspaceId:string;personId:string;stageReference:string;actorUserId?:string|null;reason?:any}){const stage=await stageByReference(db,input.workspaceId,input.stageReference);if(stage.status!=='ACTIVE')throw new Error('CRM_PIPELINE_STAGE_ARCHIVED');const current:any=await db.prepare('SELECT id,crm_pipeline_stage_id FROM crm_person_stage_assignments WHERE workspace_id=? AND crm_person_id=? LIMIT 1').bind(input.workspaceId,input.personId).first();if(current?.crm_pipeline_stage_id===stage.id)return {idempotent:true,currentStage:stageProjection(stage)};const now=new Date().toISOString(),ops=[] as any[];if(current)ops.push(db.prepare('UPDATE crm_person_stage_assignments SET crm_pipeline_stage_id=?,assigned_by_user_id=?,assigned_at=? WHERE id=? AND workspace_id=?').bind(stage.id,input.actorUserId||null,now,current.id,input.workspaceId));else ops.push(db.prepare('INSERT INTO crm_person_stage_assignments(id,workspace_id,crm_person_id,crm_pipeline_stage_id,assigned_by_user_id,assigned_at) VALUES(?,?,?,?,?,?)').bind(id('crmpsa'),input.workspaceId,input.personId,stage.id,input.actorUserId||null,now));ops.push(db.prepare('INSERT INTO crm_person_stage_events(id,workspace_id,crm_person_id,from_stage_id,to_stage_id,actor_user_id,reason,occurred_at) VALUES(?,?,?,?,?,?,?,?)').bind(id('crmpse'),input.workspaceId,input.personId,current?.crm_pipeline_stage_id||null,stage.id,input.actorUserId||null,clean(input.reason,1000)||null,now));await db.batch(ops);return {changed:true,currentStage:stageProjection(stage)};}
export async function listFollowUps(db:D1Database,workspaceId:string,personId:string,includeNote:boolean){const rows:any[]=(await db.prepare('SELECT t.*,u.display_name FROM crm_follow_up_tasks t LEFT JOIN users u ON u.id=t.assigned_user_id WHERE t.workspace_id=? AND t.crm_person_id=? ORDER BY CASE t.status WHEN \'OPEN\' THEN 0 ELSE 1 END,t.due_at ASC,t.created_at DESC').bind(workspaceId,personId).all()).results||[];return rows.map(row=>taskProjection(row,includeNote));}
export async function createFollowUp(db:D1Database,input:{workspaceId:string;personId:string;assignedUserId:string;title:any;note?:any;dueAt?:any;priority?:any;actorUserId?:string|null}){const title=clean(input.title,240),priority=clean(input.priority||'NORMAL',20).toUpperCase();if(!title)throw new Error('CRM_FOLLOW_UP_TITLE_REQUIRED');if(!PRIORITIES.has(priority))throw new Error('CRM_FOLLOW_UP_PRIORITY_INVALID');const user:any=await db.prepare('SELECT id FROM users WHERE id=? AND workspace_id=? AND (status IS NULL OR status IN (\'active\',\'ACTIVE\')) LIMIT 1').bind(input.assignedUserId,input.workspaceId).first();if(!user)throw new Error('CRM_ASSIGNEE_NOT_ELIGIBLE');const task={id:id('crmfut'),ref:taskRef(),dueAt:timestamp(input.dueAt),note:clean(input.note,4000)||null};await db.batch([db.prepare('INSERT INTO crm_follow_up_tasks(id,public_ref,workspace_id,crm_person_id,assigned_user_id,title,note,due_at,priority,created_by_user_id) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(task.id,task.ref,input.workspaceId,input.personId,input.assignedUserId,title,task.note,task.dueAt,priority,input.actorUserId||null),db.prepare('INSERT INTO crm_follow_up_task_events(id,workspace_id,crm_follow_up_task_id,event_type,actor_user_id,note) VALUES(?,?,?,?,?,?)').bind(id('crmfte'),input.workspaceId,task.id,'CREATED',input.actorUserId||null,task.note)]);const row:any=await db.prepare('SELECT t.*,u.display_name FROM crm_follow_up_tasks t LEFT JOIN users u ON u.id=t.assigned_user_id WHERE t.id=?').bind(task.id).first();return taskProjection(row,true);}
export async function setFollowUpStatus(db:D1Database,input:{workspaceId:string;taskReference:string;status:any;outcome?:any;actorUserId?:string|null}){const status=clean(input.status,20).toUpperCase();if(!TASK_STATUSES.has(status))throw new Error('CRM_FOLLOW_UP_STATUS_INVALID');const task:any=await db.prepare('SELECT * FROM crm_follow_up_tasks WHERE workspace_id=? AND public_ref=? LIMIT 1').bind(input.workspaceId,input.taskReference).first();if(!task)throw new Error('CRM_FOLLOW_UP_NOT_FOUND');if(task.status!== 'OPEN')return {idempotent:true,status:task.status};const now=new Date().toISOString();await db.batch([db.prepare('UPDATE crm_follow_up_tasks SET status=?,completed_at=?,updated_at=? WHERE id=? AND workspace_id=? AND status=\'OPEN\'').bind(status,status==='COMPLETED'?now:null,now,task.id,input.workspaceId),db.prepare('INSERT INTO crm_follow_up_task_events(id,workspace_id,crm_follow_up_task_id,event_type,actor_user_id,outcome,occurred_at) SELECT ?,?,?,?,?,?,? WHERE changes()=1').bind(id('crmfte'),input.workspaceId,task.id,status==='COMPLETED'?'COMPLETED':'CANCELLED',input.actorUserId||null,clean(input.outcome,2000)||null,now)]);return {status,completedAt:status==='COMPLETED'?now:null};}
export async function pipelineSummary(db:D1Database,workspaceId:string){const rows:any[]=(await db.prepare('SELECT s.*,COUNT(a.crm_person_id) person_count FROM crm_pipeline_stages s LEFT JOIN crm_person_stage_assignments a ON a.workspace_id=s.workspace_id AND a.crm_pipeline_stage_id=s.id WHERE s.workspace_id=? AND s.status=\'ACTIVE\' GROUP BY s.id ORDER BY s.sort_order ASC,s.name ASC').bind(workspaceId).all()).results||[];return rows.map(row=>({stageReference:clean(row.public_ref,100),stageName:clean(row.name,120),stageCategory:clean(row.stage_category,20),personCount:Number(row.person_count||0)}));}
export async function businessProcessSummary(db:D1Database,workspaceId:string,personId:string){const [currentStage,tasks]:any=await Promise.all([personStage(db,workspaceId,personId),db.prepare("SELECT COUNT(*) open_count,SUM(CASE WHEN due_at IS NOT NULL AND due_at<CURRENT_TIMESTAMP THEN 1 ELSE 0 END) overdue_count,MIN(due_at) next_at FROM crm_follow_up_tasks WHERE workspace_id=? AND crm_person_id=? AND status='OPEN'").bind(workspaceId,personId).first()]);return {currentStage,openFollowUpCount:Number(tasks?.open_count||0),overdueFollowUpCount:Number(tasks?.overdue_count||0),nextFollowUpAt:tasks?.next_at||null};}
