import { assigneeReference, verifyAssigneeHandle } from './assignee-handle';
import { assignPersonStage, businessProcessSummary, createFollowUp, createPipelineStage, listFollowUps, listPipelineStages, personStage, pipelineSummary, setFollowUpStatus, setPipelineStageStatus } from './pipeline';

export function registerCrmPipelineRoutes(app:any,deps:any){
  const fail=(c:any,error:any,fallback:string)=>{const code=String(error?.message||'');if(code==='FORBIDDEN_ROLE')return c.json({success:false,error:'FORBIDDEN'},403);if(['CRM_PERSON_NOT_FOUND','CRM_PIPELINE_STAGE_NOT_FOUND','CRM_FOLLOW_UP_NOT_FOUND'].includes(code))return c.json({success:false,error:'NOT_FOUND'},404);if(code.startsWith('CRM_'))return c.json({success:false,error:code},400);return c.json({success:false,error:fallback},500);};
  const person=async(c:any)=>{const workspaceId=deps.workspaceIdOf(c),row:any=await deps.crmPersonByReference(c.env.smart_menu_db,{workspaceId,publicRef:deps.text(c.req.param('safePersonReference'),80)});if(!row)throw new Error('CRM_PERSON_NOT_FOUND');return {workspaceId,person:row};};
  const resolveAssignee=async(c:any,workspaceId:string,reference:any)=>{const token=deps.text(reference,4096);if(!token)throw new Error('CRM_ASSIGNEE_REFERENCE_REQUIRED');const secret=deps.text(c.env.CRM_ASSIGNEE_HANDLE_SECRET);const verified=await verifyAssigneeHandle(secret,token);const users:any[]=await deps.crmAssignableUsers(c.env.smart_menu_db,workspaceId),matched=[] as any[];for(const user of users)if(await assigneeReference(secret,workspaceId,user.id)===verified.reference)matched.push(user);if(matched.length!==1)throw new Error('CRM_ASSIGNEE_NOT_ELIGIBLE');return matched[0];};
  app.get('/api/crm/pipeline-stages',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,stages:await listPipelineStages(c.env.smart_menu_db,deps.workspaceIdOf(c))});}catch(e){return fail(c,e,'CRM_PIPELINE_STAGE_LIST_FAILED')}});
  app.post('/api/crm/pipeline-stages',async(c:any)=>{try{deps.requireRole(c,'admin');const b:any=await c.req.json().catch(()=>({}));return c.json({success:true,stage:await createPipelineStage(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),stageKey:b.stageKey,name:b.name,description:b.description,sortOrder:b.sortOrder,stageCategory:b.stageCategory,createdByUserId:deps.text(c.get('userId'))||null})},201);}catch(e){return fail(c,e,'CRM_PIPELINE_STAGE_CREATE_FAILED')}});
  app.post('/api/crm/pipeline-stages/:safeStageReference/status',async(c:any)=>{try{deps.requireRole(c,'admin');const b:any=await c.req.json().catch(()=>({}));return c.json({success:true,stage:await setPipelineStageStatus(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),stageReference:deps.text(c.req.param('safeStageReference'),100),status:b.status})});}catch(e){return fail(c,e,'CRM_PIPELINE_STAGE_STATUS_FAILED')}});
  app.get('/api/crm/people/:safePersonReference/stage',async(c:any)=>{try{deps.requireRole(c,'viewer');const x=await person(c);return c.json({success:true,currentStage:await personStage(c.env.smart_menu_db,x.workspaceId,x.person.id)});}catch(e){return fail(c,e,'CRM_PERSON_STAGE_READ_FAILED')}});
  app.post('/api/crm/people/:safePersonReference/stage',async(c:any)=>{try{deps.requireRole(c,'editor');const x=await person(c),b:any=await c.req.json().catch(()=>({}));const safeStageReference=deps.text(b.safeStageReference,100);if(!safeStageReference)return c.json({success:false,error:'CRM_PIPELINE_STAGE_REFERENCE_REQUIRED'},400);return c.json({success:true,result:await assignPersonStage(c.env.smart_menu_db,{workspaceId:x.workspaceId,personId:x.person.id,stageReference:safeStageReference,actorUserId:deps.text(c.get('userId'))||null,reason:b.reason})});}catch(e){return fail(c,e,'CRM_PERSON_STAGE_ASSIGN_FAILED')}});
  app.get('/api/crm/people/:safePersonReference/follow-ups',async(c:any)=>{try{deps.requireRole(c,'viewer');const x=await person(c),includeNote=String(c.get('userRole')||'viewer').toLowerCase()!=='viewer';return c.json({success:true,followUps:await listFollowUps(c.env.smart_menu_db,x.workspaceId,x.person.id,includeNote)});}catch(e){return fail(c,e,'CRM_FOLLOW_UP_LIST_FAILED')}});
  app.post('/api/crm/people/:safePersonReference/follow-ups',async(c:any)=>{try{deps.requireRole(c,'editor');const x=await person(c),b:any=await c.req.json().catch(()=>({})),assignee=await resolveAssignee(c,x.workspaceId,b.assignedUserReference);return c.json({success:true,followUp:await createFollowUp(c.env.smart_menu_db,{workspaceId:x.workspaceId,personId:x.person.id,assignedUserId:assignee.id,title:b.title,note:b.note,dueAt:b.dueAt,priority:b.priority,actorUserId:deps.text(c.get('userId'))||null})},201);}catch(e){return fail(c,e,'CRM_FOLLOW_UP_CREATE_FAILED')}});
  app.post('/api/crm/follow-ups/:safeTaskReference/status',async(c:any)=>{try{deps.requireRole(c,'editor');const b:any=await c.req.json().catch(()=>({}));return c.json({success:true,result:await setFollowUpStatus(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),taskReference:deps.text(c.req.param('safeTaskReference'),100),status:b.status,outcome:b.outcome,actorUserId:deps.text(c.get('userId'))||null})});}catch(e){return fail(c,e,'CRM_FOLLOW_UP_STATUS_FAILED')}});
  app.get('/api/crm/pipeline-summary',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,stages:await pipelineSummary(c.env.smart_menu_db,deps.workspaceIdOf(c))});}catch(e){return fail(c,e,'CRM_PIPELINE_SUMMARY_FAILED')}});
  app.get('/api/crm/people/:safePersonReference/business-process',async(c:any)=>{try{deps.requireRole(c,'viewer');const x=await person(c),[process,owner]=await Promise.all([businessProcessSummary(c.env.smart_menu_db,x.workspaceId,x.person.id),deps.assignmentSummary(c.env.smart_menu_db,x.workspaceId,x.person.id)]);return c.json({success:true,businessProcess:{...process,assignedOwner:owner?{label:owner.label,assignedAt:owner.assignedAt}:null}});}catch(e){return fail(c,e,'CRM_BUSINESS_PROCESS_READ_FAILED')}});
}
