import { archiveSegment, createSegment, executeSegment, listSegments, segmentByReference, updateSegment, validateSegmentRule } from './segments';
import { analyticsPeriod, crmAnalyticsSummary } from './analytics';
import { assigneeReference, verifyAssigneeHandle } from './assignee-handle';

const fail=(c:any,e:any,code:string)=>c.json({success:false,error:e?.message==='FORBIDDEN_ROLE'?'FORBIDDEN':e?.message||code},e?.message==='FORBIDDEN_ROLE'?403:400);
const enc=new TextEncoder();
const copy=(v:any)=>JSON.parse(JSON.stringify(v));
async function sign(secret:string,parts:string[]){if(!secret)throw new Error('CRM_ASSIGNEE_HANDLE_SECRET_MISSING');const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const out=await crypto.subtle.sign('HMAC',key,enc.encode(parts.join('\u001f')));return [...new Uint8Array(out)].map(x=>x.toString(16).padStart(2,'0')).join('');}
const b64=(v:string)=>btoa(v).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const unb64=(v:string)=>atob(v.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(v.length/4)*4,'='));
async function cursor(secret:string,workspaceId:string,segmentRef:string,position:any){const raw=b64(JSON.stringify({v:1,t:position.updatedAt,r:await sign(secret,['crm-segment-cursor-person:v1',workspaceId,segmentRef,position.personId])}));return `${raw}.${await sign(secret,['crm-segment-cursor:v1',workspaceId,segmentRef,raw])}`;}
async function readCursor(secret:string,workspaceId:string,segmentRef:string,value:any){if(!value)return null;const [raw,sig,...rest]=String(value).split('.');if(!raw||!sig||rest.length||sig!==await sign(secret,['crm-segment-cursor:v1',workspaceId,segmentRef,raw]))throw new Error('CRM_SEGMENT_CURSOR_INVALID');try{const x=JSON.parse(unb64(raw));if(x.v!==1||typeof x.t!=='string'||!x.t||!/^[a-f0-9]{64}$/.test(x.r||''))throw 0;return x;}catch{throw new Error('CRM_SEGMENT_CURSOR_INVALID');}}
export async function resolveReferences(db:any,workspaceId:string,secret:string,raw:any){const stored=validateSegmentRule(raw),execution=copy(stored);for(let i=0;i<stored.conditions.length;i++){const c:any=stored.conditions[i],values=Array.isArray(c.value)?c.value:[c.value];if(c.field==='tag'||c.field==='stage'){const table=c.field==='tag'?'crm_tags':'crm_pipeline_stages';for(const value of values){const row:any=await db.prepare(`SELECT public_ref FROM ${table} WHERE workspace_id=? AND public_ref=?${c.field==='stage'?" AND status='ACTIVE'":''} LIMIT 1`).bind(workspaceId,value).first();if(!row)throw new Error('CRM_SEGMENT_REFERENCE_INVALID');}}
 if(c.field==='assignedOwner'){const ids:string[]=[];for(const token of values){const verified=await verifyAssigneeHandle(secret,String(token));const users:any[]=(await db.prepare("SELECT id FROM users WHERE workspace_id=? AND status='ACTIVE'").bind(workspaceId).all()).results||[];const matches:string[]=[];for(const user of users)if(await assigneeReference(secret,workspaceId,String(user.id))===verified.reference)matches.push(String(user.id));if(matches.length!==1)throw new Error('CRM_SEGMENT_ASSIGNED_OWNER_INVALID');ids.push(matches[0]);}execution.conditions[i].value=Array.isArray(c.value)?ids:ids[0];}}
 return {stored,execution};}
export const resolveSegmentReferences=resolveReferences;
function publicPeople(rows:any[]){return rows.map(({__segmentCursor,...person})=>person);}
async function pagePosition(secret:string,workspaceId:string,segmentRef:string,people:any[],start:any){if(!start)return 0;for(let i=0;i<people.length;i++){const pos=people[i].__segmentCursor;if(pos.updatedAt===start.t&&await sign(secret,['crm-segment-cursor-person:v1',workspaceId,segmentRef,pos.personId])===start.r)return i+1;}throw new Error('CRM_SEGMENT_CURSOR_INVALID');}
export function registerCrmSegmentRoutes(app:any,deps:any){
 app.get('/api/crm/analytics-summary',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,...await crmAnalyticsSummary(c.env.smart_menu_db,deps.workspaceIdOf(c),analyticsPeriod(c.req.query('period')))});}catch(e){return fail(c,e,'CRM_ANALYTICS_READ_FAILED')}});
 app.post('/api/crm/segments/preview',async(c:any)=>{try{deps.requireRole(c,'viewer');const b:any=await c.req.json().catch(()=>({})),w=deps.workspaceIdOf(c),resolved=await resolveReferences(c.env.smart_menu_db,w,String(c.env.CRM_ASSIGNEE_HANDLE_SECRET||''),b.rule),people=await executeSegment(c.env.smart_menu_db,{workspaceId:w,rule:resolved.execution,includePii:String(c.get('userRole')).toLowerCase()!=='viewer'});return c.json({success:true,totalCount:people.length,previewPeople:publicPeople(people.slice(0,25)),truncated:people.length>25});}catch(e){return fail(c,e,'CRM_SEGMENT_PREVIEW_FAILED')}});
 app.get('/api/crm/segments',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,segments:await listSegments(c.env.smart_menu_db,deps.workspaceIdOf(c))});}catch(e){return fail(c,e,'CRM_SEGMENT_LIST_FAILED')}});
 app.post('/api/crm/segments',async(c:any)=>{try{deps.requireRole(c,'admin');const b:any=await c.req.json().catch(()=>({})),w=deps.workspaceIdOf(c),resolved=await resolveReferences(c.env.smart_menu_db,w,String(c.env.CRM_ASSIGNEE_HANDLE_SECRET||''),b.rule);return c.json({success:true,segment:await createSegment(c.env.smart_menu_db,{workspaceId:w,name:b.name,description:b.description,rule:resolved.stored,userId:deps.text(c.get('userId'))||null})},201);}catch(e){return fail(c,e,'CRM_SEGMENT_CREATE_FAILED')}});
 app.get('/api/crm/segments/:safeSegmentReference',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,segment:await segmentByReference(c.env.smart_menu_db,deps.workspaceIdOf(c),deps.text(c.req.param('safeSegmentReference'),100))});}catch(e){return fail(c,e,'CRM_SEGMENT_READ_FAILED')}});
 app.patch('/api/crm/segments/:safeSegmentReference',async(c:any)=>{try{deps.requireRole(c,'admin');const b:any=await c.req.json().catch(()=>({})),w=deps.workspaceIdOf(c),resolved=await resolveReferences(c.env.smart_menu_db,w,String(c.env.CRM_ASSIGNEE_HANDLE_SECRET||''),b.rule);return c.json({success:true,segment:await updateSegment(c.env.smart_menu_db,{workspaceId:w,publicRef:deps.text(c.req.param('safeSegmentReference'),100),rule:resolved.stored,description:b.description,userId:deps.text(c.get('userId'))||null})});}catch(e){return fail(c,e,'CRM_SEGMENT_UPDATE_FAILED')}});
 app.post('/api/crm/segments/:safeSegmentReference/status',async(c:any)=>{try{deps.requireRole(c,'admin');const b:any=await c.req.json().catch(()=>({}));if(String(b.status||'').toUpperCase()!=='ARCHIVED')throw new Error('CRM_SEGMENT_STATUS_INVALID');return c.json({success:true,segment:await archiveSegment(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),publicRef:deps.text(c.req.param('safeSegmentReference'),100)})});}catch(e){return fail(c,e,'CRM_SEGMENT_STATUS_FAILED')}});
 app.get('/api/crm/segments/:safeSegmentReference/people',async(c:any)=>{try{deps.requireRole(c,'viewer');const w=deps.workspaceIdOf(c),s=await segmentByReference(c.env.smart_menu_db,w,deps.text(c.req.param('safeSegmentReference'),100)),secret=String(c.env.CRM_ASSIGNEE_HANDLE_SECRET||''),limit=Math.min(Math.max(Number(c.req.query('limit')||25),1),100),resolved=await resolveReferences(c.env.smart_menu_db,w,secret,s.rule),people=await executeSegment(c.env.smart_menu_db,{workspaceId:w,rule:resolved.execution,includePii:String(c.get('userRole')).toLowerCase()!=='viewer'}),start=await pagePosition(secret,w,s.safeSegmentReference,people,await readCursor(secret,w,s.safeSegmentReference,c.req.query('cursor'))),page=people.slice(start,start+limit),last=page[page.length-1];return c.json({success:true,people:publicPeople(page),nextCursor:last&&start+limit<people.length?await cursor(secret,w,s.safeSegmentReference,last.__segmentCursor):null});}catch(e){return fail(c,e,'CRM_SEGMENT_PEOPLE_FAILED')}});
}