import { publicCrmPerson } from './index';

const clean=(v:any,max=160)=>typeof v==='string'?v.trim().slice(0,max):'';
const id=(p:string)=>`${p}_${crypto.randomUUID()}`;
const ref=()=>`crms_${crypto.randomUUID().replace(/-/g,'')}`;
const FIELDS:any={status:['EQ','NEQ','IN','NOT_IN'], 'acquisition.firstSource':['EQ','NEQ','IN','NOT_IN'], 'acquisition.latestSource':['EQ','NEQ','IN','NOT_IN'],hasReferrer:['IS_TRUE','IS_FALSE'],tag:['EQ','NEQ','IN','NOT_IN'],stage:['EQ','NEQ','IN','NOT_IN'],assignedOwner:['EQ','NEQ','IN','NOT_IN'],region:['EQ','NEQ','IN','NOT_IN'],preferredLanguage:['EQ','NEQ','IN','NOT_IN'],hasVerifiedLineIdentity:['IS_TRUE','IS_FALSE'],'followUp.overdue':['IS_TRUE','IS_FALSE'],'followUp.hasOpen':['IS_TRUE','IS_FALSE'],'trait.zodiac':['EQ','NEQ','IN','NOT_IN'],createdAt:['BEFORE','AFTER'],updatedAt:['BEFORE','AFTER']};
const LIST=20, MAX_BYTES=12000, IN_MAX=50;
export function validateSegmentRule(raw:any){
  if(!raw||raw.operator!=='AND'||!Array.isArray(raw.conditions)||raw.conditions.length>LIST||JSON.stringify(raw).length>MAX_BYTES)throw new Error('CRM_SEGMENT_RULE_INVALID');
  const conditions=raw.conditions.map((c:any)=>{const field=clean(c?.field,80),op=clean(c?.op,20),keys=Object.keys(c||{}).sort();if(!FIELDS[field]||!FIELDS[field].includes(op))throw new Error('CRM_SEGMENT_RULE_CONDITION_INVALID');const bool=['IS_TRUE','IS_FALSE'].includes(op);if(keys.join(',')!==(bool?'field,op':'field,op,value'))throw new Error('CRM_SEGMENT_RULE_CONDITION_INVALID');if(bool){if(c.value!==undefined&&c.value!==null)throw new Error('CRM_SEGMENT_RULE_VALUE_INVALID');return {field,op};}const owner=(v:string)=>field!=='assignedOwner'||/^[A-Za-z0-9_-]+\.[a-f0-9]{64}$/.test(v);if(['IN','NOT_IN'].includes(op)){if(!Array.isArray(c.value)||!c.value.length||c.value.length>IN_MAX||c.value.some((v:any)=>!clean(v,160)||!owner(clean(v,160))))throw new Error('CRM_SEGMENT_RULE_VALUE_INVALID');return {field,op,value:c.value.map((v:any)=>clean(v,160))};}const value=clean(c.value,160);if(!value||!owner(value)||/[;]|--|\/\*|\*\//.test(value))throw new Error('CRM_SEGMENT_RULE_VALUE_INVALID');return {field,op,value};});
  return {operator:'AND' as const,conditions};
}
const comparison=(column:string,c:any,args:any[])=>{if(c.op==='EQ'||c.op==='NEQ'){args.push(c.value);return `${column}${c.op==='EQ'?'=':'!='}?`;}if(c.op==='IN'||c.op==='NOT_IN'){args.push(...c.value);return `${column} ${c.op==='IN'?'IN':'NOT IN'} (${c.value.map(()=>'?').join(',')})`; }if(c.op==='BEFORE'||c.op==='AFTER'){args.push(c.value);return `${column}${c.op==='BEFORE'?'<':'>'}?`;}throw new Error('CRM_SEGMENT_RULE_CONDITION_INVALID');};
export function compileSegmentRule(rule:any,workspaceId:string,now=new Date().toISOString()){
 const args:any[]=[workspaceId],clauses:string[]=[]; for(const c of validateSegmentRule(rule).conditions){
  if(c.field==='status')clauses.push(comparison('p.status',c,args));
  else if(c.field==='region')clauses.push(comparison('pr.region',c,args)); else if(c.field==='preferredLanguage')clauses.push(comparison('pr.preferred_language',c,args));
  else if(c.field==='createdAt')clauses.push(comparison('p.created_at',c,args)); else if(c.field==='updatedAt')clauses.push(comparison('p.updated_at',c,args));
  else if(c.field==='hasVerifiedLineIdentity')clauses.push(`${c.op==='IS_TRUE'?'':'NOT '}EXISTS(SELECT 1 FROM crm_person_identity_links l WHERE l.workspace_id=p.workspace_id AND l.crm_person_id=p.id AND l.identity_type='LINE_MEMBER' AND l.verification_status='VERIFIED')`);
  else if(c.field==='hasReferrer')clauses.push(`${c.op==='IS_TRUE'?'':'NOT '}EXISTS(SELECT 1 FROM crm_person_identity_links l JOIN member_referral_attributions a ON a.workspace_id=l.workspace_id AND a.line_account_id=l.line_account_id AND a.invitee_member_id=l.line_member_id WHERE l.workspace_id=p.workspace_id AND l.crm_person_id=p.id AND l.identity_type='LINE_MEMBER')`);
  else if(c.field==='followUp.hasOpen')clauses.push(`${c.op==='IS_TRUE'?'':'NOT '}EXISTS(SELECT 1 FROM crm_follow_up_tasks f WHERE f.workspace_id=p.workspace_id AND f.crm_person_id=p.id AND f.status='OPEN')`);
  else if(c.field==='followUp.overdue'){args.push(now);clauses.push(`${c.op==='IS_TRUE'?'':'NOT '}EXISTS(SELECT 1 FROM crm_follow_up_tasks f WHERE f.workspace_id=p.workspace_id AND f.crm_person_id=p.id AND f.status='OPEN' AND f.due_at<?)`);}
  else if(c.field==='tag')clauses.push(`EXISTS(SELECT 1 FROM crm_person_tags pt JOIN crm_tags t ON t.id=pt.crm_tag_id WHERE pt.workspace_id=p.workspace_id AND pt.crm_person_id=p.id AND pt.removed_at IS NULL AND ${comparison('t.public_ref',c,args)})`);
  else if(c.field==='stage')clauses.push(`EXISTS(SELECT 1 FROM crm_person_stage_assignments sa JOIN crm_pipeline_stages s ON s.id=sa.crm_pipeline_stage_id WHERE sa.workspace_id=p.workspace_id AND sa.crm_person_id=p.id AND ${comparison('s.public_ref',c,args)})`);
  else if(c.field==='trait.zodiac')clauses.push(`EXISTS(SELECT 1 FROM crm_person_traits t WHERE t.workspace_id=p.workspace_id AND t.crm_person_id=p.id AND t.trait_type='ZODIAC' AND t.superseded_at IS NULL AND ${comparison('t.trait_value',c,args)})`);
  else if(c.field.startsWith('acquisition.')){const order=c.field.endsWith('firstSource')?'ASC':'DESC';clauses.push(`(SELECT a.source_type FROM crm_acquisition_events a WHERE a.workspace_id=p.workspace_id AND a.crm_person_id=p.id ORDER BY a.occurred_at ${order},a.id ${order} LIMIT 1) ${comparison('',c,args).replace(/^\s*/,'')}`);}
  else if(c.field==='assignedOwner')clauses.push(`EXISTS(SELECT 1 FROM crm_person_relationships r WHERE r.workspace_id=p.workspace_id AND r.crm_person_id=p.id AND r.relationship_type='ASSIGNED_TO' AND r.status='ACTIVE' AND ${comparison('r.related_user_id',c,args)})`);
 }
 return {where:clauses.length?` AND ${clauses.join(' AND ')}`:'',args};
}
export async function executeSegment(db:D1Database,input:any){const {where,args}=compileSegmentRule(input.rule,input.workspaceId,input.now);const rows:any[]=(await db.prepare(`SELECT p.id,p.public_ref,p.status,p.created_at,p.updated_at,pr.*,EXISTS(SELECT 1 FROM crm_person_identity_links l WHERE l.workspace_id=p.workspace_id AND l.crm_person_id=p.id AND l.identity_type='LINE_MEMBER' AND l.verification_status='VERIFIED') has_verified_line_identity FROM crm_people p JOIN crm_profiles pr ON pr.crm_person_id=p.id WHERE p.workspace_id=?${where} ORDER BY p.updated_at DESC,p.public_ref ASC`).bind(...args).all()).results||[];return rows.map(r=>({...publicCrmPerson(r,{includePii:input.includePii!==false,includeInternalNote:false}),__segmentCursor:{updatedAt:String(r.updated_at||''),personId:String(r.id||'')}}));}
const segmentRow=(r:any)=>({safeSegmentReference:clean(r.public_ref,80),name:clean(r.name,120),description:clean(r.description,1000)||null,status:clean(r.status,20),currentVersion:Number(r.current_version_no),createdAt:r.created_at||null,updatedAt:r.updated_at||null});
export async function listSegments(db:D1Database,workspaceId:string){const rows:any[]=(await db.prepare('SELECT s.*,v.description FROM crm_segments s LEFT JOIN crm_segment_versions v ON v.segment_id=s.id AND v.version_no=s.current_version_no WHERE s.workspace_id=? ORDER BY s.updated_at DESC,s.public_ref ASC').bind(workspaceId).all()).results||[];return rows.map(segmentRow);}
export async function segmentByReference(db:D1Database,workspaceId:string,publicRef:string){const s:any=await db.prepare('SELECT * FROM crm_segments WHERE workspace_id=? AND public_ref=?').bind(workspaceId,publicRef).first();if(!s)throw new Error('CRM_SEGMENT_NOT_FOUND');const versions:any[]=(await db.prepare('SELECT version_no,rule_version,rule_json,description,created_at FROM crm_segment_versions WHERE workspace_id=? AND segment_id=? ORDER BY version_no DESC').bind(workspaceId,s.id).all()).results||[];return {...segmentRow(s),rule:JSON.parse(versions[0].rule_json),ruleVersion:Number(versions[0].rule_version),versions:versions.map(v=>({version:Number(v.version_no),ruleVersion:Number(v.rule_version),description:clean(v.description,1000)||null,createdAt:v.created_at}))};}
export async function createSegment(db:D1Database,input:any){const rule=validateSegmentRule(input.rule),name=clean(input.name,120);if(!name)throw new Error('CRM_SEGMENT_NAME_REQUIRED');const segmentId=id('crmseg'),publicRef=ref(),versionId=id('crmsegv'),description=clean(input.description,1000)||null;await db.batch([db.prepare("INSERT INTO crm_segments(id,public_ref,workspace_id,name,status,current_version_no,created_by_user_id) VALUES(?,?,?,?, 'ACTIVE',1,?)").bind(segmentId,publicRef,input.workspaceId,name,input.userId||null),db.prepare('INSERT INTO crm_segment_versions(id,workspace_id,segment_id,version_no,rule_version,rule_json,description,created_by_user_id) VALUES(?,?,?,?,1,?,?,?)').bind(versionId,input.workspaceId,segmentId,1,JSON.stringify(rule),description,input.userId||null)]);return segmentByReference(db,input.workspaceId,publicRef);}
export async function updateSegment(db:D1Database,input:any){const current:any=await db.prepare('SELECT * FROM crm_segments WHERE workspace_id=? AND public_ref=?').bind(input.workspaceId,input.publicRef).first();if(!current)throw new Error('CRM_SEGMENT_NOT_FOUND');if(current.status!=='ACTIVE')throw new Error('CRM_SEGMENT_ARCHIVED');const rule=validateSegmentRule(input.rule),version=Number(current.current_version_no)+1,description=clean(input.description,1000)||null;await db.batch([db.prepare('INSERT INTO crm_segment_versions(id,workspace_id,segment_id,version_no,rule_version,rule_json,description,created_by_user_id) VALUES(?,?,?,?,1,?,?,?)').bind(id('crmsegv'),input.workspaceId,current.id,version,JSON.stringify(rule),description,input.userId||null),db.prepare('UPDATE crm_segments SET current_version_no=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND workspace_id=?').bind(version,current.id,input.workspaceId)]);return segmentByReference(db,input.workspaceId,input.publicRef);}
export async function archiveSegment(db:D1Database,input:any){const r=await db.prepare("UPDATE crm_segments SET status='ARCHIVED',archived_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE workspace_id=? AND public_ref=? AND status='ACTIVE'").bind(input.workspaceId,input.publicRef).run();if(!r.meta.changes)throw new Error('CRM_SEGMENT_NOT_FOUND');return {safeSegmentReference:input.publicRef,status:'ARCHIVED'};}