import type { GuideContext } from '../guide/types.ts';
import type { RecommendationCandidate, RecommendationRule } from '../guide/recommendations/types.ts';

export const JOURNEY_RECOMMENDATION_THRESHOLDS = { minimumObservedSessions: 30, minimumWebhookSamples: 20, minimumConversionSamples: 10, maximumFreshnessDays: 3, minimumMappingRatio: .8, highFailureRate: .2, lowObservedConversionRate: .02, highObservedConversionRate: .1, lowClickShare: .1 } as const;
const q=(c:GuideContext)=>((c as any).journey || { period:{from:'',to:'',days:0}, project:{observedActions:0,aggregateClicks:0,webhookRoutes:0,webhookSuccesses:0,webhookFailures:0,keywordMatches:0,conversions:0}, areas:[], dataQuality:{ready:false,reasonCodes:['NO_JOURNEY_DATA'],conversionIntegrationAvailable:false,observedSessions:0,mappingRatio:0} }) as any;
const ready=(c:GuideContext,...reasons:string[])=>Boolean(q(c)?.dataQuality?.ready)&&reasons.every(reason=>!q(c)?.dataQuality?.reasonCodes?.includes(reason));
const base=(c:GuideContext)=>[{key:'periodFrom',value:q(c).period.from},{key:'periodTo',value:q(c).period.to},{key:'periodDays',value:q(c).period.days},{key:'observedActions',value:q(c).project.observedActions},{key:'observedSessions',value:q(c).dataQuality.observedSessions},{key:'webhookRoutes',value:q(c).project.webhookRoutes},{key:'webhookSuccesses',value:q(c).project.webhookSuccesses},{key:'webhookFailures',value:q(c).project.webhookFailures},{key:'conversions',value:q(c).project.conversions},{key:'mappingRatio',value:q(c).dataQuality.mappingRatio}];
const project=(c:GuideContext,code:string,fields:any):RecommendationCandidate=>({...fields,stableKey:c.project.id+':'+code,entityType:'project',entityId:c.project.id,source:'journey',proposal:{available:false,type:null,reason:'PROPOSAL_NOT_AVAILABLE'},canGenerateProposal:false});
const area=(c:GuideContext,code:string,item:any,fields:any):RecommendationCandidate=>({...project(c,code,fields),stableKey:item.areaId,entityType:'project_area',entityId:item.areaId});
const R201:RecommendationRule={code:'R201',order:201,evaluate(c){const j=q(c);if(!ready(c)||!j.dataQuality.conversionIntegrationAvailable)return[];return j.areas.filter((a:any)=>a.aggregateClicks>0&&a.sessions>=JOURNEY_RECOMMENDATION_THRESHOLDS.minimumObservedSessions&&a.conversions>=JOURNEY_RECOMMENDATION_THRESHOLDS.minimumConversionSamples&&a.observedConversionRate!==null&&a.observedConversionRate<=JOURNEY_RECOMMENDATION_THRESHOLDS.lowObservedConversionRate).map((a:any)=>area(c,'R201',a,{category:'conversion',priority:'high',tone:'improvement',title:'High click area has low observed conversion',message:'This area has aggregate clicks but limited observed downstream conversion quality.',reason:'Review the downstream path using observed data; it does not infer individual URI behavior.',evidence:[...base(c),{key:'aggregateClicks',value:a.aggregateClicks},{key:'observedConversionRate',value:a.observedConversionRate} ],suggestedAction:{type:'navigate',target:'journey-area-'+a.areaId}}));}};
const R202:RecommendationRule={code:'R202',order:202,evaluate(c){const j=q(c);if(!ready(c)||!j.dataQuality.conversionIntegrationAvailable)return[];return j.areas.filter((a:any)=>a.aggregateClicks>0&&a.aggregateClicks/j.project.aggregateClicks<=JOURNEY_RECOMMENDATION_THRESHOLDS.lowClickShare&&a.sessions>=JOURNEY_RECOMMENDATION_THRESHOLDS.minimumObservedSessions&&a.conversions>=JOURNEY_RECOMMENDATION_THRESHOLDS.minimumConversionSamples&&a.observedConversionRate!==null&&a.observedConversionRate>=JOURNEY_RECOMMENDATION_THRESHOLDS.highObservedConversionRate).map((a:any)=>area(c,'R202',a,{category:'conversion',priority:'low',tone:'positive',title:'Low click area converts well',message:'This lower-click area shows strong observed conversion quality.',reason:'Treat this as a positive observed signal, not a prediction.',evidence:[...base(c),{key:'aggregateClicks',value:a.aggregateClicks},{key:'observedConversionRate',value:a.observedConversionRate}],suggestedAction:{type:'navigate',target:'journey-area-'+a.areaId}}));}};
const R203:RecommendationRule={code:'R203',order:203,evaluate(c){const j=q(c);if(j.project.webhookRoutes<JOURNEY_RECOMMENDATION_THRESHOLDS.minimumWebhookSamples)return[];const rate=j.project.webhookFailures/j.project.webhookRoutes;return rate>=JOURNEY_RECOMMENDATION_THRESHOLDS.highFailureRate?[project(c,'R203',{category:'line-oa',priority:'high',tone:'improvement',title:'Webhook failure rate is high',message:'A meaningful share of observed downstream webhook routes failed.',reason:'Review endpoint reliability without exposing request or response payloads.',evidence:[...base(c),{key:'webhookFailureRate',value:rate}],suggestedAction:{type:'navigate',target:'journey-webhook'}})]:[];}};
const R204:RecommendationRule={code:'R204',order:204,evaluate(c){const j=q(c);if(!j.dataQuality.ready||j.project.observedActions<30||j.project.keywordMatches/j.project.observedActions>.1)return[];return[project(c,'R204',{category:'navigation',priority:'medium',tone:'improvement',title:'Keyword flow has a drop-off',message:'Observed actions rarely continue into a keyword-matched flow.',reason:'Review the keyword journey handoff with aggregate counts only.',evidence:[...base(c),{key:'keywordMatches',value:j.project.keywordMatches}],suggestedAction:{type:'navigate',target:'journey-funnel'}})];}};
const R205:RecommendationRule={code:'R205',order:205,evaluate(c){const j=q(c);if(!ready(c)||!j.dataQuality.conversionIntegrationAvailable||j.project.webhookSuccesses<JOURNEY_RECOMMENDATION_THRESHOLDS.minimumWebhookSamples||j.project.conversions<JOURNEY_RECOMMENDATION_THRESHOLDS.minimumConversionSamples)return[];const rate=j.project.conversions/j.project.webhookSuccesses;return rate<=JOURNEY_RECOMMENDATION_THRESHOLDS.lowObservedConversionRate?[project(c,'R205',{category:'conversion',priority:'medium',tone:'improvement',title:'Webhook success has limited observed conversion',message:'Observed webhook success is not followed by a comparable observed conversion rate.',reason:'Review downstream completion instrumentation and experience.',evidence:[...base(c),{key:'observedConversionRate',value:rate}],suggestedAction:{type:'navigate',target:'journey-conversion'}})]:[];}};
const R206:RecommendationRule={code:'R206',order:206,evaluate(c){const j=q(c);if(!ready(c)||!j.dataQuality.conversionIntegrationAvailable||j.project.webhookRoutes<JOURNEY_RECOMMENDATION_THRESHOLDS.minimumWebhookSamples||j.project.conversions<JOURNEY_RECOMMENDATION_THRESHOLDS.minimumConversionSamples)return[];const success=j.project.webhookSuccesses/j.project.webhookRoutes,conversion=j.project.conversions/j.project.webhookSuccesses;return success>=.9&&conversion>=JOURNEY_RECOMMENDATION_THRESHOLDS.highObservedConversionRate?[project(c,'R206',{category:'conversion',priority:'low',tone:'positive',title:'Journey is healthy',message:'Observed action, webhook, and conversion signals are healthy for this period.',reason:'Continue monitoring this observed journey baseline.',evidence:[...base(c),{key:'webhookFailureRate',value:1-success},{key:'observedConversionRate',value:conversion}],suggestedAction:{type:'navigate',target:'journey-summary'}})]:[];}};
export const JOURNEY_RECOMMENDATION_RULES=[R201,R202,R203,R204,R205,R206];
