import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const file=(relative)=>fileURLToPath(new URL(relative,import.meta.url));

test('0040 is additive, workspace scoped, and has immutable workflow history',async()=>{const sql=await readFile(file('../migrations/0040_crm_pipeline_followup.sql'),'utf8');for(const table of ['crm_pipeline_stages','crm_person_stage_assignments','crm_person_stage_events','crm_follow_up_tasks','crm_follow_up_task_events'])assert.match(sql,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));assert.match(sql,/UNIQUE\(workspace_id,crm_person_id\)/);assert.match(sql,/crm_person_stage_events_no_update/);assert.match(sql,/crm_follow_up_task_events_no_delete/);assert.doesNotMatch(sql,/\b(?:ALTER TABLE|DROP TABLE|INSERT INTO crm_pipeline_stages)\b/i);});
test('pipeline route contract uses tenant roles, safe references, and opaque assignee handles',async()=>{const source=await readFile(file('../src/crm/pipeline-routes.ts'),'utf8');for(const path of ["'/api/crm/pipeline-stages'","'/api/crm/people/:safePersonReference/stage'","'/api/crm/people/:safePersonReference/follow-ups'","'/api/crm/follow-ups/:safeTaskReference/status'","'/api/crm/pipeline-summary'","'/api/crm/people/:safePersonReference/business-process'"])assert.ok(source.includes(path));assert.match(source,/verifyAssigneeHandle/);assert.match(source,/assigneeReference/);assert.match(source,/CRM_ASSIGNEE_REFERENCE_REQUIRED/);assert.match(source,/requireRole\(c,'admin'\)/);assert.match(source,/requireRole\(c,'editor'\)/);assert.match(source,/requireRole\(c,'viewer'\)/);assert.doesNotMatch(source,/member\/|dealer\/|referral|commission|point/i);});
test('pipeline service keeps stage, owner, and task domains independent',async()=>{const source=await readFile(file('../src/crm/pipeline.ts'),'utf8');assert.match(source,/await db\.batch\(ops\)/);assert.match(source,/CRM_PIPELINE_STAGE_ARCHIVED/);assert.match(source,/due_at<CURRENT_TIMESTAMP/);assert.match(source,/TASK_STATUSES/);assert.match(source,/status!== 'OPEN'/);assert.match(source,/WHERE changes\(\)=1/);for(const forbidden of ['member_referral','commission_','point_','dealer_','assignCrmOwner','referralSummary'])assert.equal(source.includes(forbidden),false);});
test('public task and pipeline projections exclude raw IDs and viewer notes',async()=>{const source=await readFile(file('../src/crm/pipeline.ts'),'utf8');assert.match(source,/safeTaskReference/);assert.match(source,/stageReference/);assert.match(source,/includeNote\?\{note/);for(const forbidden of ['assigned_user_id:', 'crm_person_id:', 'crm_pipeline_stage_id:', 'line_identity_hash', 'source_ref', 'member_id'])assert.equal(source.includes(forbidden),false);});
