import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { OPTIMIZATION_RECOMMENDATION_RULES, OPTIMIZATION_THRESHOLDS, evaluateOptimizationDataQuality } from '../src/optimization/recommendations.ts';
import { sanitizeOptimizationRecommendationForAi } from '../src/guide/explanations/prompt.ts';
import { executeMeteredAiCall } from '../src/ai/usage.ts';
const base=(x={})=>({period:{from:'2026-08-01',to:'2026-08-30',days:30},project:{aggregateLineClicks:100,trackedUriClicks:90,observedActions:100,attributedConversions:10,attributionCoverage:.9,uriTrackingAvailable:true,conversionIntegrationAvailable:true,conversionSourceEvents:10,activeConversionSources:1,staleConversionSources:0,webhookFailureRate:.05,freshnessDays:0},areas:[{areaId:'a',aggregateLineClicks:20,trackedUriClicks:30,attributedConversions:3,attributionCoverage:.9,trackingEnabled:true,trackedObservedConversionRate:.01}],...x});
const ctx=o=>({project:{id:'p',name:'p',status:'draft',templateId:null,assetId:null,areaCount:1},areas:[],optimization:o,lineAccount:{},completeness:{}});const rule=c=>OPTIMIZATION_RECOMMENDATION_RULES.find(x=>x.code===c); const run=(c,o)=>rule(c).evaluate(ctx(o));
test('R301-R306 trigger and block with deterministic proposal safety',()=>{assert.ok(OPTIMIZATION_THRESHOLDS.minimumTrackedUriClicks>0);assert.equal(run('R301',base({project:{...base().project,attributionCoverage:.2}})).length,1);assert.equal(run('R301',base({project:{...base().project,aggregateLineClicks:1,observedActions:1,attributionCoverage:.2}})).length,0);assert.equal(run('R302',base()).length,1);assert.equal(run('R302',base({areas:[{areaId:'x',trackedUriClicks:19,attributedConversions:3,attributionCoverage:.9,trackingEnabled:true,trackedObservedConversionRate:.01}]})).length,0);assert.equal(run('R303',base({areas:[{areaId:'g',aggregateLineClicks:10,trackedUriClicks:25,attributedConversions:4,attributionCoverage:.9,trackingEnabled:true,trackedObservedConversionRate:.16}]}))[0].tone,'positive');assert.equal(run('R303',base({areas:[{areaId:'tiny',aggregateLineClicks:2,trackedUriClicks:3,attributedConversions:1,attributionCoverage:.9,trackingEnabled:true,trackedObservedConversionRate:.5}]})).length,0);assert.equal(run('R304',base({project:{...base().project,staleConversionSources:1}})).length,1);assert.equal(run('R304',base({project:{...base().project,conversionSourceEvents:0}})).length,0);assert.match(run('R305',base({project:{...base().project,attributionCoverage:.1}}))[0].message,/cannot reliably determine/i);assert.equal(run('R306',base())[0].tone,'positive');assert.equal(run('R306',base({project:{...base().project,freshnessDays:4}})).length,0);for(const c of ['R301','R302','R303','R304','R305','R306'])for(const item of run(c,base({project:{...base().project,staleConversionSources:c==='R304'?1:0,attributionCoverage:c==='R301'||c==='R305'?.1:.9}})))assert.equal(item.proposal.reason,'PROPOSAL_NOT_AVAILABLE');});
test('optimization data quality is explicit and unavailable is not zero performance',()=>{assert.deepEqual(evaluateOptimizationDataQuality(ctx(base())).reasonCodes,['READY']);for(const update of [{aggregateLineClicks:0},{observedActions:0},{uriTrackingAvailable:false},{attributionCoverage:.1},{conversionIntegrationAvailable:false},{conversionSourceEvents:0},{staleConversionSources:1},{freshnessDays:4}])assert.notEqual(evaluateOptimizationDataQuality(ctx(base({project:{...base().project,...update}}))).reasonCodes[0],'READY');});
test('optimization Gemini sanitizer allowlists aggregate primitive evidence',()=>{const payload=sanitizeOptimizationRecommendationForAi({ruleCode:'R303',category:'optimization',priority:'low',tone:'positive',title:'safe',message:'safe',evidence:[{key:'periodFrom',value:'2026-08-01'},{key:'periodTo',value:'2026-08-30'},{key:'periodDays',value:30},{key:'trackedUriClicks',value:30},{key:'attributionToken',value:'secret'},{key:'urlQuery',value:'?x=1'},{key:'rawJourneyRows',value:'raw'},{key:'apiKeyHash',value:'hash'}],token:'nope'});assert.deepEqual(payload.evidence.map(x=>x.key),['periodFrom','periodTo','periodDays','trackedUriClicks']);for(const forbidden of ['secret','?x=1','raw','hash','token'])assert.equal(JSON.stringify(payload).includes(forbidden),false);});
class Db{constructor(){this.ledger=[]}prepare(sql){const db=this;return{bind(...args){return{async first(){return null},async run(){if(sql.includes('INSERT INTO ai_usage_ledger'))db.ledger.push(args);return{meta:{changes:1}}}}}}}}
test('optimization evaluation is free and actual explanations meter the dedicated feature',async()=>{const db=new Db();run('R303',base({areas:[{areaId:'g',aggregateLineClicks:10,trackedUriClicks:25,attributedConversions:4,attributionCoverage:.9,trackingEnabled:true,trackedObservedConversionRate:.16}]}));assert.equal(db.ledger.length,0);await executeMeteredAiCall({db,workspaceId:'ws',userId:'u',featureCode:'optimization_recommendation_explanation',operationCode:'R303',provider:'google',model:'gemini',execute:async()=>({value:'fallback',status:'fallback',usage:{inputTokens:1,outputTokens:1}})});assert.deepEqual(db.ledger[0].slice(1,5),['ws','u','optimization_recommendation_explanation','R303']);assert.equal(db.ledger[0][15],0);});
test('completion wiring uses backend grouping, server block, and safe UIs',async()=>{const [engine,index,ui,health]=await Promise.all([readFile(new URL('../src/guide/recommendations/engine.ts',import.meta.url),'utf8'),readFile(new URL('../src/index.ts',import.meta.url),'utf8'),readFile(new URL('../../frontend/src/components/OptimizationIntelligencePanel.jsx',import.meta.url),'utf8'),readFile(new URL('../../frontend/src/components/LineIntelligenceHealthPanel.jsx',import.meta.url),'utf8')]);for(const word of ['usage-vs-conversion-quality','tracked-conversion-quality','optimization-observability','click-trend'])assert.ok(engine.includes(word));assert.match(index,/source === 'optimization'/);assert.match(index,/optimization_recommendation_explanation/);for(const word of ['Attribution Coverage','Optimization Ready','Tracked URI observed'])assert.ok(ui.includes(word));for(const word of ['Final Optimization Health','Optimization Ready','Sources Ready'])assert.ok(health.includes(word));});
