import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createReferralFlowToken, recordReferralAnalyticsEvent, referralEventKeys, reuseReferralFlowToken, verifyReferralFlowToken } from '../src/referral/growth.ts';

function eventDb({fail=false}={}) { const rows=[]; return {rows,prepare(sql){let values=[];return {bind(...input){values=input;return this},async run(){if(fail)throw new Error('analytics unavailable');const [,workspaceId,lineAccountId,,,,,eventType,,dedupeKey]=values;if(rows.some(row=>row.workspaceId===workspaceId&&row.lineAccountId===lineAccountId&&row.eventType===eventType&&row.dedupeKey===dedupeKey))return {meta:{changes:0}};rows.push({workspaceId,lineAccountId,eventType,dedupeKey,values});return {meta:{changes:1}}}}}}; }
const safeInput=(eventType,dedupeKey)=>({workspaceId:'w1',lineAccountId:'a1',referralIdentityId:'ri1',inviterMemberId:'m-inviter',inviteeMemberId:'m-invitee',eventType,source:'qr',dedupeKey});

async function routeSource(){return readFile(new URL('../src/index.ts',import.meta.url),'utf8')}

test('A2 exact flow reuse and landing persistence remain stage-idempotent',async()=>{const token=await createReferralFlowToken('s',{workspaceId:'w1',lineAccountId:'a1',referralIdentityId:'ri1',source:'qr'});assert.strictEqual(await reuseReferralFlowToken('s',token,{workspaceId:'w1',lineAccountId:'a1',referralIdentityId:'ri1',source:'qr'}),token);assert.equal(await reuseReferralFlowToken('s',token,{workspaceId:'w1',lineAccountId:'a1',referralIdentityId:'ri1',source:'line_share'}),null);const db=eventDb(),keys=await referralEventKeys('s',{workspaceId:'w1',lineAccountId:'a1',eventType:'REFERRAL_LINK_OPENED',flowNonce:token});assert.equal(await recordReferralAnalyticsEvent(db,safeInput('REFERRAL_LINK_OPENED',keys.dedupeKey)),true);assert.equal(await recordReferralAnalyticsEvent(db,safeInput('REFERRAL_LINK_OPENED',keys.dedupeKey)),false);assert.equal(db.rows.length,1);const other=await createReferralFlowToken('s',{workspaceId:'w1',lineAccountId:'a1',referralIdentityId:'ri1',source:'qr'}),otherKeys=await referralEventKeys('s',{workspaceId:'w1',lineAccountId:'a1',eventType:'REFERRAL_LINK_OPENED',flowNonce:other});assert.equal(await recordReferralAnalyticsEvent(db,safeInput('REFERRAL_LINK_OPENED',otherKeys.dedupeKey)),true);assert.equal(db.rows.length,2);});

test('all five stages use the verified flow as their dedupe input and persist no raw flow token',async()=>{const token=await createReferralFlowToken('s',{workspaceId:'w1',lineAccountId:'a1',referralIdentityId:'ri1',source:'qr'}),flow=await verifyReferralFlowToken('s',token),db=eventDb();for(const eventType of ['REFERRAL_LINK_OPENED','LIFF_AUTHENTICATED','MEMBER_ESTABLISHED','FRIENDSHIP_CONFIRMED','REFERRAL_QUALIFIED']){const keys=await referralEventKeys('s',{workspaceId:flow.workspaceId,lineAccountId:flow.lineAccountId,eventType,flowNonce:token});assert.equal(await recordReferralAnalyticsEvent(db,safeInput(eventType,keys.dedupeKey)),true);assert.equal(await recordReferralAnalyticsEvent(db,safeInput(eventType,keys.dedupeKey)),false)}assert.equal(db.rows.length,5);assert.ok(db.rows.every(row=>!JSON.stringify(row).includes(token)));});

test('A3/A4 production route requires backend LIFF authority and retains the non-referral path',async()=>{const source=await routeSource();const establish=source.slice(source.indexOf("app.post('/api/member/establish'"),source.indexOf("app.get('/api/member/referral'"));assert.match(establish,/verifiedReferralMember\(c,body\)/);assert.match(establish,/verifyReferralFlowToken/);assert.match(establish,/LIFF_AUTHENTICATED/);assert.match(establish,/MEMBER_ESTABLISHED/);assert.match(establish,/if\(supplied\)/);assert.match(establish,/referralFlowInvalid/);assert.doesNotMatch(establish,/lineUserId/);});

test('A5/A6 production route orders observations after their backend business authorities',async()=>{const source=await routeSource();const qualify=source.slice(source.indexOf("app.post('/api/member/referral/qualify'"),source.indexOf("app.get('/api/ai-usage/summary'"));const friendship=qualify.indexOf('backendFriendship(verified.token)'),friendEvent=qualify.indexOf("eventType:'FRIENDSHIP_CONFIRMED'"),insert=qualify.indexOf('INSERT INTO member_referral_attributions'),qualified=qualify.indexOf("eventType:'REFERRAL_QUALIFIED'"),already=qualify.indexOf("status:'ALREADY_QUALIFIED'");assert.ok(friendship>=0&&friendEvent>friendship);assert.ok(insert>=0&&qualified>insert);assert.ok(already>qualified);assert.match(qualify,/if\(!friendshipConfirmed\).*NOT_FRIEND/);assert.match(qualify,/recordReferralAnalyticsEvent[\s\S]*?\.catch\(\(\)=>\{\}\)/);});

test('writer unique conflict and writer failure preserve the observational safety contract',async()=>{const db=eventDb(),input=safeInput('REFERRAL_QUALIFIED','dedupe-a');assert.equal(await recordReferralAnalyticsEvent(db,input),true);assert.equal(await recordReferralAnalyticsEvent(db,input),false);await assert.rejects(()=>recordReferralAnalyticsEvent(eventDb({fail:true}),input));const source=await routeSource();const qualify=source.slice(source.indexOf("app.post('/api/member/referral/qualify'"),source.indexOf("app.get('/api/ai-usage/summary'"));assert.match(qualify,/eventType:'REFERRAL_QUALIFIED'[\s\S]*?\.catch\(\(\)=>\{\}\)/);});

test('analytics contract has no columns for raw identity, token, PII, IP, or device data',async()=>{const migration=await readFile(new URL('../migrations/0023_referral_growth_analytics.sql',import.meta.url),'utf8');for(const forbidden of ['line_user_id','line_identity_hash','access_token','referral_flow_token','referral_code TEXT','email','phone','ip_address','user_agent','device'])assert.equal(migration.includes(forbidden),false);});