import test from 'node:test';import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';import{REFERRAL_ANALYTICS_EVENT_REGISTRY,REFERRAL_ANALYTICS_SOURCE_REGISTRY,referralAnalyticsFingerprint,referralEventKeys,createReferralFlowToken,verifyReferralFlowToken,evaluateReferralGrowthDataQuality,funnelRate,referralFunnelRates,referralGrowthRecommendations,reuseReferralFlowToken}from'../src/referral/growth.ts';
test('0023 is additive-only referral analytics storage with required safe indexes',async()=>{const migration=await readFile(new URL('../migrations/0023_referral_growth_analytics.sql',import.meta.url),'utf8');assert.match(migration,/CREATE TABLE IF NOT EXISTS member_referral_events/);for(const index of['idx_referral_events_workspace_time','idx_referral_events_source_time','idx_referral_events_identity_time','idx_referral_events_dedupe'])assert.match(migration,new RegExp(index));assert.doesNotMatch(migration,/(?:^|;)\s*(?:ALTER TABLE|UPDATE|DELETE FROM|DROP TABLE)\b/im);for(const forbidden of['line_identity_hash','access_token','line_user_id','email','phone','ip_address','user_agent','metadata'])assert.equal(migration.includes(forbidden),false);});
test('analytics registry accepts only five server event stages and three source contexts',()=>{assert.deepEqual([...REFERRAL_ANALYTICS_EVENT_REGISTRY],['REFERRAL_LINK_OPENED','LIFF_AUTHENTICATED','FRIENDSHIP_CONFIRMED','MEMBER_ESTABLISHED','REFERRAL_QUALIFIED']);assert.deepEqual([...REFERRAL_ANALYTICS_SOURCE_REGISTRY],['qr','line_share','web_share']);});
test('dedupe and referral-code fingerprints are HMAC opaque and workspace scoped',async()=>{const a=await referralEventKeys('analytics-secret',{workspaceId:'w1',lineAccountId:'a1',eventType:'REFERRAL_LINK_OPENED',flowNonce:'flow-a',referralCode:'r_secret'}),b=await referralEventKeys('analytics-secret',{workspaceId:'w2',lineAccountId:'a1',eventType:'REFERRAL_LINK_OPENED',flowNonce:'flow-a',referralCode:'r_secret'});assert.notEqual(a.dedupeKey,b.dedupeKey);assert.equal(a.dedupeKey.includes('r_secret'),false);assert.equal(a.referralCodeFingerprint.includes('r_secret'),false);assert.equal(await referralAnalyticsFingerprint('analytics-secret',['w1','a1']),await referralAnalyticsFingerprint('analytics-secret',['w1','a1']));});
test('signed opaque flow tokens bind referral context without a raw code or identity hash',async()=>{const token=await createReferralFlowToken('analytics-secret',{workspaceId:'w1',lineAccountId:'a1',referralIdentityId:'ri1',source:'qr'});const flow=await verifyReferralFlowToken('analytics-secret',token);assert.equal(flow.workspaceId,'w1');assert.equal(flow.source,'qr');assert.equal(token.includes('r_secret'),false);await assert.rejects(()=>verifyReferralFlowToken('wrong-secret',token));});
test('growth quality and rates use unavailable states instead of fake zero rates',()=>{assert.equal(funnelRate(0,0),null);assert.equal(evaluateReferralGrowthDataQuality({landings:0,qualified:0,liffReady:true}).code,'NO_REFERRAL_DATA');assert.equal(evaluateReferralGrowthDataQuality({landings:12,qualified:2,liffReady:true,lastOccurredAt:new Date().toISOString()}).code,'READY');});

test('R401-R406 are deterministic advisory-only and group dominant funnel loss',()=>{const funnel={landings:20,authenticated:20,friendshipConfirmed:5,memberEstablished:5,qualified:1};const rules=referralGrowthRecommendations({funnel,liffReady:true,lastOccurredAt:new Date().toISOString(),sources:{qr:{landings:5,authenticated:5,friendshipConfirmed:5,memberEstablished:5,qualified:2},line_share:{landings:5,authenticated:5,friendshipConfirmed:5,memberEstablished:5,qualified:2},web_share:{landings:0,authenticated:0,friendshipConfirmed:0,memberEstablished:0,qualified:0}}});assert.equal(referralFunnelRates({landings:0,authenticated:0,friendshipConfirmed:0,memberEstablished:0,qualified:0}).landingToAuth,null);assert.equal(rules[0].ruleCode,'R402');assert.ok(rules.every(x=>x.source==='referral_growth'&&x.proposal.available===false));assert.ok(rules.some(x=>x.ruleCode==='R404'));assert.ok(rules.some(x=>x.ruleCode==='R405'));});

test('existing matching signed flow token is returned by exact string equality',async()=>{const t=await createReferralFlowToken('s',{workspaceId:'w',lineAccountId:'a',referralIdentityId:'r',source:'qr'});assert.strictEqual(await reuseReferralFlowToken('s',t,{workspaceId:'w',lineAccountId:'a',referralIdentityId:'r',source:'qr'}),t);});
