import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { sanitizeReferralGrowthRecommendationForAi } from '../src/guide/explanations/prompt.ts';

const recommendation={ruleCode:'R401',category:'referral_growth',priority:'high',tone:'improvement',title:'t',message:'m',evidence:[{key:'periodFrom',value:'2026-08-01'},{key:'periodTo',value:'2026-08-08'},{key:'periodDays',value:7},{key:'landings',value:12},{key:'qualified',value:1},{key:'source',value:'qr'},{key:'inviter_member_id',value:'m1'},{key:'referralFlowToken',value:'secret'},{key:'rawEvents',value:[{id:'x'}]},{key:'unknown',value:{x:1}}]};
test('referral Gemini sanitizer permits only aggregate primitive evidence',()=>{const safe=sanitizeReferralGrowthRecommendationForAi(recommendation);assert.deepEqual(safe.evidence.map(x=>x.key),['periodFrom','periodTo','periodDays','landings','qualified','source']);assert.equal(JSON.stringify(safe).includes('secret'),false);assert.equal(JSON.stringify(safe).includes('m1'),false);});
test('referral explanation recomputes backend rules, meters only provider calls, and retains proposal block',async()=>{const source=await readFile(new URL('../src/index.ts',import.meta.url),'utf8');const route=source.slice(source.indexOf("app.post('/api/referral-growth/recommendations/:ruleCode/explain'"),source.indexOf("app.get('/api/member/referral-growth'"));assert.match(route,/referralGrowthSnapshot/);assert.match(route,/source==='referral_growth'/);assert.match(route,/featureCode:'referral_growth_recommendation_explanation'/);assert.match(route,/executeMeteredAiCall/);assert.match(route,/available:false,reasonCode:'PROPOSAL_NOT_AVAILABLE'/);assert.doesNotMatch(route,/referralFlowToken|dedupeKey|inviter_member_id|invitee_member_id/);});
test('System Admin growth health is aggregate-only and authorization guarded',async()=>{const source=await readFile(new URL('../src/index.ts',import.meta.url),'utf8');const route=source.slice(source.indexOf("app.get('/api/system/referral-growth-health'"),source.indexOf("app.get('/api/system/referral-health'"));assert.match(route,/requireSystemAdmin/);assert.match(route,/member_referral_attributions/);assert.match(route,/REFERRAL_LINK_OPENED/);assert.match(route,/overallQualificationRate:landings\?qualifiedCount\/landings:null/);for(const forbidden of ['topContributors','memberId','inviter_member_id','invitee_member_id','referral_code','dedupe_key','line_identity_hash','accessToken'])assert.equal(route.includes(forbidden),false);});
