import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { referralGrowthSnapshot } from '../src/referral/growth-api.ts';

function db({events=[],attributions=[]}={}) {
  return { prepare(sql) { return { bind(){ return this }, async all(){ const q=String(sql); if(q.includes('member_referral_events')) return {results:events}; if(q.includes('substr(qualified_at')) return {results:[{day:'2026-08-08',count:attributions.length}]}; return {results:attributions}; }, async first(){ return {count:1}; } }; } };
}
test('member aggregates use attribution truth, sources, trends, and null-safe rates',async()=>{const s=await referralGrowthSnapshot(db({events:[{event_type:'REFERRAL_LINK_OPENED',source:'qr',count:2,last_at:'2026-08-08'},{event_type:'REFERRAL_LINK_OPENED',source:'line_share',count:1,last_at:'2026-08-08'},{event_type:'REFERRAL_QUALIFIED',source:'web_share',count:99,last_at:'2026-08-08'}],attributions:[{source:'qr',count:1,last_at:'2026-08-08'},{source:'web_share',count:2,last_at:'2026-08-08'}]}),{workspaceId:'w',lineAccountId:'a',inviterMemberId:'trusted',referralIdentityId:'ri',days:7});assert.equal(s.funnel.qualified,3);assert.equal(s.sourceBreakdown.qr.qualificationRate,.5);assert.equal(s.sourceBreakdown.line_share.qualificationRate,0);assert.equal(s.sourceBreakdown.web_share.qualificationRate,null);assert.deepEqual(s.trend,[{day:'2026-08-08',qualified:2}]);});
test('member self route derives identity from verified LIFF context and returns no internal identifiers',async()=>{const source=await readFile(new URL('../src/index.ts',import.meta.url),'utf8');const route=source.slice(source.indexOf("app.get('/api/member/referral-growth'"),source.indexOf("app.post('/api/member/referral/qualify'"));assert.match(route,/verifiedReferralMember/);assert.match(route,/inviterMemberId:verified\.memberId/);assert.match(route,/referralIdentityId:identity\?\.id/);assert.match(route,/qualified7d/);assert.match(route,/qualified30d/);for(const forbidden of ['memberId:','line_identity_hash','lineUserId','dedupeKey','referralFlowToken','invitee'])assert.equal(route.includes(forbidden),false);});
