import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

const read = relative => readFile(new URL(relative, import.meta.url), 'utf8');
const [migration, foundation, travel, routes, memberRoutes, index] = await Promise.all([
  read('../migrations/0052_travel_ui_contract.sql'),
  read('../migrations/0051_travel_foundation.sql'),
  read('../src/travel/travel.ts'),
  read('../src/travel/routes.ts'),
  read('../src/travel/member-routes.ts'),
  read('../src/index.ts'),
]);

const contracts = [
  ['0052 is additive only', migration, /Additive only; no backfill, seed data/],
  ['0052 adds itinerary region', migration, /ADD COLUMN region TEXT/],
  ['region is bounded', migration, /length\(region\) <= 120/],
  ['0052 adds itinerary notes', migration, /ADD COLUMN notes TEXT/],
  ['notes are bounded', migration, /length\(notes\) <= 4000/],
  ['0052 adds cover reference', migration, /ADD COLUMN cover_asset_reference TEXT/],
  ['cover reference is optional', migration, /cover_asset_reference IS NULL/],
  ['0052 adds minimum group size', migration, /ADD COLUMN min_group_size INTEGER/],
  ['minimum group size is bounded', migration, /min_group_size BETWEEN 1 AND 10000/],
  ['0052 contains no table replacement', migration, /^(?![\s\S]*\bDROP\b)/i],
  ['0052 contains no backfill update', migration, /^(?![\s\S]^\s*UPDATE\s)/im],
  ['0052 contains no seeded insert', migration, /^(?![\s\S]^\s*INSERT\s+INTO\s)/im],
  ['0052 contains no delete', migration, /^(?![\s\S]^\s*DELETE\s+FROM\s)/im],
  ['cover insert is workspace scoped', migration, /travel_itinerary_cover_scope_insert[^]*a\.workspace_id=NEW\.workspace_id/],
  ['cover update is workspace scoped', migration, /travel_itinerary_cover_scope_update[^]*a\.workspace_id=NEW\.workspace_id/],
  ['cover must be ready', migration, /a\.status='ready'/],
  ['cover must be an image', migration, /a\.content_type LIKE 'image\/%'/],
  ['cover must be R2-backed', migration, /length\(a\.storage_key\)>0/],
  ['deleted covers are rejected', migration, /a\.deleted_at IS NULL/],
  ['minimum group size cannot exceed seats on insert', migration, /travel_departure_group_size_insert[^]*NEW\.min_group_size>NEW\.seat_limit/],
  ['minimum group size cannot exceed seats on update', migration, /travel_departure_group_size_update[^]*NEW\.min_group_size>NEW\.seat_limit/],
  ['database prevents seat limit below reserved', migration, /travel_departure_reserved_seat_guard[^]*TRAVEL_SEAT_LIMIT_BELOW_RESERVED/],
  ['cancelled bookings do not reserve seats', migration, /booking_status<>'CANCELLED'/],
  ['0051 remains unchanged foundation authority', foundation, /0051 Travel itinerary, departure, booking/],
  ['itinerary create accepts region', travel, /createItinerary[^]*'region'/],
  ['itinerary create accepts notes', travel, /createItinerary[^]*'notes'/],
  ['itinerary create accepts cover reference', travel, /createItinerary[^]*'coverAssetReference'/],
  ['itinerary update accepts region notes and cover', travel, /updateItinerary[^]*\['title','summary','durationDays','region','notes','coverAssetReference'\]/],
  ['region rejects over-limit input', travel, /boundedText\(input\.body\.region,120,'TRAVEL_ITINERARY_REGION_INVALID'\)/],
  ['notes reject over-limit input', travel, /boundedText\(input\.body\.notes,4000,'TRAVEL_ITINERARY_NOTES_INVALID'\)/],
  ['cover reference uses established asset namespace', travel, /\^asset_\[A-Za-z0-9_-\]/],
  ['cover lookup is workspace scoped', travel, /SELECT id FROM assets[^]*id=\? AND workspace_id=\?/],
  ['cover lookup rejects deleted assets', travel, /deleted_at IS NULL AND status='ready'/],
  ['cover lookup accepts only images', travel, /content_type LIKE 'image\/%'/],
  ['cover projection exposes safe reference', travel, /coverAssetReference/],
  ['cover projection exposes tenant and member safe route URLs', travel, /coverUrl:[^\r\n]*\/api\/member\/travel\/assets[^\r\n]*\/api\/assets/],
  ['member cover asset route exists', memberRoutes, /\/api\/member\/travel\/assets\/:coverAssetReference/],
  ['member cover asset route uses verified member context', memberRoutes, /assets\/:coverAssetReference[^]*const ctx=await context\(c,deps\)/],
  ['member cover asset lookup is workspace scoped and image only', memberRoutes, /SELECT storage_key,content_type FROM assets[^]*id=\? AND workspace_id=\?[^]*content_type LIKE 'image\/%'/],
  ['member cover asset reads through the R2 binding', memberRoutes, /smart_menu_assets\.get\(asset\.storage_key\)/],
  ['cover projection never exposes storage key', travel, /^(?![\s\S]*storageKey\s*:)/],
  ['itinerary reads revalidate cover authority', travel, /LEFT JOIN assets a ON a\.id=i\.cover_asset_reference AND a\.workspace_id=i\.workspace_id/],
  ['departure create accepts minimum group size', travel, /createDeparture[^]*'minGroupSize'/],
  ['departure projection returns minimum group size', travel, /minGroupSize: Number\(row\.min_group_size/],
  ['tenant departure PATCH route exists', routes, /app\.patch\('\/api\/travel\/departures\/:safeDepartureReference'/],
  ['departure PATCH requires admin', routes, /app\.patch\('\/api\/travel\/departures[^]*deps\.requireRole\(c,'admin'\)/],
  ['departure PATCH is workspace scoped', travel, /updateDeparture[^]*d\.workspace_id=\? AND d\.public_ref=\?/],
  ['departure edit uses an exact whitelist', travel, /const allowed=\['departureDate','returnDate','bookingOpensAt','bookingClosesAt','seatLimit','minGroupSize','priceAmountMinor','currencyCode'\]/],
  ['departure edit excludes status mutation input', travel, /const allowed=\[(?![^\]]*status)/],
  ['closed departures are protected', travel, /\['CLOSED','SOLD_OUT','CANCELLED','ARCHIVED'\]\.includes\(row\.status\)/],
  ['open departure edit is limited', travel, /row\.status==='OPEN'[^]*\['bookingClosesAt','seatLimit','minGroupSize','priceAmountMinor','currencyCode'\]/],
  ['reserved departure dates are locked', travel, /reserved>0[^]*TRAVEL_DEPARTURE_DATE_LOCKED/],
  ['service prevents seat limit below reserved', travel, /seatLimit<reserved[^]*TRAVEL_SEAT_LIMIT_BELOW_RESERVED/],
  ['booking window remains ordered', travel, /if\(closes<=opens\)throw new Error\('TRAVEL_BOOKING_WINDOW_INVALID'\)/],
  ['departure date range remains ordered', travel, /if\(returnDate<departureDate\)throw new Error\('TRAVEL_DATE_RANGE_INVALID'\)/],
  ['departure edit remains TWD only', travel, /currencyCode!==undefined&&input\.body\.currencyCode!=='TWD'/],
  ['price update synchronizes Travel Commerce offer', travel, /UPDATE commerce_products SET name=\?,description=\?,price_amount_minor=\?/],
  ['offer synchronization is workspace scoped', travel, /commerce_products[^]*WHERE workspace_id=\? AND product_kind='TRAVEL_DEPARTURE'/],
  ['offer synchronization uses Travel source authority', travel, /source_domain='TRAVEL_DEPARTURE' AND source_reference=\?/],
  ['booking projection includes safe customer label', travel, /safeCustomerLabel:/],
  ['safe customer label reuses CRM profile', travel, /JOIN crm_people cp[^]*LEFT JOIN crm_profiles pr/],
  ['safe customer lookup is workspace scoped', travel, /cp\.workspace_id=b\.workspace_id/],
  ['safe customer label has a privacy-safe fallback', travel, /'會員顧客'\) safe_customer_label/],
  ['tenant booking events route exists', routes, /\/api\/travel\/bookings\/:safeBookingReference\/events/],
  ['member own booking events route exists', memberRoutes, /\/api\/member\/travel\/bookings\/:safeBookingReference\/events/],
  ['member events reuse verified member context', memberRoutes, /bookings\/:safeBookingReference\/events[^]*const ctx=await context\(c,deps\)/],
  ['member event lookup scopes account and member', travel, /listBookingEvents[^]*line_account_id=\?[^]*line_member_id=\?/],
  ['event timeline is bounded', travel, /ORDER BY occurred_at ASC,id ASC LIMIT 100/],
  ['event projection is chronological', travel, /ORDER BY occurred_at ASC,id ASC/],
  ['event projection returns type time and safe label', travel, /eventType:[^]*occurredAt:[^]*safeEventLabel:/],
  ['event projection does not return event id', travel, /SELECT event_type,occurred_at FROM travel_events/],
  ['no global tenant departure list route is added', routes, /^(?![\s\S]*app\.get\('\/api\/travel\/departures'\s*,)/],
  ['Travel exposes no LINE UID or hash', travel, /^(?![\s\S]*(lineUserId|line_user_id|identityHash|identity_hash)\s*:)/],
  ['booking projection exposes no internal customer or order IDs', travel, /function bookingView\((?![^\r\n]*(crmPersonId|commerceOrderId|paymentObligationId)\s*:)[^\r\n]*/],
  ['Travel performs no Referral mutation', travel, /^(?![\s\S]*(UPDATE|INSERT INTO) referral\w*\b)/i],
  ['Travel performs no Points mutation', travel, /^(?![\s\S]*(UPDATE|INSERT INTO) (points|rewards)\w*\b)/i],
  ['Travel performs no Commission mutation', travel, /^(?![\s\S]*(UPDATE|INSERT INTO) (commission|payout)\w*\b)/i],
  ['Travel performs no CRM mutation', travel, /^(?![\s\S]*(UPDATE|INSERT INTO) crm_(profiles|stages|follow|tags)\w*\b)/i],
  ['Travel performs no Campaign mutation', travel, /^(?![\s\S]*(UPDATE|INSERT INTO) campaign\w*\b)/i],
  ['Travel invokes no AI', travel, /^(?![\s\S]*(GEMINI|OPENAI|executeMeteredAiCall))/i],
  ['Travel imports no TravelKeeper data', `${migration}\n${travel}`, /^(?![\s\S]*TravelKeeper)/i],
  ['asset API remains workspace scoped', index, /SELECT \* FROM assets WHERE id = \? AND workspace_id = \? AND deleted_at IS NULL/],
];

for (const [name, source, pattern] of contracts) test(name, () => assert.match(source, pattern));
