import { createDeparture, createItinerary, listBookingEvents, listBookings, listDepartures, listItineraries, readBooking, readDeparture, readItinerary, setDepartureStatus, transitionItinerary, updateDeparture, updateItinerary } from './travel';
import { grantTravelSellerPermission, listTravelSellers, revokeTravelSellerPermission } from './seller-commission.ts';
import { listDepartureOperationBookings, listDepartureOperationEvents, listDepartureOperationTravelers, readDepartureOperations } from './operations.ts';
import { completeDepartureService, confirmDepartureOperation } from './milestones.ts';
import { registerTravelPromotionRoutes } from './promotion-routes.ts';

const known = /^TRAVEL_[A-Z0-9_]+$/;
function fail(c:any,error:unknown,fallback:string){const raw=error instanceof Error?error.message:'';const code=raw==='FORBIDDEN_ROLE'?'FORBIDDEN':known.test(raw)?raw:fallback;const status=code==='FORBIDDEN'||code==='TRAVEL_PROMOTION_AI_DISABLED'?403:code.endsWith('_NOT_FOUND')?404:code==='TRAVEL_PROMOTION_AI_UNAVAILABLE'?503:code.includes('CAPACITY')||code.includes('TRANSITION')||code.includes('NOT_EDITABLE')||code.includes('ARCHIVED')||code.includes('VERSION_CONFLICT')?409:400;return c.json({success:false,error:code},status);}

export function registerTravelRoutes(app:any,deps:any){
  registerTravelPromotionRoutes(app,deps,fail);
  app.get('/api/travel/departures/:safeDepartureReference/operations',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,operations:await readDepartureOperations(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),safeDepartureReference:deps.text(c.req.param('safeDepartureReference'),100)})});}catch(e){return fail(c,e,'TRAVEL_DEPARTURE_OPERATIONS_READ_FAILED')}});
  for(const [path,mutate] of [['confirm',confirmDepartureOperation],['complete',completeDepartureService]] as const){app.post(`/api/travel/departures/:safeDepartureReference/operations/${path}`,async(c:any)=>{try{deps.requireRole(c,'admin');const body=await c.req.json().catch(()=>({}));if(!body||typeof body!=='object'||Array.isArray(body)||Object.keys(body).length)throw new Error('TRAVEL_OPERATION_INPUT_INVALID');const operationalState=await mutate(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),safeDepartureReference:deps.text(c.req.param('safeDepartureReference'),100),actorUserId:deps.text(c.get('userId'))||null});return c.json({success:true,operationalState});}catch(e){return fail(c,e,'TRAVEL_OPERATION_MUTATION_FAILED')}})}
  app.get('/api/travel/departures/:safeDepartureReference/bookings',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,...await listDepartureOperationBookings(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),safeDepartureReference:deps.text(c.req.param('safeDepartureReference'),100),limit:c.req.query('limit'),page:c.req.query('page')})});}catch(e){return fail(c,e,'TRAVEL_DEPARTURE_BOOKINGS_READ_FAILED')}});
  app.get('/api/travel/departures/:safeDepartureReference/travelers',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,...await listDepartureOperationTravelers(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),safeDepartureReference:deps.text(c.req.param('safeDepartureReference'),100),limit:c.req.query('limit'),page:c.req.query('page')})});}catch(e){return fail(c,e,'TRAVEL_DEPARTURE_TRAVELERS_READ_FAILED')}});
  app.get('/api/travel/departures/:safeDepartureReference/events',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,...await listDepartureOperationEvents(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),safeDepartureReference:deps.text(c.req.param('safeDepartureReference'),100),limit:c.req.query('limit')})});}catch(e){return fail(c,e,'TRAVEL_DEPARTURE_EVENTS_READ_FAILED')}});
  app.get('/api/travel/sellers',async(c:any)=>{try{deps.requireRole(c,'viewer');const lineAccountId=deps.text(c.req.query('lineAccountId'),100);return c.json({success:true,sellers:await listTravelSellers(c.env.smart_menu_db,{secret:deps.text(c.env.MEMBER_IDENTITY_HMAC_SECRET),workspaceId:deps.workspaceIdOf(c),lineAccountId})});}catch(e){return fail(c,e,'TRAVEL_SELLER_LIST_FAILED')}});
  app.post('/api/travel/sellers/:safeDealerReference/permission',async(c:any)=>{try{deps.requireRole(c,'admin');const body=await c.req.json().catch(()=>({}));if(!body||typeof body!=='object'||Array.isArray(body)||Object.keys(body).length)throw new Error('TRAVEL_SELLER_PERMISSION_INPUT_INVALID');const seller=await grantTravelSellerPermission(c.env.smart_menu_db,{secret:deps.text(c.env.MEMBER_IDENTITY_HMAC_SECRET),workspaceId:deps.workspaceIdOf(c),lineAccountId:deps.text(c.req.query('lineAccountId'),100),safeSellerReference:deps.text(c.req.param('safeDealerReference'),100),actorUserId:deps.text(c.get('userId'))||null});return c.json({success:true,seller});}catch(e){return fail(c,e,'TRAVEL_SELLER_PERMISSION_FAILED')}});
  app.post('/api/travel/sellers/:safeDealerReference/revoke',async(c:any)=>{try{deps.requireRole(c,'admin');const body=await c.req.json().catch(()=>({}));if(!body||typeof body!=='object'||Array.isArray(body)||Object.keys(body).length)throw new Error('TRAVEL_SELLER_PERMISSION_INPUT_INVALID');const seller=await revokeTravelSellerPermission(c.env.smart_menu_db,{secret:deps.text(c.env.MEMBER_IDENTITY_HMAC_SECRET),workspaceId:deps.workspaceIdOf(c),lineAccountId:deps.text(c.req.query('lineAccountId'),100),safeSellerReference:deps.text(c.req.param('safeDealerReference'),100),actorUserId:deps.text(c.get('userId'))||null});return c.json({success:true,seller});}catch(e){return fail(c,e,'TRAVEL_SELLER_REVOKE_FAILED')}});
  app.get('/api/travel/itineraries',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,itineraries:await listItineraries(c.env.smart_menu_db,deps.workspaceIdOf(c))});}catch(e){return fail(c,e,'TRAVEL_ITINERARY_LIST_FAILED')}});
  app.post('/api/travel/itineraries',async(c:any)=>{try{deps.requireRole(c,'admin');const itinerary=await createItinerary(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),userId:deps.text(c.get('userId'))||null,body:await c.req.json().catch(()=>({}))});return c.json({success:true,itinerary},201);}catch(e){return fail(c,e,'TRAVEL_ITINERARY_CREATE_FAILED')}});
  app.get('/api/travel/itineraries/:safeItineraryReference',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,itinerary:await readItinerary(c.env.smart_menu_db,deps.workspaceIdOf(c),deps.text(c.req.param('safeItineraryReference'),100))});}catch(e){return fail(c,e,'TRAVEL_ITINERARY_READ_FAILED')}});
  app.patch('/api/travel/itineraries/:safeItineraryReference',async(c:any)=>{try{deps.requireRole(c,'admin');return c.json({success:true,itinerary:await updateItinerary(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),reference:deps.text(c.req.param('safeItineraryReference'),100),body:await c.req.json().catch(()=>({}))})});}catch(e){return fail(c,e,'TRAVEL_ITINERARY_UPDATE_FAILED')}});
  for(const [path,action,role] of [['submit-review','submit','admin'],['approve','approve','owner'],['reject','reject','owner'],['archive','archive','admin']] as const){app.post(`/api/travel/itineraries/:safeItineraryReference/${path}`,async(c:any)=>{try{deps.requireRole(c,role);const body=await c.req.json().catch(()=>({}));return c.json({success:true,itinerary:await transitionItinerary(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),reference:deps.text(c.req.param('safeItineraryReference'),100),action,userId:deps.text(c.get('userId'))||null,reviewNote:body.reviewNote})});}catch(e){return fail(c,e,'TRAVEL_ITINERARY_TRANSITION_FAILED')}})}
  app.get('/api/travel/itineraries/:safeItineraryReference/departures',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,departures:await listDepartures(c.env.smart_menu_db,deps.workspaceIdOf(c),deps.text(c.req.param('safeItineraryReference'),100))});}catch(e){return fail(c,e,'TRAVEL_DEPARTURE_LIST_FAILED')}});
  app.post('/api/travel/itineraries/:safeItineraryReference/departures',async(c:any)=>{try{deps.requireRole(c,'admin');const departure=await createDeparture(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),itineraryReference:deps.text(c.req.param('safeItineraryReference'),100),userId:deps.text(c.get('userId'))||null,body:await c.req.json().catch(()=>({}))});return c.json({success:true,departure},201);}catch(e){return fail(c,e,'TRAVEL_DEPARTURE_CREATE_FAILED')}});
  app.get('/api/travel/departures/:safeDepartureReference',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,departure:await readDeparture(c.env.smart_menu_db,deps.workspaceIdOf(c),deps.text(c.req.param('safeDepartureReference'),100))});}catch(e){return fail(c,e,'TRAVEL_DEPARTURE_READ_FAILED')}});
  app.patch('/api/travel/departures/:safeDepartureReference',async(c:any)=>{try{deps.requireRole(c,'admin');return c.json({success:true,departure:await updateDeparture(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),reference:deps.text(c.req.param('safeDepartureReference'),100),userId:deps.text(c.get('userId'))||null,body:await c.req.json().catch(()=>({}))})});}catch(e){return fail(c,e,'TRAVEL_DEPARTURE_UPDATE_FAILED')}});
  for(const action of ['open','close','cancel','archive'] as const){app.post(`/api/travel/departures/:safeDepartureReference/${action}`,async(c:any)=>{try{deps.requireRole(c,'admin');return c.json({success:true,departure:await setDepartureStatus(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c),reference:deps.text(c.req.param('safeDepartureReference'),100),action,userId:deps.text(c.get('userId'))||null})});}catch(e){return fail(c,e,'TRAVEL_DEPARTURE_TRANSITION_FAILED')}})}
  app.get('/api/travel/bookings',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,bookings:await listBookings(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c)})});}catch(e){return fail(c,e,'TRAVEL_BOOKING_LIST_FAILED')}});
  app.get('/api/travel/bookings/:safeBookingReference',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,booking:await readBooking(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c)},deps.text(c.req.param('safeBookingReference'),100))});}catch(e){return fail(c,e,'TRAVEL_BOOKING_READ_FAILED')}});
  app.get('/api/travel/bookings/:safeBookingReference/events',async(c:any)=>{try{deps.requireRole(c,'viewer');return c.json({success:true,events:await listBookingEvents(c.env.smart_menu_db,{workspaceId:deps.workspaceIdOf(c)},deps.text(c.req.param('safeBookingReference'),100))});}catch(e){return fail(c,e,'TRAVEL_BOOKING_EVENTS_READ_FAILED')}});
}
