import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
async function login(page,user='owner-a'){
 await page.goto('/');await page.getByLabel('示範身分').selectOption(user);
 await page.getByRole('button',{name:'進入示範工作台'}).click();
 await expect(page.getByRole('heading',{name:'總覽',exact:true})).toBeVisible();
}
test('desktop core journey: create, advance, convert tenant, request service and message retry',async({page})=>{
 await page.setViewportSize({width:1440,height:1050});await login(page);
 await mkdir('docs/screenshots',{recursive:true});
 await page.screenshot({path:'docs/screenshots/desktop-dashboard.png',fullPage:true});
 await page.getByRole('button',{name:'＋ 建立案件'}).click();
 await page.getByLabel('企業名稱',{exact:true}).fill('驗收企業');
 await page.getByLabel('聯絡人',{exact:true}).fill('驗收窗口');
 await page.getByLabel('下一步',{exact:true}).fill('確認方案');
 await page.getByRole('button',{name:'建立案件',exact:true}).click();
 await expect(page.getByRole('dialog').getByRole('heading',{name:'驗收企業'})).toBeVisible();
 await page.getByLabel('階段',{exact:true}).selectOption('onboarding');await page.getByRole('button',{name:'儲存案件'}).click();
 await expect(page.getByRole('dialog')).not.toBeVisible();
 await page.getByRole('button',{name:/驗收企業/}).click();
 await page.getByLabel('階段',{exact:true}).selectOption('billing');await page.getByRole('button',{name:'儲存案件'}).click();
 await page.getByRole('button',{name:/驗收企業/}).click();
 await page.getByRole('button',{name:'成交轉租戶',exact:true}).click();
 await expect(page.getByRole('heading',{name:'租戶管理',exact:true})).toBeVisible();
 await page.getByRole('button',{name:/驗收企業/}).click();
 await expect(page.getByRole('dialog')).toContainText('數位服務尚未開通');
 await page.getByRole('dialog').locator('.service-grid article').filter({hasText:'品牌官網'}).getByRole('button',{name:'提出需求'}).click();
 await expect(page.getByRole('dialog').locator('.service-grid article').filter({hasText:'品牌官網'})).toContainText('申請中');
 await page.screenshot({path:'docs/screenshots/desktop-tenant.png',fullPage:true});
 await page.getByRole('button',{name:'關閉',exact:true}).click();
 await page.getByRole('button',{name:'工作聊天室',exact:false}).click();
 await page.locator('[data-chat]').filter({hasText:'驗收企業'}).click();
 await page.getByLabel('回覆內容').fill('這是測試訊息，不會送至 LINE。');
 await page.getByLabel('模擬失敗',{exact:true}).check();
 await page.getByRole('button',{name:'模擬回覆',exact:true}).click();
 await expect(page.locator('.messages')).toContainText('模擬發送失敗');
 await page.getByRole('button',{name:'重試模擬'}).click();
 await expect(page.locator('.messages')).toContainText('本地模擬完成，未發送至 LINE');
 await expect(page.locator('.message.out')).toHaveCount(1);
 await expect(page.locator('.message.out')).toContainText('林園長');
 await page.screenshot({path:'docs/screenshots/desktop-chat.png',fullPage:true});
});
test('mobile drawer, search empty state, form error, no horizontal overflow',async({page})=>{
 await page.setViewportSize({width:390,height:844});await login(page);
 await page.screenshot({path:'docs/screenshots/mobile-dashboard.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'開啟導覽'}).click();
 await page.getByRole('button',{name:'成交追蹤',exact:false}).click();
 await page.getByRole('textbox',{name:'搜尋案件'}).fill('不會存在的企業');
 await page.getByRole('button',{name:'搜尋',exact:true}).click();
 await expect(page.getByRole('heading',{name:'目前沒有案件'})).toBeVisible();
 await page.getByRole('button',{name:'＋ 建立案件'}).click();
 await page.getByLabel('企業名稱',{exact:true}).fill('   ');
 await page.getByLabel('聯絡人',{exact:true}).fill('驗收');
 await page.getByRole('button',{name:'建立案件',exact:true}).click();
 await expect(page.getByRole('dialog').getByRole('alert')).toContainText('企業名稱格式不正確');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'docs/screenshots/mobile-form.png',fullPage:true});
 await page.getByRole('button',{name:'關閉',exact:true}).click();
 await page.getByRole('button',{name:'開啟導覽'}).click();
 await page.getByRole('button',{name:'工作聊天室',exact:false}).click();
 await expect(page.locator('#message-body')).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'docs/screenshots/mobile-chat.png',fullPage:true});
});
test('sales UI omits owner risk and historical input is escaped',async({page})=>{
 await login(page,'sales-a1');
 await expect(page.getByRole('button',{name:'聊天室 AI 監控',exact:false})).toHaveCount(0);
 await page.getByRole('button',{name:'工作聊天室',exact:false}).click();
 await page.getByLabel('回覆內容').fill('<img src=x onerror=alert(1)>');
 await page.getByRole('button',{name:'模擬回覆',exact:true}).click();
 await expect(page.locator('.message.out .bubble')).toHaveText('<img src=x onerror=alert(1)>');
 await expect(page.locator('.message.out img')).toHaveCount(0);
});

test('owner integration center desktop/mobile displays honest unconfigured state, staff cannot see it',async({page})=>{
 await page.setViewportSize({width:1440,height:1050});await login(page);
 await page.getByRole('button',{name:'整合中心',exact:false}).click();
 await expect(page.getByRole('heading',{name:'LINE OA 尚未串接'})).toBeVisible();
 await expect(page.getByRole('heading',{name:'目前沒有待分派來客'})).toBeVisible();
 await page.getByRole('button',{name:'處理待收／待送訊息'}).click();
 await expect(page.getByRole('status')).toContainText('外送未啟用');
 await page.screenshot({path:'docs/screenshots/desktop-integrations.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await expect.poll(()=>page.locator('.sidebar').evaluate(el=>el.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
 await page.screenshot({path:'docs/screenshots/mobile-integrations.png',fullPage:true,animations:'disabled'});
 await page.getByRole('button',{name:'登出',exact:true}).click();await login(page,'sales-a1');
 await expect(page.getByRole('button',{name:'整合中心',exact:false})).toHaveCount(0);
});
