import {test,expect} from '@playwright/test';
for(const [name,width,height] of [['desktop',1440,1050],['mobile',390,844]]){
 test(name+' unified LINE workspace: CRM to address tenant, templates and owner-only review',async({page})=>{
  await page.setViewportSize({width,height});await page.goto('http://127.0.0.1:8789/');await page.getByLabel('示範身分').selectOption('owner-a');await page.getByRole('button',{name:'進入示範工作台'}).click();await expect(page.getByRole('heading',{name:'總覽',exact:true})).toBeVisible();
  async function nav(label){if(await page.getByRole('button',{name:'開啟導覽'}).isVisible())await page.getByRole('button',{name:'開啟導覽'}).click();await page.getByRole('button',{name:label,exact:true}).click();}
  await nav('會員 CRM');await expect(page.getByRole('heading',{name:'會員 CRM',exact:true})).toBeVisible();await expect(page.locator('#content')).toContainText('同一份會員資料');
  await page.getByRole('button',{name:'＋ 新增會員',exact:true}).click();await page.getByLabel('聯絡姓名',{exact:true}).fill(name+'虛構會員');await page.getByLabel('企業名稱',{exact:true}).fill(name+'虛構借址企業');await page.getByLabel('電話',{exact:true}).fill('0900000000');await page.getByRole('button',{name:'建立會員',exact:true}).click();
  await expect(page.locator('#lw-person-form')).toBeVisible();await page.getByLabel('標籤（以逗號分隔）').fill('借址，年約');await page.getByRole('button',{name:'保存會員',exact:true}).click();await expect(page.getByLabel('標籤（以逗號分隔）')).toHaveValue('借址，年約');
  await page.getByRole('button',{name:'＋ 建立成交案件',exact:true}).click();await page.getByRole('button',{name:'建立案件並沿用會員',exact:true}).click();await expect(page.locator('#edit-form')).toBeVisible();
  await page.getByLabel('階段',{exact:true}).selectOption('onboarding');await page.getByRole('button',{name:'儲存案件',exact:true}).click();await page.locator('[data-lw-person]').filter({hasText:name+'虛構會員'}).click();await page.getByRole('button',{name:'開啟案件',exact:true}).click();await page.getByLabel('階段',{exact:true}).selectOption('billing');await page.getByRole('button',{name:'儲存案件',exact:true}).click();
  await page.locator('[data-lw-person]').filter({hasText:name+'虛構會員'}).click();await page.getByRole('button',{name:'開啟案件',exact:true}).click();await page.getByRole('button',{name:'成交轉租戶',exact:true}).click();await expect(page.getByRole('heading',{name:'租戶管理',exact:true})).toBeVisible();await expect(page.locator('#content')).toContainText(name+'虛構借址企業');
  await nav('會員 CRM');await expect(page.locator('[data-lw-person]').filter({hasText:name+'虛構會員'})).toContainText('借址租戶');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'docs/screenshots/'+name+'-line-workspace-crm.png',fullPage:true,animations:'disabled',style:'#toast{visibility:hidden!important}'});
  await nav('模板中心');await page.getByRole('button',{name:'＋ 新增模板',exact:true}).click();await page.getByLabel('模板名稱',{exact:true}).fill(name+'借址回覆');await page.getByLabel('草稿狀態').selectOption('ready');await page.getByLabel('回覆內容',{exact:true}).fill(name+'虛構核查TEST-ONLY，請確認借址起迄及郵件代收。');await page.getByRole('button',{name:'保存模板草稿',exact:true}).click();
  await page.locator('.lw-row').filter({hasText:name+'借址回覆'}).getByRole('button',{name:'預覽／套用',exact:true}).click();await page.getByRole('button',{name:'填入聊天室草稿',exact:true}).click();await page.getByLabel('聊天室',{exact:true}).selectOption({label:name+'虛構借址企業 / 管理員 · 林園長'});await page.getByRole('button',{name:'套用至草稿',exact:true}).click();await expect(page.getByLabel('回覆內容',{exact:true})).toHaveValue(name+'虛構核查TEST-ONLY，請確認借址起迄及郵件代收。');await page.getByRole('button',{name:'模擬回覆',exact:true}).click();await expect(page.locator('.messages')).toContainText(name+'虛構核查TEST-ONLY');
  await nav('模板中心');await page.locator('.lw-row').filter({hasText:'借址服務六格圖文選單'}).getByRole('button',{name:'預覽／套用',exact:true}).click();await expect(page.locator('.lw-menu-preview')).toContainText('郵件代收');await expect(page.locator('#modal')).toContainText('尚未上傳圖片或發布到 LINE');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'docs/screenshots/'+name+'-line-workspace-templates.png',fullPage:true,animations:'disabled',style:'#toast{visibility:hidden!important}'});await page.getByRole('button',{name:'關閉',exact:true}).click();
  await nav('LINE OA 工作台');await expect(page.locator('#content')).toContainText('Messaging API 接收 → 會員 CRM → 成交追蹤 → 借址租戶');await page.getByRole('button',{name:'＋ 新增分類',exact:true}).click();await page.getByLabel('客戶詢問用語').fill(name+'年約');await page.getByLabel('需求分類').selectOption('address');await page.getByRole('button',{name:'保存分類',exact:true}).click();await expect(page.locator('#content')).toContainText(name+'年約');await page.screenshot({path:'docs/screenshots/'+name+'-line-workspace-hub.png',fullPage:true,animations:'disabled',style:'#toast{visibility:hidden!important}'});
  await nav('聊天室 AI 監控');await expect(page.locator('#content')).toContainText('AI 模型未啟用');await page.getByRole('button',{name:'＋ 新增規則',exact:true}).click();await page.getByLabel('規則名稱').fill(name+'虛構核查規則');await page.getByLabel('核查用語（每行一個）').fill(name+'虛構核查TEST-ONLY');await page.getByLabel('啟用私有核查規則').check();await page.getByRole('button',{name:'保存私有規則',exact:true}).click();await page.getByRole('button',{name:'掃描工作紀錄',exact:true}).click();await expect(page.locator('.lw-review').filter({hasText:name+'虛構核查規則'})).toContainText('管理員 · 林園長');await page.screenshot({path:'docs/screenshots/'+name+'-line-workspace-monitor.png',fullPage:true,animations:'disabled',style:'#toast{visibility:hidden!important}'});
  await page.locator('.lw-review').filter({hasText:name+'虛構核查規則'}).getByRole('button',{name:'人工核查',exact:true}).click();await page.getByLabel('核查狀態').selectOption('false_positive');await page.getByLabel('核查依據').fill('虛構測試用語，完成流程驗收');await page.getByRole('button',{name:'保存核查紀錄',exact:true}).click();await expect(page.locator('.lw-review').filter({hasText:name+'虛構核查規則'})).toContainText('誤報');
  await page.getByRole('button',{name:'登出',exact:true}).click();await page.getByLabel('示範身分').selectOption('sales-a1');await page.getByRole('button',{name:'進入示範工作台'}).click();await expect(page.getByRole('heading',{name:'總覽',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'聊天室 AI 監控',exact:true})).toHaveCount(0);const risk=await page.request.get('http://127.0.0.1:8789/api/admin/risk');expect(risk.status()).toBe(403);
 });
 test(name+' platform module administration keeps core active and has no operator chat access',async({page})=>{
  await page.setViewportSize({width,height});await page.goto('http://127.0.0.1:8789/');await page.getByLabel('示範身分').selectOption('platform');await page.getByRole('button',{name:'進入示範工作台'}).click();await expect(page.getByRole('heading',{name:'系統總覽',exact:true})).toBeVisible();if(await page.getByRole('button',{name:'開啟導覽'}).isVisible())await page.getByRole('button',{name:'開啟導覽'}).click();await page.getByRole('button',{name:'模組管理',exact:true}).click();await expect(page.locator('#content')).toContainText('借址登記');await expect(page.locator('#content')).toContainText('後續租用');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'docs/screenshots/'+name+'-line-workspace-modules.png',fullPage:true,animations:'disabled',style:'#toast{visibility:hidden!important}'});
  expect((await page.request.get('http://127.0.0.1:8789/api/crm/people')).status()).toBe(403);expect((await page.request.get('http://127.0.0.1:8789/api/admin/risk')).status()).toBe(403);await expect(page.getByRole('button',{name:'工作聊天室',exact:true})).toHaveCount(0);
 });
}
