import {test,expect} from '@playwright/test';
const origin='http://127.0.0.1:8790';
for(const [name,width,height] of [['desktop',1440,1050],['mobile',390,844]]){
 async function login(page){await page.setViewportSize({width,height});await page.goto(origin);await page.getByLabel('示範身分').selectOption('owner-a');await page.getByRole('button',{name:'進入示範工作台'}).click();await expect(page.getByRole('heading',{name:'總覽',exact:true})).toBeVisible();}
 async function nav(page,label){if(await page.getByRole('button',{name:'開啟導覽'}).isVisible())await page.getByRole('button',{name:'開啟導覽'}).click();await page.getByRole('button',{name:label,exact:true}).click();}
 async function capture(page,part){await page.locator('#toast').evaluate(el=>el.classList.remove('show'));expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'docs/screenshots/'+name+'-monitor-'+part+'.png',fullPage:true,animations:'disabled'});}
 test(name+' four monitor tabs, group confirmation and private owner boundaries',async({page})=>{
  await login(page);await nav(page,'聊天室 AI 監控');await expect(page.getByRole('tab',{name:'LINE 聊天室',exact:true})).toHaveAttribute('aria-selected','true');await expect(page.locator('#mc-console')).toContainText('AI 模型未啟用');
  await page.locator('#mc-period').selectOption('30');await expect(page.locator('#mc-period')).toHaveValue('30');await expect(page.getByRole('heading',{name:'實際回覆人員 · 最近 30 天',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'查看對話',exact:true}).first().click();await expect(page.locator('#modal')).toContainText('最近 100 則授權對話');await page.getByRole('button',{name:'關閉',exact:true}).click();await capture(page,'chat');
  await page.getByRole('tab',{name:'用量總覽',exact:true}).click();await expect(page.getByRole('heading',{name:'AI 用量總覽',exact:true})).toBeVisible();await expect(page.locator('#mc-console')).toContainText('本期尚無 AI 用量');await capture(page,'usage');
  await page.getByRole('tab',{name:'AI 呼叫紀錄',exact:true}).click();await expect(page.locator('#mc-console')).toContainText('沒有 AI 呼叫紀錄');await capture(page,'calls');
  await page.getByRole('tab',{name:'群組商機',exact:true}).click();await expect(page.locator('#mc-console')).toContainText('借址需求測試群組（虛構）');await page.getByRole('button',{name:'設定群組',exact:true}).click();await page.getByLabel('啟用此群組觀測').check();await page.getByLabel('啟停依據').fill('虛構驗收群組，僅本機');await page.getByRole('button',{name:'保存群組設定',exact:true}).click();
  await page.getByRole('button',{name:'新增群組規則',exact:true}).click();await page.getByLabel('群組規則名稱').fill(name+'虛構借址規則');await page.getByLabel('群組關鍵字（每行一個）').fill('借址');await page.getByLabel('情境用語（每行一個）').fill('年約');await page.getByLabel('啟用群組規則',{exact:true}).check();await page.getByRole('button',{name:'保存群組規則',exact:true}).click();await page.getByRole('button',{name:'掃描群組紀錄',exact:true}).click();
  const row=page.locator('.lw-row').filter({hasText:name+'虛構借址規則'}).filter({has:page.getByRole('button',{name:'查看／處理商機',exact:true})});await expect(row).toContainText('TEST-ONLY');await capture(page,'groups');await row.getByRole('button',{name:'查看／處理商機',exact:true}).click();await page.getByLabel('商機狀態').selectOption('accepted');await page.getByLabel('連結 CRM 會員').selectOption('crm-contact-contact-b1');await page.getByLabel('確認依據').fill('虛構需求確認，不建立成交');await page.getByRole('button',{name:'保存商機確認',exact:true}).click();await expect(row).toContainText('確認商機');await expect(row.getByRole('button',{name:'開啟 CRM 會員',exact:true})).toBeVisible();
  expect((await page.request.get(origin+'/api/admin/monitor?tab=usage')).status()).toBe(200);await page.getByRole('button',{name:'登出',exact:true}).click();await page.getByLabel('示範身分').selectOption('sales-a1');await page.getByRole('button',{name:'進入示範工作台'}).click();await expect(page.getByRole('heading',{name:'總覽',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'聊天室 AI 監控',exact:true})).toHaveCount(0);expect((await page.request.get(origin+'/api/admin/monitor?tab=groups')).status()).toBe(403);
 });
 test(name+' 30 second refresh stops for a modal and on page exit',async({page})=>{
  await login(page);await nav(page,'聊天室 AI 監控');await expect(page.locator('#mc-console')).toBeVisible();await page.clock.install();let requests=0;page.on('request',r=>{if(new URL(r.url()).pathname==='/api/admin/monitor')requests++;});
  await page.getByLabel('每 30 秒更新',{exact:true}).check();const response=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/admin/monitor');await page.clock.fastForward(30000);await response;await expect(page.locator('#mc-console')).toBeVisible();const after=requests;expect(after).toBe(1);const search=page.getByLabel('搜尋企業／訊息／回覆人員',{exact:true});await search.fill('尚未送出的篩選');await page.clock.fastForward(60000);expect(requests).toBe(after);await search.fill('');await search.evaluate(el=>el.blur());
  await page.getByRole('button',{name:'查看對話',exact:true}).first().click();await expect(page.locator('#modal')).toBeVisible();await page.clock.fastForward(60000);expect(requests).toBe(after);await page.getByRole('button',{name:'關閉',exact:true}).click();await nav(page,'會員 CRM');await expect(page.getByRole('heading',{name:'會員 CRM',exact:true})).toBeVisible();await page.clock.fastForward(60000);expect(requests).toBe(after);
 });
}
