import {test,expect} from '@playwright/test';
async function openOperations(page,user='owner-a'){
 await page.goto('/');await page.getByLabel('示範身分').selectOption(user);
 await page.getByRole('button',{name:'進入示範工作台'}).click();
 await expect(page.getByRole('heading',{name:'總覽',exact:true})).toBeVisible();
 if(await page.getByRole('button',{name:'開啟導覽'}).isVisible())await page.getByRole('button',{name:'開啟導覽'}).click();
 await page.getByRole('button',{name:'租戶管理',exact:false}).click();
 await page.getByRole('button',{name:'租戶維運台 →',exact:true}).click();
 await page.getByLabel('目前租戶').selectOption('b4');
 await expect(page.getByRole('heading',{name:'租戶維運',exact:true})).toBeVisible();
 await expect(page.getByRole('heading',{name:'服務接續'})).toBeVisible();
}
test('desktop tenant operations: paid subscription, mail handoff, operator history',async({page})=>{
 await page.setViewportSize({width:1440,height:1050});await openOperations(page);
 await page.screenshot({path:'docs/screenshots/desktop-operations.png',fullPage:true});
 await page.getByRole('button',{name:'數位訂閱',exact:true}).click();
 await page.getByRole('button',{name:'＋ 新增訂閱'}).click();
 await page.getByLabel('數位服務方案').selectOption('plan-crm');
 await page.getByRole('button',{name:'儲存紀錄',exact:true}).click();
 await expect(page.getByRole('dialog')).not.toBeVisible();
 await page.getByRole('button',{name:'應收與收退款',exact:true}).click();
 await page.getByRole('button',{name:'＋ 建立應收'}).click();
 await page.getByLabel('帳款來源').selectOption({label:'數位訂閱 · CRM 服務方案（示範） · NT$ 800'});
 await page.getByRole('button',{name:'儲存紀錄',exact:true}).click();
 await expect(page.getByRole('dialog')).not.toBeVisible();
 const bill=page.locator('.ops-card').filter({hasText:'數位訂閱款'}).filter({hasText:'NT$ 800'});
 await bill.getByRole('button',{name:'記錄收款／退款'}).click();
 await page.getByLabel('人工核對依據').fill('UI 驗收：虛構收款依據');
 await page.getByRole('button',{name:'儲存紀錄',exact:true}).click();
 await expect(bill).toContainText('已核對收足');
 await bill.getByRole('button',{name:'查看收退款歷程'}).click();
 await expect(page.getByRole('dialog')).toContainText('林園長');
 await expect(page.getByRole('dialog')).toContainText('UI 驗收：虛構收款依據');
 await page.getByRole('button',{name:'關閉',exact:true}).click();
 await page.screenshot({path:'docs/screenshots/desktop-billing.png',fullPage:true});
 await page.getByRole('button',{name:'數位訂閱',exact:true}).click();
 const sub=page.locator('.ops-card').filter({hasText:'CRM 服務方案（示範）'});
 await sub.getByRole('button',{name:'確認訂閱'}).click();
 await page.getByLabel('處理原因').fill('虛構收款完成，僅確認訂閱資格');
 await page.getByRole('button',{name:'確認變更'}).click();
 await expect(sub).toContainText('訂閱資格符合');
 await expect(sub).toContainText('功能未開通');
 await page.screenshot({path:'docs/screenshots/desktop-subscriptions.png',fullPage:true});
 await page.getByRole('button',{name:'信件包裹',exact:true}).click();
 await page.getByRole('button',{name:'標記待領'}).click();
 await page.getByRole('button',{name:'確認變更'}).click();
 await page.getByRole('button',{name:'確認領取'}).click();
 await page.getByLabel('交付依據（領取人／轉寄單號／退回原因）').fill('UI 示範領取人核對');
 await page.getByRole('button',{name:'確認變更'}).click();
 await expect(page.locator('.ops-card')).toContainText('UI 示範領取人核對');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('mobile assigned service: no financial UI, maintenance completion and no overflow',async({page})=>{
 await page.setViewportSize({width:390,height:844});await openOperations(page,'service-a');
 await expect(page.getByRole('button',{name:'應收與收退款',exact:true})).toHaveCount(0);
 await expect(page.locator('#ops-panel')).not.toContainText('NT$');
 await page.screenshot({path:'docs/screenshots/mobile-operations.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'維運需求',exact:true}).click();
 await page.getByRole('button',{name:'開始處理'}).click();
 await page.getByRole('button',{name:'確認變更'}).click();
 await page.getByRole('button',{name:'標記解決'}).click();
 await page.getByLabel('處理說明').fill('驗收：品牌資料已核對');
 await page.getByRole('button',{name:'確認變更'}).click();
 await page.getByRole('button',{name:'確認結案'}).click();
 await page.getByLabel('處理說明').fill('驗收：租戶已確認');
 await page.getByRole('button',{name:'確認變更'}).click();
 await expect(page.locator('.ops-card')).toContainText('驗收：租戶已確認');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'docs/screenshots/mobile-maintenance.png',fullPage:true});
});
