import type { GuideContext } from '../types.ts';
import type { RecommendationCandidate, RecommendationRule } from './types.ts';

export const BEHAVIOR_RECOMMENDATION_THRESHOLDS = { minimumImpressions: 100, maximumFreshnessDays: 3, minimumMappedAreaRatio: .8, lowUsageShare: .03, zeroUsageShare: 0, concentrationShare: .75, switchLowShare: .05, switchHighShare: .25, decliningClicks: .4, stableImpressions: .15, ctrDecline: .3, lowEngagementShare: .05, uriUsageDominanceShare: .8, postbackPositiveShare: .2 } as const;
const project = (context: GuideContext, code: string, fields: Omit<RecommendationCandidate, 'stableKey' | 'entityType' | 'entityId'>): RecommendationCandidate => ({ ...fields, stableKey: `${context.project.id}:${code}`, entityType: 'project', entityId: context.project.id });
const evidence = (context: GuideContext) => [{ key: 'periodFrom', value: context.behavior!.period.from }, { key: 'periodTo', value: context.behavior!.period.to }, { key: 'periodDays', value: context.behavior!.period.days }, { key: 'impressions', value: context.behavior!.project.impressions }, { key: 'clicks', value: context.behavior!.project.clicks }, { key: 'metricsThrough', value: context.behavior!.dataQuality.metricsThrough || '' }];
const ready = (context: GuideContext) => Boolean(context.behavior?.dataQuality.sufficient);
const area = (context: GuideContext, id: string) => context.behavior!.areas.find(item => item.id === id)!;

const R101: RecommendationRule = { code: 'R101', order: 101, evaluate(context) { if (!ready(context)) return []; const total = context.behavior!.project.clicks; return context.behavior!.areas.filter(item => item.clicks > 0 && item.clicks / total <= BEHAVIOR_RECOMMENDATION_THRESHOLDS.lowUsageShare).map(item => ({ stableKey: item.id, entityType: 'project_area', entityId: item.id, category: 'navigation', priority: 'low', title: 'Low usage menu area', message: 'This area receives a very small share of mapped Rich Menu clicks in the selected period.', reason: 'Review its label, placement, or necessity using the cached aggregate data.', evidence: [...evidence(context), { key: 'areaLabel', value: item.label }, { key: 'areaClicks', value: item.clicks }, { key: 'shareOfClicks', value: item.clicks / total }], suggestedAction: { type: 'navigate', target: 'intelligence' }, source: 'behavior', tone: 'improvement' })); } };
const R102: RecommendationRule = { code: 'R102', order: 102, evaluate(context) { if (!ready(context)) return []; return context.behavior!.areas.filter(item => item.clicks === 0).map(item => ({ stableKey: item.id, entityType: 'project_area', entityId: item.id, category: 'navigation', priority: 'medium', title: 'Zero click menu area', message: 'This mapped area has no cached clicks for the selected period.', reason: 'Check visibility, wording, and user intent before changing the menu.', evidence: [...evidence(context), { key: 'areaLabel', value: item.label }, { key: 'areaClicks', value: 0 }], suggestedAction: { type: 'navigate', target: 'intelligence' }, source: 'behavior', tone: 'improvement' })); } };
const R103: RecommendationRule = { code: 'R103', order: 103, evaluate(context) { if (!ready(context) || context.behavior!.areas.length < 5) return []; const sorted = [...context.behavior!.areas].sort((a,b)=>b.clicks-a.clicks); const share=(sorted[0].clicks+sorted[1].clicks)/context.behavior!.project.clicks; return share >= .75 ? [project(context,'R103',{ category:'structure',priority:'medium',title:'Clicks are concentrated in two areas',message:'The top two areas account for most mapped clicks.',reason:'Consider whether the remaining navigation can be simplified.',evidence:[...evidence(context),{key:'combinedShare',value:share}],suggestedAction:{type:'navigate',target:'intelligence'},source:'behavior',tone:'improvement'})] : []; } };
const R105: RecommendationRule = { code:'R105',order:105,evaluate(context){ if(!ready(context))return[];return context.behavior!.areas.filter(item=>item.actionType==='richmenuswitch'&&item.clicks/context.behavior!.project.clicks<=.05).map(item=>({stableKey:item.id,entityType:'project_area',entityId:item.id,category:'navigation',priority:'low',title:'Low usage page switch',message:'This Rich Menu switch receives limited use.',reason:'Review whether the destination is discoverable.',evidence:[...evidence(context),{key:'areaLabel',value:item.label},{key:'shareOfClicks',value:item.clicks/context.behavior!.project.clicks}],suggestedAction:{type:'navigate',target:'intelligence'},source:'behavior',tone:'improvement'}));}};
const R106: RecommendationRule = { code:'R106',order:106,evaluate(context){ if(!ready(context))return[];return context.behavior!.areas.filter(item=>item.actionType==='richmenuswitch'&&item.clicks/context.behavior!.project.clicks>=.25).map(item=>({stableKey:item.id,entityType:'project_area',entityId:item.id,category:'navigation',priority:'low',title:'Popular page switch',message:'This page switch is a positive navigation signal.',reason:'Keep its destination clear and reliable.',evidence:[...evidence(context),{key:'areaLabel',value:item.label},{key:'shareOfClicks',value:item.clicks/context.behavior!.project.clicks}],suggestedAction:{type:'navigate',target:'intelligence'},source:'behavior',tone:'positive'}));}};
const R109: RecommendationRule = { code:'R109',order:109,evaluate(context){if(!ready(context)||context.behavior!.daily.length<14)return[];const days=context.behavior!.daily;const recent=days.slice(-7),previous=days.slice(-14,-7);const sum=(xs:any[],k:string)=>xs.reduce((n,x)=>n+Number(x[k]||0),0);const rc=sum(recent,'clicks'),pc=sum(previous,'clicks'),ri=sum(recent,'impressions'),pi=sum(previous,'impressions');return pc>0&&rc/pc<=.6&&ri/pi>=.85?[project(context,'R109',{category:'engagement',priority:'medium',title:'Recent clicks declined',message:'The latest seven days have materially fewer clicks while impressions remain comparable.',reason:'Review changes in menu content or audience behavior.',evidence:[...evidence(context),{key:'recentClicks',value:rc},{key:'previousClicks',value:pc}],suggestedAction:{type:'navigate',target:'intelligence'},source:'behavior',tone:'improvement'})]:[];}};
const R110: RecommendationRule = { code:'R110',order:110,evaluate(context){if(!ready(context)||context.behavior!.daily.length<14)return[];const d=context.behavior!.daily,sum=(xs:any[],k:string)=>xs.reduce((n,x)=>n+Number(x[k]||0),0),r=d.slice(-7),p=d.slice(-14,-7),ri=sum(r,'impressions'),pi=sum(p,'impressions'),rctr=sum(r,'clicks')/ri,pctr=sum(p,'clicks')/pi;return pi&&ri&&Math.abs(ri/pi-1)<=.15&&pctr&&rctr/pctr<=.7?[project(context,'R110',{category:'engagement',priority:'high',title:'CTR declined with stable impressions',message:'Impressions are stable but click-through rate fell.',reason:'This can indicate the menu is less compelling to the same audience.',evidence:[...evidence(context),{key:'recentCtr',value:rctr},{key:'previousCtr',value:pctr}],suggestedAction:{type:'navigate',target:'intelligence'},source:'behavior',tone:'improvement'})]:[];}};
const R104: RecommendationRule={code:'R104',order:104,evaluate(context){if(!ready(context)||context.behavior!.areas.length<6)return[];const total=context.behavior!.project.clicks;const low=context.behavior!.areas.filter((x:any)=>x.clicks/total<=.05);return low.length/context.behavior!.areas.length>=.5?[project(context,'R104',{category:'structure',priority:'medium',title:'Many areas have low engagement',message:'At least half of menu areas receive little mapped usage.',reason:'Consider simplifying navigation.',evidence:[...evidence(context),{key:'areaCount',value:context.behavior!.areas.length},{key:'lowEngagementAreaCount',value:low.length},{key:'lowEngagementRatio',value:low.length/context.behavior!.areas.length}],suggestedAction:{type:'navigate',target:'intelligence'},source:'behavior',tone:'improvement',relatedRuleCodes:['R003']})]:[];}};
const R107: RecommendationRule={code:'R107',order:107,evaluate(context){if(!ready(context))return[];const a=context.behavior!.areas,t=context.behavior!.project.clicks,u=a.filter((x:any)=>x.actionType==='uri').reduce((n:number,x:any)=>n+x.clicks,0);return t&&u/t>=.8&&u<t?[project(context,'R107',{category:'engagement',priority:'medium',title:'URI dominates real usage',message:'Mapped URI actions account for most clicks.',reason:'Consider adding interactive LINE actions where appropriate.',evidence:[...evidence(context),{key:'uriClicks',value:u},{key:'totalClicks',value:t},{key:'uriShare',value:u/t}],suggestedAction:{type:'navigate',target:'intelligence'},source:'behavior',tone:'improvement',relatedRuleCodes:['R001','R002']})]:[];}};
const R108: RecommendationRule={code:'R108',order:108,evaluate(context){if(!ready(context))return[];const a=context.behavior!.areas,t=context.behavior!.project.clicks,p=a.filter((x:any)=>x.actionType==='postback').reduce((n:number,x:any)=>n+x.clicks,0);return t&&p/t>=.2?[project(context,'R108',{category:'engagement',priority:'low',title:'Postback is a strong interaction signal',message:'Mapped Postback actions have meaningful click share.',reason:'Keep this interaction path clear and reliable.',evidence:[...evidence(context),{key:'postbackClicks',value:p},{key:'postbackShare',value:p/t}],suggestedAction:{type:'navigate',target:'intelligence'},source:'behavior',tone:'positive'})]:[];}};
export const BEHAVIOR_RECOMMENDATION_RULES = [R101,R102,R103,R104,R105,R106,R107,R108,R109,R110];

