import React,{useEffect,useState} from 'react';
import RichMenuChatOperators from './RichMenuChatOperators';
export default function MenuChatWorkspace({request,onBack}){
 const [connection,setConnection]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[liffId,setLiffId]=useState('');
 const load=async()=>{const r=await request('/api/rich-menu-chat/connection');const d=await r.json();if(!r.ok)throw Error(d.error);setConnection(d);setLiffId(d.liffId||'');};
 useEffect(()=>{load().catch(e=>setError(e.message));},[request]);
 async function toggle(){setBusy(true);setError('');try{const r=await request('/api/rich-menu-chat/connection',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:!connection.enabled})});const d=await r.json();if(!r.ok)throw Error(d.error);await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="space-y-5"><button className="border rounded px-4 py-2" onClick={onBack}>返回工作區</button><h1 className="text-2xl font-bold">聊天室修改選單</h1><p>管理員私訊此工作區官方帳號「修改選單」，選擇已發布選單後傳送 JPG／PNG 原圖。保留選單名稱、按鈕功能與首頁；結果顯示於下方紀錄。</p><div className="rounded border bg-white p-4 space-y-3"><h2 className="font-bold">LINE 接收與選單發布</h2><p>先在「LINE OA 設定」保存 Messaging API Secret 與 Token，再啟用此流程並將下方網址填入 LINE Developers 的 Webhook URL、開啟 Use webhook。此網址專門接收修改選單指令。</p>{connection&&<><p>狀態：{connection.enabled?'已啟用':'未啟用'}{connection.demo?'（展示環境）':''}</p>{connection.webhookUrl&&<label className="block">Webhook URL<input readOnly className="border rounded p-3 block w-full mt-2" value={connection.webhookUrl}/></label>}<button disabled={busy||connection.demo||!connection.credentialsReady} className="rounded bg-green-700 text-white px-4 py-2 disabled:opacity-50" onClick={toggle}>{busy?'儲存中…':connection.enabled?'停用聊天室接收':'驗證 Token 並啟用'}</button>{!connection.credentialsReady&&<p>尚缺此工作區的 Messaging API 憑證。</p>}<form className="space-y-3 border-t pt-4" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const r=await request('/api/rich-menu-chat/liff',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({liffId,linkageConfirmed:true})});const d=await r.json();if(!r.ok)throw Error(d.error);await load();setError('');}catch(e){setError(e.message);}finally{setBusy(false);}}}><h2 className="font-bold">原圖上傳與按鈕範圍調整</h2><p>在此工作區 LINE Login Channel 建立 LIFF（Scope 勾選 profile），Endpoint URL 使用下方網址。保存 LIFF ID 後，「上傳圖片」會開啟上傳頁；完成結果直接顯示於該頁。</p><label className="block">LIFF Endpoint URL<input readOnly className="border rounded p-3 block w-full mt-2" value={connection.liffEndpoint}/></label><label className="block">LIFF ID<input className="border rounded p-3 block w-full mt-2" value={liffId} onChange={e=>setLiffId(e.target.value)} maxLength={100}/></label><label className="block"><input type="checkbox" required className="mr-2"/>已確認 LINE Login 與官方帳號屬於同一 Provider</label><button className="border rounded px-4 py-2" disabled={busy||!connection.enabled||connection.demo}>保存 LIFF 上傳設定</button></form></>}{error&&<p role="alert" className="text-red-700">{error}</p>}</div><RichMenuChatOperators request={request} endpoint="/api/rich-menu-chat/operators"/><button className="border rounded px-4 py-2" disabled={busy||!connection?.enabled} onClick={async()=>{try{const r=await request('/api/rich-menu-chat/refresh',{method:'POST'});const d=await r.json();if(!r.ok)throw Error(d.error);setError('既有選單連結更新狀態：'+d.result.phase);}catch(e){setError(e.message);}}}>核對既有會員選單連結更新</button><button className="border rounded px-4 py-2 ml-3" onClick={onBack}>返回工作區</button></section>;
}
