import React,{useEffect,useState} from 'react';
export function RuntimeDashboard({request,onNavigate}){
 const[data,setData]=useState(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;request('/api/startup-park/summary').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);if(active)setData(d);}).catch(e=>active&&setError(e.message));return()=>{active=false;};},[request]);
 return <section className="space-y-5"><h1 className="text-2xl font-bold">企業數位營運工作區</h1><p>借址服務與企業數位管理共用已驗證身分，資料按工作區隔離。</p><div className="rounded border border-amber-300 bg-amber-50 p-4 text-amber-950">LINE 外送、AI 模型、商城金流尚未串接。企業租用費率與分潤待議定；本頁提供內部管理與草稿。</div>{error&&<p role="alert">{error}</p>}{!data&&!error&&<p>正在讀取工作區資料…</p>}{data&&<div className="rounded border bg-white divide-y">{[['圖文選單專案',data.projects,'projects'],['會員與客戶',data.crm_people,'crm'],['商城商品',data.products,'commerce'],['商城訂單',data.orders,'commerce'],['素材',data.assets,'sites']].map(([label,count,view])=><button key={label} className="w-full flex items-center justify-between p-4 text-left" onClick={()=>onNavigate(view)}><strong>{label}</strong><span>{count} 筆 →</span></button>)}</div>}<div className="rounded border bg-white p-4 space-y-2"><h2 className="font-bold text-xl">借址服務 CRM</h2><p>成交、合約起迄、收款、郵件與續約保留原企業和操作人員歷程。</p><a href="/" className="inline-block text-blue-800 underline">開啟借址主工作台 →</a></div></section>;
}
export function RuntimeSites({request}){
 const[items,setItems]=useState([]),[active,setActive]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState('');
 const load=async()=>{const r=await request('/api/site-drafts');const d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.items||[]);};
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function save(e){e.preventDefault();setBusy(true);setError('');try{
  const form=new FormData(e.currentTarget),assets=[];
  for(const file of form.getAll('materials'))if(file.size){const upload=new FormData();upload.set('image',file);upload.set('purpose','travel-promotion-dm');const r=await request('/api/templates/upload-image',{method:'POST',body:upload});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error);assets.push(d.asset.id);}
  const r=await request('/api/site-drafts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:form.get('name'),description:form.get('description'),social_urls:String(form.get('social_urls')||'').split('\n').filter(Boolean),asset_ids:assets})});
  const d=await r.json();if(!r.ok)throw new Error(d.error);await load();setActive(d.item);setPreview(d.preview);e.target.reset();
 }catch(e){setError(e.message);}finally{setBusy(false);}}
 async function open(id){try{const r=await request('/api/site-drafts/'+id);const d=await r.json();if(!r.ok)throw new Error(d.error);setActive(d.item);setPreview(d.preview);}catch(e){setError(e.message);}}
 return <section className="space-y-5"><h1 className="font-bold text-2xl">官網素材與草稿</h1><p>上傳名片、DM 和社群網址，生成可檢視的網站草稿。圖片辨識與 AI 文案尚未串接，請填入已確認的公司介紹；社群網址只保留連結。</p><form className="rounded border bg-white p-4 space-y-4" onSubmit={save}><label className="block font-semibold">網站名稱<input name="name" required maxLength={100} className="block w-full border rounded p-3 text-gray-900 mt-2"/></label><label className="block font-semibold">已確認的公司介紹<textarea name="description" maxLength={4000} rows={4} className="block w-full border rounded p-3 text-gray-900 mt-2"/></label><label className="block font-semibold">社群網址（每行一個 https 網址）<textarea name="social_urls" rows={3} className="block w-full border rounded p-3 text-gray-900 mt-2"/></label><label className="block font-semibold">名片／DM（PNG、JPG，每張最多 1 MB）<input name="materials" type="file" accept="image/png,image/jpeg" multiple className="block mt-2"/></label><button className="rounded bg-green-600 px-5 py-3 text-white font-semibold" disabled={busy}>{busy?'保存素材與生成草稿…':'生成網站草稿'}</button>{error&&<p role="alert" className="text-red-800">{error}</p>}</form><h2 className="font-bold text-xl">已保存草稿</h2><ul className="rounded border bg-white divide-y">{items.length?items.map(d=><li key={d.id} className="flex items-center justify-between p-4 gap-4"><div><strong>{d.name}</strong><p>第 {d.version} 版 · {d.status==='confirmed'?'已確認':'草稿'} · {d.asset_count} 份素材</p></div><button className="text-blue-800 underline" onClick={()=>open(d.id)}>查看</button></li>):<li className="p-4">尚無草稿。</li>}</ul>{active&&<section className="rounded border bg-white p-4 space-y-4"><h2 className="font-bold text-xl">{active.name} · 私有預覽</h2><div dangerouslySetInnerHTML={{__html:preview}}/><p>正式官網發布與網域租用尚未啟用，費率及分潤待議定。</p>{active.status==='draft'&&<button className="rounded border px-4 py-2" onClick={async()=>{try{const r=await request('/api/site-drafts/'+active.id+'/confirm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:active.version})});const d=await r.json();if(!r.ok)throw new Error(d.error);setActive(d.item);await load();}catch(e){setError(e.message);}}}>確認第 {active.version} 版內容</button>}</section>}</section>;
}

export function BorrowedCompanies({request}){
 const[data,setData]=useState(null),[query,setQuery]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let live=true;request('/api/startup-park/borrowed-enterprises?q='+encodeURIComponent(query)).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);if(live)setData(d);}).catch(e=>live&&setError(e.message));return()=>{live=false;};},[request,query]);
 const terms={annual:'年約',monthly:'月約',two_year:'兩年約',custom:'自訂期間'};
 const cycles={once:'一次繳清',monthly:'每月繳付',quarterly:'每季繳付',half_yearly:'每半年繳付',yearly:'每年繳付',custom:'依個別約定'};
 if(error)return <section className="rounded border bg-white p-4"><h2 className="font-bold text-xl">借址企業</h2><p>{error}</p></section>;
 return <details className="rounded border bg-white p-4 mb-5" open><summary className="font-bold text-xl text-blue-900">借址企業 · {data?.total??'讀取中'}</summary><label className="block mt-4">搜尋借址企業<input className="block border rounded p-3 mt-2 w-full" value={query} onChange={e=>setQuery(e.target.value)} /></label><ul className="divide-y mt-4">{data?.items?.length?data.items.map(b=><li className="py-4 flex flex-wrap gap-3 items-center justify-between" key={b.id}><div><strong>{b.name}</strong><p>{b.location_name||'登記據點待補'} · 承辦：{b.service_owner_name||'待指派'}</p><p>{b.service_starts_on&&b.service_ends_on?b.service_starts_on+' ～ '+b.service_ends_on:'服務起迄待補'} · {terms[b.term_kind]||'合約類型待補'} · {cycles[b.payment_cycle]||'付款週期待補'}</p></div><a className="text-blue-800 underline" href="/">管理合約、郵件與維運 →</a></li>):<li className="py-4">尚無借址租戶。</li>}</ul>{data?.has_more&&<p>請至借址主工作台查看其餘租戶。</p>}<p className="mt-3">以下為此工作區的會員與數位客戶；企業自己的顧客資料需另行授權。</p></details>;
}
