type Row=Record<string,any>;
type Dependencies={api:(path:string,method?:string,data?:Row)=>Promise<any>;e:(v:unknown)=>string;badge:(v:string,tone?:string)=>string;date:(v:string)=>string;modal:(html:string)=>void;toast:(s:string)=>void;me:()=>Row;staff:()=>Row[];refresh:()=>Promise<void>;openCase:(id:string)=>Promise<void>;compose:(id:string,body:string)=>Promise<void>;followUTC:(s:string)=>string};
export function lineWorkspace(d:Dependencies){
 const{e,badge}=d;let snapshot:Row={},current='';let cursors:(string|null)[]=[null],index=0;let q='',status='active',tag='',person:Row;let template:Row;
 const destinations:Row={address:'借址登記',renewal:'合約續租',mail:'郵件代收',billing:'帳務查詢',support:'服務申請'};
 const reviewNames:Row={pending:'待確認',reviewing:'處理中',normal:'正常結案',false_positive:'誤報',confirmed:'確認異常'};
 const pages:Row={crm:'/crm/people',templates:'/templates',modules:'/workspace/modules','line-hub':'/line/hub',risk:'/admin/risk','system-modules':'/platform/modules','system-templates':'/platform/templates'};
 const mine=()=>d.me().role==='operator_owner';const seller=()=>['operator_owner','operator_sales'].includes(d.me().role);
 const panel=(title:string,body:string,action='')=>'<section class="panel lw-panel"><div class="panel-heading"><h2>'+e(title)+'</h2>'+action+'</div>'+body+'</section>';
 const input=(name:string,label:string,value='',attrs='')=>'<label>'+e(label)+'<input name="'+name+'" value="'+e(value)+'" '+attrs+'></label>';
 const area=(name:string,label:string,value='',attrs='')=>'<label>'+e(label)+'<textarea name="'+name+'" '+attrs+'>'+e(value)+'</textarea></label>';
 const error='<p class="form-error" role="alert"></p>';
 const search=()=>'<form id="lw-search" class="lw-search">'+input('q',current==='crm'?'搜尋會員／公司／電話':'搜尋模板',q,'maxlength="100"')+(current==='crm'?'<label>會員狀態<select name="status"><option value="active" '+(status==='active'?'selected':'')+'>使用中</option><option value="archived" '+(status==='archived'?'selected':'')+'>已封存</option><option value="all" '+(status==='all'?'selected':'')+'>全部狀態</option></select></label>'+input('tag','標籤篩選',tag,'maxlength="40"'):'')+'<button type="submit">搜尋</button>'+error+'</form>';
 const nothing=(title:string,detail:string)=>'<div class="lw-empty"><b>'+e(title)+'</b><p>'+e(detail)+'</p></div>';
 const staffOptions=(value:string)=>d.staff().filter(s=>s.active&&['operator_owner','operator_sales'].includes(s.role)).map(s=>'<option value="'+e(s.id)+'" '+(value===s.id?'selected':'')+'>'+e(s.name)+'</option>').join('');
 function reset(page:string){if(page==='crm'||page==='templates'||page==='system-templates'){q='';status='active';tag='';cursors=[null];index=0;}}
 function path(page:string){let p=pages[page];if(!p)return '';if(page==='crm')p+='?limit=50&q='+encodeURIComponent(q)+'&status='+encodeURIComponent(status)+'&tag='+encodeURIComponent(tag)+(cursors[index]?'&cursor='+encodeURIComponent(cursors[index]!):'');if(page==='templates'||page==='system-templates')p+='?q='+encodeURIComponent(q);return p;}
 function render(page:string,data:Row){current=page;snapshot=data;
  if(page==='crm')return panel('會員名單',search()+'<p>同一份會員資料，沿用到成交案件、借址租戶與收件服務；LINE 身分依 OA／Provider 分開。</p><div class="lw-list">'+(data.items.length?data.items.map((p:Row)=>'<button class="lw-person" data-lw-person="'+e(p.id)+'"><span class="company-icon">'+e(p.name.slice(0,1))+'</span><span><b>'+e(p.name)+'</b><small>'+e(p.business_name||p.company_name||'企業待補')+' · '+e(p.phone||'電話待補')+'</small><span class="lw-tags">'+p.tags.map((t:string)=>badge(t)).join('')+'</span></span><span>'+badge(p.is_tenant?'借址租戶':p.business_id?'已連結案件':'潛在客戶',p.is_tenant?'green':'')+badge(p.line_count?'LINE 身分已接收':'人工聯絡資料',p.line_count?'green':'')+'</span><span aria-hidden="true">查看 ›</span></button>').join(''):nothing('尚無會員','可以手動建檔；業者 OA 的已驗簽來客也會自動建立 CRM 身分。'))+'</div><div class="list-pagination"><span>共 '+e(data.total)+' 位 · 第 '+(index+1)+' 頁</span><div><button data-lw-pager="previous" '+(!index?'disabled':'')+'>上一頁</button><button data-lw-pager="next" '+(!data.next_cursor?'disabled':'')+'>下一頁</button></div></div>',seller()?'<button class="primary" data-lw-new-person="1">＋ 新增會員</button>':'');
  if(page==='templates'||page==='system-templates')return panel(page==='system-templates'?'平台共用模板':'模板中心',search()+'<p>'+e(data.note)+'</p><div class="lw-list">'+data.items.map((t:Row)=>'<article class="lw-row"><div><h3>'+e(t.name)+'</h3><p>'+e(t.kind==='message'?'回覆文字':'六格圖文選單配置')+' · '+e(t.builtin?'內建參考':t.operator_id?'業者私有':'平台共用')+'</p></div><div>'+badge(t.status==='ready'?'可套用草稿':'草稿',t.status==='ready'?'green':'')+'<button data-lw-template="'+e(t.id)+'">預覽／套用</button></div></article>').join('')+'</div>',mine()||page==='system-templates'?'<button class="primary" data-lw-new-template="1">＋ 新增模板</button>':'');
  if(page==='modules')return panel('工作區模組', '<p>這裡是借址業者使用的平台功能；租戶加購官網、商城或自有 OA 是另一份數位租用合約。價格與分潤仍待議定。</p>'+modules(data.modules)+'<p>業者僅查看權益，啟用與停用由系統總管理員管理。模組啟用不代表 LINE 已接線或 AI 模型已啟用。</p>');
  if(page==='system-modules')return '<div class="lw-system-modules">'+data.operators.map((o:Row)=>panel(o.name,modules(o.modules,String(o.id)))).join('')+'</div>';
  if(page==='line-hub')return hub(data);
  if(page==='risk')return monitor(data);return '';
 }
 function modules(rows:Row[],operator=''){return '<div class="lw-list">'+rows.map(m=>'<article class="lw-row"><div><h3>'+e(m.name)+'</h3><p>'+e(m.description)+'</p><p>平台費／分潤：待議定</p></div><div>'+badge(m.future?'後續租用':m.enabled?'可使用':'已停用',m.future?'amber':m.enabled?'green':'')+(operator&&!m.core&&!m.future?'<button data-lw-module="'+e(m.key)+'" data-operator="'+e(operator)+'" data-version="'+m.version+'" data-enabled="'+(m.enabled?'0':'1')+'">'+(m.enabled?'停用模組':'啟用模組')+'</button>':'')+'</div></article>').join('')+'</div>';}
 function hub(data:Row){return '<div class="lw-summary">'+[['接線 OA',data.accounts.length],['CRM 來客',data.contacts.length],['分類規則',data.rules.filter((r:Row)=>r.enabled).length]].map(r=>'<article><span>'+r[0]+'</span><strong>'+r[1]+'</strong></article>').join('')+'</div>'+panel('LINE OA 工作台','<p>Messaging API 接收 → 會員 CRM → 成交追蹤 → 借址租戶。Login 與 Messaging 的 Channel／Secret 分開設定，Login 登入和訊息外送仍未啟用。</p><div class="lw-shortcuts"><button data-page="line-settings">Messaging API 帳號設定 →</button><button data-page="crm">會員 CRM →</button><button data-page="templates">回覆與選單模板 →</button></div><div class="lw-list">'+(data.accounts.length?data.accounts.map((a:Row)=>'<article class="lw-row"><div><h3>'+e(a.name||'業者 OA')+'</h3><p>Messaging API：'+e(a.channel_id)+' · Provider '+e(a.provider_id)+'</p><p>LINE Login：'+e(a.login_channel_id||'尚未設定')+' · 密鑰 '+e(a.has_login_secret?'已加密保存':'尚未設定')+'</p><p>最後驗簽：'+e(a.last_webhook_at?d.date(a.last_webhook_at):'尚無成功接收')+'</p></div><div>'+badge('Login 未啟用','amber')+'<button data-lw-login="'+e(a.id)+'">設定 LINE Login</button></div></article>').join(''):nothing('尚無業者 OA','請先新增 Messaging API 帳號，再設定該 OA 對應的 LINE Login。'))+'</div>')+panel('關鍵字分類','<p>用於判斷來客想辦理的借址服務，只提出分類建議；不自動回覆、不自動收費，也不把訊息轉送到其他網站。</p><div class="lw-list">'+(data.rules.length?data.rules.map((r:Row)=>'<article class="lw-row"><div><b>'+e(r.keyword)+'</b><p>'+e(r.match_type==='exact'?'完全相同':'包含文字')+' → '+e(destinations[r.destination])+'</p></div><div>'+badge(r.enabled?'已啟用':'停用中',r.enabled?'green':'')+'<button data-lw-route="'+e(r.id)+'">編輯分類</button></div></article>').join(''):nothing('尚無分類','加入常見詢問用語，協助服務人員辨認需求。'))+'</div>','<button data-lw-new-route="1">＋ 新增分類</button>')+panel('LINE 來客與需求','<p>顯示最近 50 位 OA 來客。多個 LINE 身分不會自動合併；請先核對資料，再建立案件。</p><div class="lw-list">'+(data.contacts.length?data.contacts.map((c:Row)=>'<article class="lw-row"><div><b>'+e(c.name)+'</b><p>'+e(c.preview||'沒有可見文字／已收回')+'</p><span>'+c.destinations.map((v:string)=>badge(destinations[v],'green')).join('')+'</span></div><div>'+badge(c.conversation_id?'已連結案件':'待分派',c.conversation_id?'green':'amber')+'<button data-lw-person="'+e(c.person_id)+'">查看會員</button></div></article>').join(''):nothing('尚無來客','完成 Webhook Verify 並開啟 Use webhook 後，客戶傳訊即可建立 CRM 身分。'))+'</div>');}
 function monitor(data:Row){return '<div class="lw-summary">'+[['OA 來客',data.stats.visitors],['待分派',data.stats.unassigned],['逾期跟進',data.stats.overdue],['待核查',data.stats.pending]].map(r=>'<article><span>'+r[0]+'</span><strong>'+r[1]+'</strong></article>').join('')+'</div>'+panel('聊天室 AI 監控','<p>'+e(data.message)+'。僅業者管理員可見，核查記錄不出現在一般 CRM、搜尋或操作歷程。</p><p>'+e(data.scan_scope)+'。規則命中不等於異常成立，請依訊息上下文及正式收款紀錄人工確認。</p>'+badge('AI 模型未啟用','amber')+'<ul>'+data.data_gaps.map((s:string)=>'<li>'+e(s)+'</li>').join('')+'</ul>')+panel('實際回覆人員 · 最近 30 天','<div class="lw-list">'+data.responders.map((r:Row)=>'<article class="lw-row"><div><b>'+e(r.name)+'</b><p>最後回覆：'+e(r.last_reply?d.date(r.last_reply):'尚無紀錄')+'</p></div><div>'+e(r.replies)+' 則回覆 · '+e(r.needs_attention||0)+' 則待留意狀態</div></article>').join('')+'</div>')+panel('管理員私有核查規則','<p>依公司授權的工作通訊範圍設定；未設定時不判讀、不產生虛構告警。內容保存在該業者私有資料庫。</p><div class="lw-list">'+(data.rules.length?data.rules.map((r:Row)=>'<article class="lw-row"><div><b>'+e(r.name)+'</b><p>'+r.keywords.map(e).join('、')+'</p></div><div>'+badge(r.enabled?'核查啟用':'停用中',r.enabled?'green':'')+'<button data-lw-rule="'+e(r.id)+'">編輯規則</button></div></article>').join(''):nothing('尚未設定私有規則','不預設任何截單用語或風險判定。'))+'</div>','<div class="lw-shortcuts"><button data-lw-new-rule="1">＋ 新增規則</button><button data-lw-scan="1" '+(!data.enabled?'disabled':'')+'>掃描工作紀錄</button></div>')+panel('待核查事件','<div class="lw-list">'+(data.events.length?data.events.map((r:Row)=>'<article class="lw-row lw-review"><div><h3>'+e(r.business_name)+' · '+e(r.rule_name)+'</h3><p>'+e(r.message_status==='removed'?'來源訊息已收回，內容不再顯示':r.body)+'</p><p>實際回覆者：'+e(r.responder_name||'缺少可歸屬紀錄')+' · '+e(d.date(r.message_at))+' · '+e(r.message_status)+'</p></div><div>'+badge(reviewNames[r.status],r.status==='pending'?'amber':'')+'<button data-lw-review="'+e(r.id)+'">人工核查</button></div></article>').join(''):nothing('目前沒有核查事件','未掃描、未命中或模型未啟用，不表示已完成 AI 判讀。'))+'</div>')+panel('私有核查歷程','<div class="lw-list">'+(data.reviews.length?data.reviews.map((r:Row)=>'<article class="lw-row"><div><b>'+e(({rule_saved:'保存私有規則',rules_scanned:'執行私有規則掃描',event_reviewed:'人工核查事件'} as Row)[r.action]||r.action)+'</b><p>'+e(r.actor_name)+' · '+e(d.date(r.created_at))+'</p><p>'+e(JSON.parse(r.detail).reference||'')+'</p></div></article>').join(''):nothing('尚無核查歷程','核查操作保留管理員及時間，只有該業者管理員可讀。'))+'</div>');}
 async function showPerson(id:string){person=await d.api('/crm/people/'+encodeURIComponent(id));const p=person;
  d.modal('<div class="lw-panel"><p class="eyebrow">CRM · 會員資料</p><h2>'+e(p.name)+'</h2><p>'+e(p.identity_note)+'</p><form id="lw-person-form" data-id="'+e(p.id)+'" data-version="'+p.version+'"><div class="form-grid">'+input('name','聯絡姓名',p.name,'required maxlength="100"')+input('company_name','企業名稱',p.company_name,'maxlength="150"')+input('phone','電話',p.phone,'maxlength="50"')+input('email','Email',p.email,'type="email" maxlength="200"')+'</div>'+input('tags','標籤（以逗號分隔）',p.tags.join('，'),'maxlength="500"')+area('note','服務備註',p.note,'maxlength="1000"')+'<label>會員狀態<select name="status"><option value="active" '+(p.status==='active'?'selected':'')+'>使用中</option><option value="archived" '+(p.status==='archived'?'selected':'')+'>封存</option></select></label><button class="primary" type="submit">保存會員</button>'+error+'</form><h3>LINE 身分</h3><div class="lw-list">'+(p.links.length?p.links.map((l:Row)=>'<article class="lw-row"><div><b>'+e(l.oa_name||'業者 OA')+'</b><p>Provider '+e(l.provider_id)+' · Messaging Channel '+e(l.channel_id)+'</p><p>'+e(l.conversation_id?'已連結案件聊天室':'尚未連結案件聊天室')+'</p></div>'+badge('驗簽事件身分','green')+'</article>').join(''):nothing('沒有 LINE 身分','人工聯絡資料不等於已綁定 LINE。'))+'</div>'+(mine()&&!p.business_id?'<form id="lw-assign" data-id="'+e(p.id)+'" data-version="'+p.version+'"><label>會員接洽人<select name="assigned_id">'+staffOptions(p.assigned_id||d.me().id)+'</select></label><button type="submit">指派接洽人</button>'+error+'</form>':'')+'<h3>成交案件與借址服務</h3><div class="lw-list">'+p.cases.map((c:Row)=>'<article class="lw-row"><div><b>'+e(c.title)+'</b><p>'+e(c.owner_name)+' · '+e(({contact:'接觸',onboarding:'導入',billing:'收費',won:'成交',paused:'暫緩',lost:'未成交'} as Row)[c.stage])+' · '+e(c.next_action||'下一步待補')+'</p></div>'+(seller()?'<button data-opp="'+e(c.id)+'">開啟案件</button>':'<button data-tenant="'+e(p.business_id)+'">查看租戶服務</button>')+'</article>').join('')+'</div>'+(seller()&&p.status==='active'?'<button class="primary" data-lw-case="'+e(p.id)+'">＋ 建立成交案件</button>':'')+(p.business_id?'<button data-tenant="'+e(p.business_id)+'">查看企業／借址服務 →</button>':'')+'<h3>服務歷程</h3><div class="lw-list">'+p.events.map((v:Row)=>'<article class="lw-row"><div><b>'+e(v.action)+'</b><p>'+e(v.actor_name)+' · '+e(d.date(v.created_at))+'</p></div></article>').join('')+'</div></div>');
 }
 function personForm(){d.modal('<div class="lw-panel"><h2>新增 CRM 會員</h2><p>先保存聯絡資料，確認需求後再建立借址成交案件。</p><form id="lw-new-person"><div class="form-grid">'+input('name','聯絡姓名','','required maxlength="100"')+input('company_name','企業名稱','','maxlength="150"')+input('phone','電話','','maxlength="50"')+input('email','Email','','type="email" maxlength="200"')+'</div>'+area('note','服務備註','','maxlength="1000"')+'<button class="primary" type="submit">建立會員</button>'+error+'</form></div>');}
 function caseForm(){const p=person;d.modal('<div class="lw-panel"><h2>從會員建立成交案件</h2><p>'+e(p.name)+' · '+e(p.business_id?'沿用現有企業，不重複建檔':'成交後同一份資料轉為借址租戶')+'</p><form id="lw-case-form" data-id="'+e(p.id)+'" data-version="'+p.version+'" data-key="'+crypto.randomUUID()+'">'+input('company_name','企業名稱',p.company_name,'required maxlength="150"')+input('title','案件名稱','借址登記與企業服務','required maxlength="150"')+'<div class="form-grid"><label>案件負責人<select name="owner_id" '+(!mine()?'disabled':'')+'>'+staffOptions(d.me().id)+'</select></label>'+input('amount','預估金額（NT$）','0','type="number" required min="0" max="1000000000"')+input('followup_at','下次跟進（台北時間）','','type="datetime-local"')+'</div>'+input('next_action','下一步','','maxlength="500"')+'<button class="primary" type="submit">建立案件並沿用會員</button>'+error+'</form></div>');}
 function templateForm(t:Row={kind:'message',content:'',status:'draft'}){template=t;const cells=t.kind==='rich_menu'?JSON.parse(t.content):Array.from({length:6},()=>({label:'',message:''}));
  d.modal('<div class="lw-panel"><h2>'+e(t.id&&!t.builtin?'編輯模板':'新增模板')+'</h2><form id="lw-template-form" data-id="'+e(t.builtin?'':t.id||'')+'" data-version="'+(t.version||1)+'">'+input('name','模板名稱',t.name||'','required maxlength="100"')+'<div class="form-grid"><label>模板種類<select name="kind" id="lw-template-kind"><option value="message" '+(t.kind==='message'?'selected':'')+'>回覆文字</option><option value="rich_menu" '+(t.kind==='rich_menu'?'selected':'')+'>六格圖文選單</option></select></label><label>草稿狀態<select name="status"><option value="draft" '+(t.status==='draft'?'selected':'')+'>草稿</option><option value="ready" '+(t.status==='ready'?'selected':'')+'>可套用草稿</option></select></label></div><div id="lw-message-fields" '+(t.kind==='rich_menu'?'hidden':'')+'>'+area('content','回覆內容',t.kind==='message'?t.content:'','maxlength="2000"')+'</div><div id="lw-menu-fields" '+(t.kind==='message'?'hidden':'')+'><p>每格填按鈕標題與點擊後的文字訊息；尚未發布至 LINE。</p><div class="lw-cell-editor">'+cells.map((c:Row,i:number)=>'<div><h3>第 '+(i+1)+' 格</h3>'+input('label-'+i,'按鈕標題 '+(i+1),c.label,'maxlength="20"')+input('message-'+i,'點擊文字 '+(i+1),c.message,'maxlength="300"')+'</div>').join('')+'</div></div><button class="primary" type="submit">保存模板草稿</button>'+error+'</form></div>');
 }
 function previewTemplate(id:string){const t=snapshot.items.find((r:Row)=>r.id===id);if(!t)return;template=t;
  const edit=(mine()&&current==='templates'&&(t.operator_id===d.me().operator_id||t.builtin||!t.operator_id))||current==='system-templates';
  d.modal('<div class="lw-panel"><h2>'+e(t.name)+'</h2><p>'+e(t.kind==='message'?'人工回覆草稿，套用不會直接發送':'圖文選單配置預覽，尚未上傳圖片或發布到 LINE')+'</p>'+(t.kind==='message'?'<div class="lw-template-text">'+e(t.content)+'</div>':'<div class="lw-menu-preview">'+JSON.parse(t.content).map((c:Row)=>'<div><b>'+e(c.label)+'</b><small>'+e(c.message)+'</small></div>').join('')+'</div>')+'<div class="lw-shortcuts">'+(current==='templates'&&t.kind==='message'&&t.status==='ready'?'<button class="primary" data-lw-use-template="1">填入聊天室草稿</button>':'')+(edit?'<button data-lw-edit-template="1">'+(t.builtin||current==='templates'&&!t.operator_id?'另存為業者模板':'編輯模板')+'</button>':'')+'</div></div>');
 }
 function ruleForm(r:Row={}){d.modal('<div class="lw-panel"><h2>管理員私有核查規則</h2><p>規則僅產生待核查事件，需管理員人工確認。AI 模型未啟用。</p><form id="lw-rule-form" data-id="'+e(r.id||'')+'" data-version="'+(r.version||1)+'">'+input('name','規則名稱',r.name||'','required maxlength="100"')+area('keywords','核查用語（每行一個）',(r.keywords||[]).join('\n'),'required maxlength="1000"')+'<label class="checkbox"><input type="checkbox" name="enabled" '+(r.enabled?'checked':'')+'>啟用私有核查規則</label><button class="primary" type="submit">保存私有規則</button>'+error+'</form></div>');}
 function routeForm(r:Row={}){d.modal('<div class="lw-panel"><h2>來客關鍵字分類</h2><form id="lw-route-form" data-id="'+e(r.id||'')+'" data-version="'+(r.version||1)+'">'+input('keyword','客戶詢問用語',r.keyword||'','required maxlength="80"')+'<div class="form-grid"><label>比對方式<select name="match_type"><option value="exact" '+(r.match_type==='exact'?'selected':'')+'>完全相同</option><option value="contains" '+(r.match_type==='contains'?'selected':'')+'>包含文字</option></select></label><label>需求分類<select name="destination">'+Object.entries(destinations).map(([k,v])=>'<option value="'+k+'" '+(r.destination===k?'selected':'')+'>'+v+'</option>').join('')+'</select></label></div><label class="checkbox"><input type="checkbox" name="enabled" '+(r.enabled||!r.id?'checked':'')+'>啟用分類建議</label><p>只分類來客需求，不自動回覆或轉送。</p><button class="primary" type="submit">保存分類</button>'+error+'</form></div>');}
 async function click(target:HTMLElement){const t=target.dataset;if(!Object.keys(t).some(k=>k.startsWith('lw')))return false;
  if(t.lwNewPerson)personForm();if(t.lwPerson)await showPerson(t.lwPerson);if(t.lwCase){person=await d.api('/crm/people/'+encodeURIComponent(t.lwCase));caseForm();}
  if(t.lwPager){if(t.lwPager==='next'&&snapshot.next_cursor){cursors[++index]=snapshot.next_cursor;}else if(t.lwPager==='previous'&&index)index--;await d.refresh();}
  if(t.lwNewTemplate)templateForm();if(t.lwTemplate)previewTemplate(t.lwTemplate);
  if(t.lwEditTemplate){let copy=template;if(copy.builtin||current==='templates'&&!copy.operator_id)copy={...copy,id:undefined,builtin:false};templateForm(copy);}
  if(t.lwUseTemplate){const rows=(await d.api('/conversations?paged=1&limit=50')).items;d.modal('<div class="lw-panel"><h2>選擇工作聊天室</h2><p>套用後請檢查內容，再自行按送出；不會自動發訊。</p><form id="lw-compose"><label>聊天室<select name="conversation_id" aria-label="聊天室" required><option value="">請選擇案件</option>'+rows.map((c:Row)=>'<option value="'+e(c.id)+'">'+e(c.business_name)+' / '+e(c.owner_name)+'</option>').join('')+'</select></label><button class="primary" type="submit">套用至草稿</button>'+error+'</form></div>');}
  if(t.lwModule)d.modal('<div class="lw-panel"><h2>更新工作區模組</h2><p>'+e(t.enabled==='1'?'啟用':'停用')+' '+e(t.lwModule)+'，會立即影響此業者的後端功能存取。</p><form id="lw-module-form" data-operator="'+e(t.operator)+'" data-module="'+e(t.lwModule)+'" data-version="'+e(t.version)+'" data-enabled="'+e(t.enabled)+'">'+area('reference','設定依據','','required maxlength="500"')+'<button class="primary" type="submit">保存模組設定</button>'+error+'</form></div>');
  if(t.lwNewRoute)routeForm();if(t.lwRoute)routeForm(snapshot.rules.find((r:Row)=>r.id===t.lwRoute));
  if(t.lwLogin){const a=snapshot.accounts.find((a:Row)=>a.id===t.lwLogin);d.modal('<div class="lw-panel"><h2>'+e(a.name)+' · LINE Login 設定</h2><p>到 LINE Developers → LINE Login → Basic settings；請勿填 LIFF ID 或 Messaging API 的密鑰。設定保存不代表登入流程已開通。</p><form id="lw-login-form" data-id="'+e(a.id)+'" data-version="'+a.login_version+'" autocomplete="off"><div class="form-grid">'+input('channel_id','LINE Login Channel ID',a.login_channel_id,'inputmode="numeric" maxlength="20"')+input('provider_id','LINE Login Provider ID',a.login_provider_id,'inputmode="numeric" maxlength="20"')+'</div>'+input('channel_secret','LINE Login Channel secret（留白沿用）','','type="password" autocomplete="new-password" maxlength="32" '+(!snapshot.storage_ready?'disabled':''))+badge(a.has_login_secret?'密鑰已加密保存':'密鑰尚未設定',a.has_login_secret?'green':'amber')+area('reference','設定依據','','required maxlength="500"')+'<p>Login 與 Messaging API 須由帳號管理員確認是否在相同 Provider；目前不自動合併不同頻道的客戶身分。Login 登入未啟用。</p><button class="primary" type="submit" '+(!snapshot.storage_ready?'disabled':'')+'>保存 Login 設定</button>'+error+'</form></div>');}
  if(t.lwNewRule)ruleForm();if(t.lwRule)ruleForm(snapshot.rules.find((r:Row)=>r.id===t.lwRule));
  if(t.lwScan){target.setAttribute('disabled','');try{const r=await d.api('/admin/risk/scan','POST',{});await d.refresh();d.toast('新增 '+r.created+' 筆待核查事件；沒有 AI 判讀或對外通知');}finally{target.removeAttribute('disabled');}}
  if(t.lwReview){const r=snapshot.events.find((r:Row)=>r.id===t.lwReview);d.modal('<div class="lw-panel"><h2>人工核查事件</h2><p>'+e(r.business_name)+' · '+e(r.rule_name)+'</p><form id="lw-review-form" data-id="'+e(r.id)+'" data-version="'+r.version+'"><label>核查狀態<select name="status">'+Object.entries(reviewNames).map(([k,v])=>'<option value="'+k+'" '+(r.status===k?'selected':'')+'>'+v+'</option>').join('')+'</select></label>'+area('reference','核查依據','','required maxlength="1000"')+'<button class="primary" type="submit">保存核查紀錄</button>'+error+'</form></div>');}
  return true;
 }
 async function submit(form:HTMLFormElement){if(!form.id.startsWith('lw-'))return false;const v=Object.fromEntries(new FormData(form)) as Row,ds=form.dataset,id=ds.id,ver=Number(ds.version),close=()=>document.querySelector<HTMLDialogElement>('#modal')?.close();
  if(form.id==='lw-search'){q=v.q;if(current==='crm'){status=v.status;tag=v.tag;}index=0;cursors=[null];await d.refresh();return true;}
  if(form.id==='lw-new-person'){const r=await d.api('/crm/people','POST',v);await d.refresh();await showPerson(r.id);return true;}
  if(form.id==='lw-person-form'){await d.api('/crm/people/'+id,'PATCH',{...v,tags:v.tags.split(/[,，]/).map((s:string)=>s.trim()).filter(Boolean),version:ver});await d.refresh();await showPerson(id!);return true;}
  if(form.id==='lw-assign'){await d.api('/crm/people/'+id+'/assign','PATCH',{...v,version:ver});await d.refresh();await showPerson(id!);return true;}
  if(form.id==='lw-case-form'){const r=await d.api('/crm/people/'+id+'/case','POST',{...v,amount:Number(v.amount),owner_id:mine()?v.owner_id:d.me().id,followup_at:d.followUTC(v.followup_at),version:ver,request_key:ds.key});await d.refresh();await d.openCase(r.id);return true;}
  if(form.id==='lw-template-form'){const content=v.kind==='message'?v.content:JSON.stringify(Array.from({length:6},(_,i)=>({label:v['label-'+i],message:v['message-'+i]})));await d.api((current==='system-templates'?'/platform':'')+'/templates'+(id?'/'+id:''),id?'PATCH':'POST',{name:v.name,kind:v.kind,status:v.status,content,...(id?{version:ver}:{})});close();await d.refresh();d.toast('模板草稿已保存，尚未發布到 LINE');return true;}
  if(form.id==='lw-compose'){close();await d.compose(v.conversation_id,template.content);return true;}
  if(form.id==='lw-module-form'){await d.api('/platform/modules/'+ds.operator+'/'+ds.module,'PATCH',{enabled:ds.enabled==='1',version:ver,reference:v.reference});}
  if(form.id==='lw-route-form'){await d.api('/line/hub/routes'+(id?'/'+id:''),id?'PATCH':'POST',{...v,enabled:v.enabled==='on',...(id?{version:ver}:{})});}
  if(form.id==='lw-login-form'){try{await d.api('/line/hub/accounts/'+id+'/login','PATCH',{...v,version:ver});}finally{(form.elements.namedItem('channel_secret') as HTMLInputElement).value='';delete v.channel_secret;}}
  if(form.id==='lw-rule-form'){await d.api('/admin/risk/rules'+(id?'/'+id:''),id?'PATCH':'POST',{name:v.name,keywords:v.keywords.split('\n').map((s:string)=>s.trim()).filter(Boolean),enabled:v.enabled==='on',...(id?{version:ver}:{})});}
  if(form.id==='lw-review-form'){await d.api('/admin/risk/events/'+id,'PATCH',{...v,version:ver});}
  close();await d.refresh();d.toast('設定已保存；實際操作人員已記錄');return true;
 }
 document.addEventListener('change',ev=>{const t=ev.target as HTMLSelectElement;if(t.id==='lw-template-kind'){document.querySelector<HTMLElement>('#lw-message-fields')!.hidden=t.value!=='message';document.querySelector<HTMLElement>('#lw-menu-fields')!.hidden=t.value!=='rich_menu';}});
 return{pages,path,render,click,submit,reset};
}
