type Row=Record<string,any>;
type Deps={api:(path:string,method?:string,data?:Row)=>Promise<any>;e:(v:unknown)=>string;badge:(v:string,tone?:string)=>string;date:(v:string)=>string;modal:(html:string)=>void;toast:(s:string)=>void;me:()=>Row;refresh:()=>Promise<void>};
export function monitorConsole(d:Deps,legacy:(data:Row)=>string){
 const {e,badge}=d,tabs:Row={chat:'LINE 聊天室',usage:'用量總覽',groups:'群組商機',calls:'AI 呼叫紀錄'};
 let tab='chat',days=7,q='',status='all',cursors:(string|null)[]=[null],index=0,snapshot:Row={},auto=false,busy=false,queued=false,timer:ReturnType<typeof setInterval>|undefined,actorId='';
 const names:Row={pending:'待確認',reviewing:'處理中',accepted:'確認商機',discarded:'不採用',success:'成功',failed:'失敗',cached:'快取',fallback:'備援'};
 const panel=(title:string,html:string,action='')=>'<section class="panel lw-panel"><div class="panel-heading"><h2>'+e(title)+'</h2>'+action+'</div>'+html+'</section>';
 const empty=(s:string)=>'<div class="lw-empty">'+e(s)+'</div>';
 const num=(v:unknown)=>v===null||v===undefined?'未回報':Number(v).toLocaleString('zh-TW');
 const cost=(v:unknown)=>v===null||v===undefined?'未定價':new Intl.NumberFormat('zh-TW',{style:'currency',currency:'USD',minimumFractionDigits:4,maximumFractionDigits:6}).format(Number(v)/1000000);
 const input=(name:string,label:string,value='',attrs='')=>'<label>'+e(label)+'<input name="'+name+'" value="'+e(value)+'" '+attrs+'></label>';
 const area=(name:string,label:string,value='')=>'<label>'+e(label)+'<textarea name="'+name+'" maxlength="1000" required>'+e(value)+'</textarea></label>';
 const error='<p class="form-error" role="alert"></p>',close=()=>document.querySelector<HTMLDialogElement>('#modal')?.close();
 function path(){return '/admin/monitor?tab='+tab+'&days='+days+'&q='+encodeURIComponent(q)+'&status='+status+'&limit=30'+(cursors[index]?'&cursor='+encodeURIComponent(cursors[index]!):'');}
 function leave(){if(timer)clearInterval(timer);timer=undefined;auto=false;}
 function reset(){leave();tab='chat';days=7;q='';status='all';cursors=[null];index=0;}
 async function reload(){if(busy){queued=true;return;}busy=true;try{do{queued=false;await d.refresh();}while(queued);}finally{busy=false;}}
 function polling(){if(timer)clearInterval(timer);timer=undefined;if(!auto)return;
  timer=setInterval(()=>{if(d.me()?.id!==actorId){leave();return;}if(document.hidden||!document.querySelector('#mc-console')||document.querySelector('#modal[open]')||document.activeElement?.matches('input,textarea,select')||busy)return;void reload().catch(()=>d.toast('監控更新失敗，請重新整理'));},30000);
 }
 const pagination=()=>'<div class="list-pagination"><span>共 '+num(snapshot.total)+' 筆 · 第 '+(index+1)+' 頁</span><div><button data-mc-pager="previous" '+(!index?'disabled':'')+'>上一頁</button><button data-mc-pager="next" '+(!snapshot.next_cursor?'disabled':'')+'>下一頁</button></div></div>';
 function filters(){const opts=tab==='chat'?{all:'全部紀錄',attention:'需注意的送出狀態',in:'客戶來訊',out:'人員回覆'}:tab==='groups'?{all:'全部商機',pending:'待確認',reviewing:'處理中',accepted:'確認商機',discarded:'不採用'}:{all:'全部呼叫',success:'成功',failed:'失敗',cached:'快取',fallback:'備援'};
  return '<form id="mc-filter" class="mc-filters">'+input('q',tab==='chat'?'搜尋企業／訊息／回覆人員':tab==='groups'?'搜尋群組／規則／訊息':'搜尋功能／模型',q,'maxlength="100"')+'<label>紀錄篩選<select name="status">'+Object.entries(opts).map(([v,n])=>'<option value="'+v+'" '+(status===v?'selected':'')+'>'+n+'</option>').join('')+'</select></label><button type="submit">搜尋紀錄</button>'+error+'</form>';
 }
 function render(data:Row){if(data.tab!==tab||data.period.days!==days)return '<div id="mc-console"><p class="loading">正在更新監控資料…</p></div>';snapshot=data;actorId=d.me().id;polling();
  const header='<div class="mc-toolbar" role="tablist" aria-label="監控分頁">'+Object.entries(tabs).map(([key,label])=>'<button role="tab" aria-selected="'+(key===tab)+'" data-mc-tab="'+key+'" class="'+(key===tab?'mc-active':'')+'">'+label+'</button>').join('')+'</div><div class="mc-options"><label>統計期間<select id="mc-period">'+[1,7,30,90].map(n=>'<option value="'+n+'" '+(days===n?'selected':'')+'>最近 '+n+' 天</option>').join('')+'</select></label><label class="check"><input type="checkbox" id="mc-auto" '+(auto?'checked':'')+'>每 30 秒更新</label><button data-mc-refresh="1">重新整理</button><span>更新於 '+e(d.date(data.updated_at))+'</span></div>';
  const stats=data.stats||{},cards='<div class="lw-summary mc-summary">'+[['已觀測訊息／身分',num(stats.messages)+' / '+num(stats.members)],['待處理／送出需注意',num(stats.pending)+' / '+num(stats.attention)],['新商機',num(stats.new_opportunities)],['啟用群組／規則',num(stats.enabled_groups)+' / '+num(stats.enabled_rules)]].map(([n,v])=>'<article><span>'+n+'</span><strong>'+v+'</strong></article>').join('')+'</div>';
  const notice='<details class="mc-help"><summary>監控說明與資料界線</summary><p>僅本業者管理員可讀取。LINE 聊天室顯示平台已有的授權對話與未分派來客；原生 OA 後台人工回覆者無法歸屬。群組只在明確啟用後保存文字，成員數為曾傳訊且可識別的身分，並非群組全部成員。</p><p>群組商機由關鍵字及同則訊息的情境用語產生規則候選，仍須人工確認。AI 模型未啟用；不讀私人 LINE，不自動告警、回覆、建案或收費。</p></details>';
  let content='';
  if(tab==='chat')content=panel('LINE 聊天室紀錄',filters()+'<div class="lw-list">'+(data.items.length?data.items.map((r:Row)=>'<article class="lw-row"><div><h3>'+e(r.business_name)+'</h3><p>'+e(r.status==='removed'?'來源訊息已收回':r.body)+'</p><p>'+e(r.direction==='in'?'客戶來訊':r.responder_name||'回覆者不可歸屬')+' · '+e(d.date(r.created_at))+'</p></div><div>'+badge(r.status)+(r.status==='simulated'||r.status==='received_demo'?badge('測試／模擬','amber'):'')+'<button data-mc-chat="'+e(r.conversation_id||r.contact_id)+'" data-kind="'+(r.conversation_id?'chats':'inbox')+'">查看對話</button>'+(r.person_id?'<button data-lw-person="'+e(r.person_id)+'">查看會員</button>':'')+'</div></article>').join(''):empty('本期間尚無聊天室紀錄；未接收資料不表示已完成分析。'))+'</div>'+pagination())+legacy(data.legacy);
  if(tab==='usage'){const t=data.total;content=panel('AI 用量總覽','<p>依實際模型呼叫紀錄計量。Token 未回報或價格未議定時保留未知，不當成免費；此處不扣款、不結算。</p><div class="lw-summary">'+[['實際呼叫',num(t.requests)],['輸入 Token',num(t.input_tokens)],['輸出 Token',num(t.output_tokens)],['總 Token',num(t.total_tokens)],['供應商成本',cost(t.provider_cost_micros)],['計費預估',cost(t.billable_cost_micros)]].map(([n,v])=>'<article><span>'+n+'</span><strong>'+v+'</strong></article>').join('')+'</div>')+breakdown('依功能',data.by_feature,(r:Row)=>r.feature)+breakdown('依模型',data.by_model,(r:Row)=>r.provider+' / '+r.model)+breakdown('依操作人員',data.by_actor,(r:Row)=>r.actor_name);}
  if(tab==='calls')content=panel('AI 呼叫紀錄',filters()+'<p>僅保存呼叫狀態、用量、延遲與安全錯誤代碼；不保存原始提示詞、對話正文或密鑰。</p><div class="lw-list">'+(data.items.length?data.items.map((r:Row)=>'<article class="lw-row"><div><h3>'+e(r.feature)+' · '+e(r.provider)+' / '+e(r.model)+'</h3><p>'+e(r.actor_name)+' · '+e(d.date(r.created_at))+'</p><p>'+num(r.total_tokens)+' Token · '+num(r.latency_ms)+' ms · 成本 '+cost(r.provider_cost_micros)+'</p><p>'+e(r.error_code||'')+'</p></div><div>'+badge(names[r.status],r.status==='failed'?'amber':'')+'</div></article>').join(''):empty('本期間沒有 AI 呼叫紀錄。模型尚未啟用，不產生示範成功紀錄。'))+'</div>'+pagination());
  if(tab==='groups')content=panel('群組商機',filters()+'<p>只列出符合已啟用規則的候選，不是所有好友或所有群組訊息。管理員確認後可連結 CRM 會員，仍不自動成交。</p><div class="lw-list">'+(data.items.length?data.items.map((r:Row)=>'<article class="lw-row"><div><h3>'+e(r.group_name)+' · '+e(r.rule_name)+'</h3><p>'+e(r.removed?'來源訊息已收回，內容不再顯示':r.body)+'</p><p>'+e(d.date(r.message_at))+' · 規則候選，非 AI 判讀</p></div><div>'+badge(names[r.status],r.status==='pending'?'amber':'')+'<button data-mc-review="'+e(r.id)+'">查看／處理商機</button>'+(r.person_id?'<button data-lw-person="'+e(r.person_id)+'">開啟 CRM 會員</button>':'')+'</div></article>').join(''):empty('尚無符合條件的群組紀錄。請先選擇群組及關鍵字／情境規則，再人工掃描。'))+'</div>'+pagination(),'<button data-mc-manage="1">群組規則與商機管理</button>')+groupConfiguration(data);
  return '<div id="mc-console">'+header+notice+badge('AI 模型未啟用','amber')+(tab==='chat'||tab==='groups'?cards:'')+content+'</div>';
 }
 function breakdown(title:string,rows:Row[],label:(r:Row)=>string){return panel(title,'<div class="lw-list">'+(rows.length?rows.map(r=>'<article class="lw-row"><div><h3>'+e(label(r))+'</h3><p>'+num(r.requests)+' 次 · '+num(r.total_tokens)+' Token · 失敗 '+num(r.failed)+' 次</p></div><div>成本 '+cost(r.provider_cost_micros)+' · 計費預估 '+cost(r.billable_cost_micros)+'</div></article>').join(''):empty('本期尚無 AI 用量。'))+'</div>');}
 function groupConfiguration(data:Row){return panel('群組啟用管理','<p>Webhook 已驗簽發現的群組預設未啟用。啟用只保存往後接收的文字；停用後不新增文字，舊商機及處理歷程保留。這裡只列最近 100 個群組。</p><div class="lw-list">'+(data.groups.length?data.groups.map((g:Row)=>'<article class="lw-row"><div><h3>'+e(g.name)+'</h3><p>最後事件 '+e(d.date(g.last_event_at))+'</p></div><div>'+badge(g.departed?'OA 已離開':g.enabled?'已啟用':'已發現／未啟用',g.enabled?'green':'amber')+'<button data-mc-group="'+e(g.id)+'">設定群組</button></div></article>').join(''):empty('尚未收到群組事件。OA 必須先加入群組並完成業者 Webhook 設定。'))+'</div>')+panel('群組關鍵字與情境規則','<p>關鍵字及情境用語都要在同則訊息命中。規則不使用 AI 模型，掃描上限為最近 500 則已保存文字。</p><div class="lw-list">'+(data.rules.length?data.rules.map((r:Row)=>'<article class="lw-row"><div><h3>'+e(r.name)+'</h3><p>關鍵字：'+e(r.keywords.join('、'))+' · 情境：'+e(r.context_words.join('、'))+'</p></div><div>'+badge(r.enabled?'啟用中':'停用中')+'<button data-mc-rule="'+e(r.id)+'">編輯群組規則</button></div></article>').join(''):empty('尚無群組規則，不會預設任何判讀條件。'))+'</div>','<div class="lw-shortcuts"><button data-mc-new-rule="1">新增群組規則</button><button data-mc-scan="1" '+(!data.rules.some((r:Row)=>r.enabled)?'disabled':'')+'>掃描群組紀錄</button></div>')+panel('群組處理歷程','<div class="lw-list">'+(data.reviews.length?data.reviews.map((r:Row)=>'<article class="lw-row"><div><b>'+e(({group_configured:'設定群組啟停',group_rule_saved:'保存群組規則',group_rules_scanned:'掃描群組規則',group_opportunity_reviewed:'處理群組商機'} as Row)[r.action])+'</b><p>'+e(r.actor_name)+' · '+e(d.date(r.created_at))+'</p><p>'+e(r.reference)+'</p></div></article>').join(''):empty('尚無群組處理歷程。'))+'</div>');}
 function ruleForm(r:Row={}){d.modal('<div class="lw-panel"><h2>群組關鍵字與情境規則</h2><form id="mc-rule-form" data-id="'+e(r.id||'')+'" data-version="'+(r.version||1)+'">'+input('name','群組規則名稱',r.name||'','required maxlength="100"')+area('keywords','群組關鍵字（每行一個）',(r.keywords||[]).join('\n'))+area('context_words','情境用語（每行一個）',(r.context_words||[]).join('\n'))+'<label class="check"><input type="checkbox" name="enabled" '+(r.enabled?'checked':'')+'>啟用群組規則</label><p>每欄 1 至 10 個用語，每個最多 80 字；同則訊息需同時命中兩欄。</p><button class="primary" type="submit">保存群組規則</button>'+error+'</form></div>');}
 async function click(target:HTMLElement){const t=target.dataset;if(!Object.keys(t).some(k=>k.startsWith('mc')))return false;
  if(t.mcTab){tab=t.mcTab;status='all';q='';cursors=[null];index=0;await reload();}
  if(t.mcRefresh)await reload();
  if(t.mcPager){if(t.mcPager==='next'&&snapshot.next_cursor)cursors[++index]=snapshot.next_cursor;else if(t.mcPager==='previous'&&index)index--;await reload();}
  if(t.mcChat){const r=await d.api('/admin/monitor/'+t.kind+'/'+encodeURIComponent(t.mcChat)+'?days='+days);d.modal('<div class="lw-panel"><h2>'+e(r.chat.business_name)+'</h2><p>依目前期間顯示最近 100 則授權對話；送出狀態不代表對方已閱讀。</p><div class="lw-list">'+(r.items.length?r.items.map((m:Row)=>'<article class="lw-row"><div><b>'+e(m.direction==='in'?'客戶來訊':m.responder_name||'無法歸屬')+'</b><p>'+e(m.status==='removed'?'來源訊息已收回':m.body)+'</p><p>'+e(d.date(m.created_at))+' · '+e(m.status)+' '+e(m.delivery_state||'')+' '+e(m.delivery_error||'')+'</p></div></article>').join(''):empty('本期間無訊息。'))+'</div></div>');}
  if(t.mcManage)document.querySelector('#mc-console .lw-panel:nth-last-child(3)')?.scrollIntoView({behavior:'smooth',block:'start'});
  if(t.mcGroup){const g=snapshot.groups.find((g:Row)=>g.id===t.mcGroup);d.modal('<div class="lw-panel"><h2>設定群組</h2><form id="mc-group-form" data-id="'+e(g.id)+'" data-version="'+g.version+'">'+input('name','群組顯示名稱',g.name,'required maxlength="100"')+'<label class="check"><input type="checkbox" name="enabled" '+(g.enabled?'checked':'')+' '+(g.departed?'disabled':'')+'>啟用此群組觀測</label>'+area('reference','啟停依據')+'<button class="primary" type="submit">保存群組設定</button>'+error+'</form></div>');}
  if(t.mcNewRule)ruleForm();if(t.mcRule)ruleForm(snapshot.rules.find((r:Row)=>r.id===t.mcRule));
  if(t.mcScan){const r=await d.api('/admin/monitor/group-scan','POST',{days});await reload();d.toast('新增 '+r.created+' 筆規則候選；沒有 AI 呼叫或外送');}
  if(t.mcReview){const r=snapshot.items.find((r:Row)=>r.id===t.mcReview);const modules=await d.api('/workspace/modules');const crm=modules.modules.some((m:Row)=>m.key==='crm'&&m.enabled);const people=crm?(await d.api('/crm/people?limit=50')).items:[];
   d.modal('<div class="lw-panel"><h2>群組商機人工確認</h2><p>'+e(r.removed?'來源訊息已收回':r.body)+'</p><form id="mc-review-form" data-id="'+e(r.id)+'" data-version="'+r.version+'"><label>商機狀態<select name="status">'+['pending','reviewing','accepted','discarded'].map(s=>'<option value="'+s+'" '+(r.status===s?'selected':'')+'>'+names[s]+'</option>').join('')+'</select></label><label>連結 CRM 會員<select name="person_id" '+(!crm?'disabled':'')+'><option value="">尚未連結／解除連結</option>'+(r.person_id&&!people.some((p:Row)=>p.id===r.person_id)?'<option value="'+e(r.person_id)+'" selected>既有連結會員</option>':'')+people.map((p:Row)=>'<option value="'+e(p.id)+'" '+(r.person_id===p.id?'selected':'')+'>'+e(p.name)+' · '+e(p.company_name||'')+'</option>').join('')+'</select></label>'+area('reference','確認依據')+'<p>若尚無會員，先至會員 CRM 建檔，再返回連結；只顯示最近 50 位，不以群組身分自動合併。'+(!crm?'CRM 模組已停用，可先完成商機核查。':'')+'</p><button class="primary" type="submit">保存商機確認</button>'+error+'</form></div>');
  }
  return true;
 }
 async function submit(form:HTMLFormElement){if(!form.id.startsWith('mc-'))return false;const v=Object.fromEntries(new FormData(form)) as Row,id=form.dataset.id,ver=Number(form.dataset.version);
  if(form.id==='mc-filter'){q=v.q;status=v.status;cursors=[null];index=0;await reload();return true;}
  if(form.id==='mc-group-form')await d.api('/admin/monitor/groups/'+id,'PATCH',{name:v.name,enabled:v.enabled==='on',reference:v.reference,version:ver});
  if(form.id==='mc-rule-form')await d.api('/admin/monitor/group-rules'+(id?'/'+id:''),id?'PATCH':'POST',{name:v.name,keywords:v.keywords.split('\n').map((s:string)=>s.trim()).filter(Boolean),context_words:v.context_words.split('\n').map((s:string)=>s.trim()).filter(Boolean),enabled:v.enabled==='on',...(id?{version:ver}:{})});
  if(form.id==='mc-review-form')await d.api('/admin/monitor/opportunities/'+id,'PATCH',{status:v.status,person_id:v.person_id||null,reference:v.reference,version:ver});
  close();await reload();d.toast('已保存；沒有自動建案、發送或收費');return true;
 }
 document.addEventListener('change',event=>{const t=event.target as HTMLInputElement;if(t.id==='mc-auto'){auto=t.checked;polling();}if(t.id==='mc-period'){days=Number(t.value);cursors=[null];index=0;void reload().catch(()=>d.toast('期間更新失敗'));}});
 return {path,render,click,submit,reset,leave};
}
